#include "core/i18n.h"

// Spanish.
//
// Generated by tools/gen_lang_tables.py from tools/lang_data.py, in the shape
// of lang_fr.cpp - same sections, same order - so any two languages can be
// read side by side. Edit the table, not this file.
//
// Left column: the English exactly as it is written in the code, which is the
// key. Reword a line in a scene and the row here stops matching in silence,
// which is what `tools/i18n_scan.py --lang es` is for. A string this
// language has not been given yet is simply absent, and comes out in English.

namespace nxp {
namespace {

    const Translation kEntries[] = {
        // ------------------------------------------------------------- tabs
        { "Nearby", "Cerca de ti" },
        { "The Square", "La plaza" },
        { "Games", "Juegos" },
        { "The shop", "La tienda" },
        { "Trophies", "Trofeos" },
        { "Your pass", "Tu tarjeta" },
        { "Settings", "Ajustes" },

        // ------------------------------------------------- the hint strip
        { "again", "otra vez" },
        { "back", "atrás" },
        { "block", "bloquear" },
        { "cancel", "cancelar" },
        { "change", "cambiar" },
        { "choose", "elegir" },
        { "close", "cerrar" },
        { "done", "hecho" },
        { "fill the screen", "pantalla completa" },
        { "give up", "rendirse" },
        { "jump - hold to go higher", "saltar - mantén para más alto" },
        { "jump ten", "diez más" },
        { "left and right to change", "izquierda y derecha para cambiar" },
        { "look now", "buscar ahora" },
        { "mark read", "marcar leído" },
        { "next pass", "tarjeta siguiente" },
        { "open", "abrir" },
        { "open section", "abrir sección" },
        { "play", "jugar" },
        { "roll", "tirar" },
        { "roll again", "tirar otra vez" },
        { "run", "correr" },
        { "run again", "correr otra vez" },
        { "save / load", "guardar / cargar" },
        { "save face", "guardar cara" },
        { "shuffle", "al azar" },
        { "shuffle face", "cara al azar" },
        { "spin", "girar" },
        { "start", "empezar" },

        // --------------------------------------------------------- buttons
        { "Make my pass", "Crear mi tarjeta" },
        { "Not now", "Ahora no" },
        { "Run", "Correr" },
        { "Run again", "Correr otra vez" },
        { "Start stacking", "Empezar a apilar" },
        { "Stack again", "Apilar otra vez" },

        // ------------------------------------------- eyebrows and captions
        { "games", "juegos" },
        { "trophies", "trofeos" },
        { "the shop", "la tienda" },
        { "the square", "la plaza" },
        { "the mii race", "la carrera de Miis" },
        { "the mii tower", "la torre de Miis" },
        { "the dice duel", "el duelo de dados" },
        { "the wheel", "la rueda" },
        { "the quest", "la búsqueda" },
        { "what it pays", "lo que paga" },
        { "your prediction", "tu pronóstico" },
        { "your pairing code", "tu código de emparejamiento" },
        { "people met", "personas conocidas" },
        { "times your pass was sent", "veces que se envió tu tarjeta" },
        { "floors", "pisos" },
        { "best %u %s", "récord %u %s" },

        // ------------------------------------------------------ the games
        { "Something to do", "Algo que hacer" },
        { "Played with the faces and names in your collection, so the "
          "more people you have crossed, the more there is here.",
            "Se juega con las caras y los nombres de tu colección: cuanta "
            "más gente hayas cruzado, más hay aquí." },

        { "The Mii race", "La carrera de Miis" },
        { "Three of the people you have crossed, against your own Mii, "
          "and nobody is faster than anybody.\nWatch for nothing, bet a "
          "coin for three back, or call first and second for eleven.",
            "Tres de las personas que has cruzado, contra tu propio Mii, "
            "y nadie es más rápido que nadie.\nMira gratis, apuesta una "
            "moneda para tres de vuelta, o canta 1º y 2º para once." },

        { "The dice duel", "El duelo de dados" },
        { "One roll each against somebody you have crossed, and the "
          "highest takes it.\nRoll for nothing, or bet two coins for "
          "three back - and a draw hands your two back.",
            "Una tirada cada uno contra alguien que has cruzado, y gana "
            "la más alta.\nTira gratis, o apuesta dos monedas para tres "
            "de vuelta - un empate te devuelve tus dos." },

        { "The lantern wheel", "La rueda de farolillos" },
        { "Twelve lanterns and a needle, and two of them are a puzzle "
          "piece.\nWatch it for nothing, or ten coins a spin - every "
          "lantern pays something, and one in six is a piece.",
            "Doce farolillos y una aguja, y dos de ellos son una pieza de "
            "puzle.\nMira gratis, o diez monedas por giro - cada "
            "farolillo paga algo, y uno de cada seis es una pieza." },

        { "The bandit", "El bandido" },
        { "Three reels, and two machines: three symbols that pay small "
          "and often, or five that pay rarely and big.\nA coin a spin, "
          "or spin for nothing - two bells hand the coin back, and the "
          "board on the wall lists every line it pays.",
            "Tres rodillos y dos máquinas: tres símbolos que pagan poco y "
            "a menudo, o cinco que pagan rara vez y en grande.\nUna "
            "moneda por giro, o gratis - dos campanas devuelven la "
            "moneda, y el tablero de la pared lista cada combinación." },

        { "The Mii tower", "La torre de Miis" },
        { "Stack the people you have crossed, one drop at a time.\nMiss "
          "the shoulders below and they fall; drift too far from the "
          "base and the lot goes over.",
            "Apila a las personas que has cruzado, una por "
            "soltada.\nFalla los hombros de abajo y se caen; aléjate "
            "demasiado de la base y todo se derrumba." },

        { "Plaza dash", "Plaza Dash" },
        { "Your own Mii running through the plaza, jumping what the "
          "market leaves in the way.\nIt gets quicker. Nothing staked, "
          "nothing won - only how far you got.",
            "Tu propio Mii corre por el plaza saltando lo que el mercado "
            "deja en medio.\nSe acelera. Nada apostado, nada ganado - "
            "solo hasta dónde llegaste." },

        // ------------------------------------------------ settings: sections
        { "%s never sends your name or an exact position. You choose "
          "how much of a pass leaves the console.",
            "%s nunca envía tu nombre ni una posición exacta. Tú eliges "
            "cuánto de una tarjeta sale de la consola." },
        { "How passes find their way to you.", "Cómo las tarjetas llegan hasta ti." },
        { "Nothing interrupts a game. The plaza waits.",
            "Nada interrumpe una partida. El plaza espera." },
        { "The app opens in daylight. Dark is for a dim room, or match "
          "whatever the console is set to.",
            "La app se abre en claro. Oscuro es para una habitación en "
            "penumbra, o sigue a la consola." },
        { "The app is written in English and says what it has been "
          "taught to say in anything else. Whatever a language is "
          "missing stays in English.",
            "La app está escrita en inglés y dice en los demás idiomas lo "
            "que se le ha enseñado. Lo que le falte a un idioma se queda "
            "en inglés." },
        { "Where your passes go, and how another console recognises this one.",
            "A dónde van tus tarjetas, y cómo otra consola reconoce esta." },
        { "Everything the app keeps lives on the SD card, and all of it can go.",
            "Todo lo que la app guarda está en la tarjeta SD, y todo puede irse." },
        { "What this build of %s is, who made it, and where it came from.",
            "Qué es esta versión de %s, quién la hizo y de dónde viene." },

        // ---------------------------------------------------- settings: rows
        { "English - what the app is written in",
            "Inglés - el idioma en que está escrita la app" },
        { "Share where we crossed", "Compartir dónde nos cruzamos" },
        { "District only - never a street or a venue you did not name",
            "Solo el barrio - nunca una calle ni un lugar que no hayas nombrado" },
        { "District label", "Nombre del barrio" },
        { "e.g. Namba Station", "p. ej. Namba Station" },
        { "City label", "Nombre de la ciudad" },
        { "used when sharing is set to City",
            "se usa cuando compartir está en Ciudad" },
        { "Show what I am playing", "Mostrar a qué juego" },
        { "The title, your hours in it, and how many games you have. "
          "Hidden titles stay hidden, always",
            "El juego, tus horas en él y cuántos juegos tienes. Los "
            "juegos ocultos siguen ocultos, siempre" },
        { "Exchange passes automatically", "Intercambiar tarjetas automáticamente" },
        { "Trades happen while the app is open",
            "Los intercambios ocurren mientras la app está abierta" },
        { "How far a crossing reaches", "Alcance de un cruce" },
        { "Same network is the closest thing to walking past someone",
            "La misma red es lo más parecido a cruzarse por la calle" },
        { "Crossings per day", "Cruces por día" },
        { "Tell me when passes arrive", "Avisarme cuando lleguen tarjetas" },
        { "A card in the corner, never an interruption",
            "Una tarjeta en la esquina, nunca una interrupción" },
        { "Theme", "Tema" },
        { "Hold the scenery still", "Mantener el fondo quieto" },
        { "On, for anybody the Plaza Dash minigame makes queasy: the "
          "background stops moving and only what you have to dodge "
          "does. Turn it off for the full parallax",
            "Activado, para quien se marea con el minijuego Plaza Dash: "
            "el fondo se detiene y solo se mueve lo que hay que esquivar. "
            "Desactívalo para el paralaje completo" },
        { "Plaza server", "Servidor del plaza" },
        { "Wi-Fi match token", "Token de Wi-Fi" },
        { "Check in now", "Conectar ahora" },
        { "Blocked consoles", "Consolas bloqueadas" },
        { "Clear the whole list", "Vaciar toda la lista" },
        { "unblock", "desbloquear" },
        { "none", "ninguno" },
        { "Write a log file", "Escribir un archivo de registro" },
        { "Copy everything to a backup folder",
            "Copiar todo a una carpeta de respaldo" },
        { "Your identity, your pass and your collection, into backup/ on this card",
            "Tu identidad, tu tarjeta y tu colección, en backup/ de esta tarjeta" },
        { "Download puzzle art", "Descargar las imágenes de los puzles" },
        { "Delete every pass you have collected",
            "Borrar todas las tarjetas recogidas" },
        { "This cannot be undone", "Esto no se puede deshacer" },
        { "Start over as someone new", "Empezar de cero como otra persona" },
        { "New id, new pass; everything you handed out goes unlinkable",
            "Nueva id, nueva tarjeta; todo lo repartido queda sin vínculo" },
        { "Check for updates", "Buscar actualizaciones" },
        { "Check on every launch", "Comprobar en cada inicio" },
        { "One request when the app opens; it never installs on its own",
            "Una petición al abrir la app; nunca se instala solo" },
        { "Developed by Insektaure", "Desarrollado por Insektaure" },
        { "Find us on GitHub !", "¡Encuéntranos en GitHub!" },
        { "This console's id", "Id de esta consola" },

        // -------------------------------------------------- settings: toasts
        { "Not connected to the plaza", "Sin conexión al plaza" },
        { "This one needs the server. The dot by the tabs turns green "
          "when it can be reached.",
            "Esto necesita el servidor. El punto junto a las pestañas se "
            "pone verde cuando se puede acceder." },
        { "Busy with another download", "Hay otra descarga en curso" },
        { "Wait for the update in About to finish, then try again.",
            "Espera a que termine la actualización en Acerca de e "
            "inténtalo otra vez." },
        { "Downloading puzzle art", "Descargando las imágenes" },
        { "This row shows how it is going.", "Esta fila muestra cómo va." },
        { "Could not back up", "No se pudo respaldar" },
        { "Backed up to %s", "Respaldado en %s" },
        { "It is on the same card. Copy the backup folder to a computer "
          "to be safe from losing the card itself.",
            "Está en la misma tarjeta. Copia la carpeta de respaldo a un "
            "ordenador para no depender de la tarjeta." },
        { "Checking in", "Conectando" },
        { "Unblocked %s", "%s desbloqueado" },
        { "They can cross you again, unless they blocked you as well.",
            "Pueden volver a cruzarse contigo, salvo que también te hayan bloqueado." },

        // ---------------------------------------------------- the Mii race
        { "Four runners, one line", "Cuatro corredores, una línea" },
        { "Nobody is faster than anybody. Nothing you do changes that.",
            "Nadie es más rápido que nadie. Nada de lo que hagas lo cambia." },
        { "Race for free", "Competir gratis" },
        { "Bet 1 coin - your Mii to win", "Apuesta 1 moneda - que gane tu Mii" },
        { "Predict 1st and 2nd", "Predice 1º y 2º" },
        { "Just to watch.", "Solo para mirar." },
        { "%u back if it comes in.", "%u de vuelta si acierta." },
        { "For free, or bet 1 coin for %u back.",
            "Gratis, o apuesta 1 moneda para %u de vuelta." },
        { "Nothing to bet with.", "No tienes con qué apostar." },
        { "Nothing to bet", "Nada para apostar" },
        { "Ten coins arrive on each new day you open the app.",
            "Llegan diez monedas cada nuevo día que abres la app." },
        { "Who comes first?", "¿Quién llega primero?" },
        { "And who comes second?", "¿Y quién segundo?" },
        { "That is your call", "Ese es tu pronóstico" },
        { "First and second, in order. Eleven for a coin if you call "
          "it, or watch for nothing.",
            "Primero y segundo, en orden. Once por una moneda si "
            "aciertas, o mira gratis." },
        { "%s to win. Now who is behind them?", "%s gana. ¿Y quién detrás?" },
        { "%s first, %s second.", "%s primero, %s segundo." },
        { "race", "competir" },
        { "Go", "¡Ya!" },
        { "You are in front", "Vas en cabeza" },
        { "%s is in front", "%s va en cabeza" },
        { "predict again", "predecir otra vez" },
        { "race again", "competir otra vez" },
        { "Called it", "Lo clavaste" },
        { "You won", "Has ganado" },
        { "%s won", "%s ha ganado" },
        { "Nobody", "Nadie" },
        { "You said %s then %s - they came %s and %s.",
            "Dijiste %s y luego %s - llegaron %s y %s." },
        { "The bet paid %u - %u coins to spend.",
            "La apuesta paga %u - te quedan %u monedas." },
        { "The bet cost you a coin. %u left.",
            "La apuesta te costó una moneda. Quedan %u." },
        { "Nothing bet, but right is right.", "Sin apostar, pero acertar es acertar." },
        { "Nothing bet, nothing lost.", "Sin apostar, nada perdido." },
        { "Predict again", "Predecir otra vez" },
        { "Race again", "Competir otra vez" },
        { "Bet %u coin - %u back", "Apostar %u moneda - %u de vuelta" },
        { "1st", "1º" },
        { "2nd", "2º" },
        { "3rd", "3º" },
        { "4th", "4º" },

        // ---------------------------------------------------- the dice duel
        { "One roll each", "Una tirada cada uno" },
        { "Highest roll takes it. A draw hands your %u back.",
            "Gana la tirada más alta. Un empate te devuelve tus %u." },
        { "Roll for free", "Tirar gratis" },
        { "%u coins to play", "%u monedas para jugar" },
        { "Ten arrive on each new day you open the app.",
            "Llegan diez cada nuevo día que abres la app." },
        { "%d all - nobody takes it", "Empate a %d - nadie gana" },
        { "%d beats %d", "%d gana a %d" },
        { "%d loses to %d", "%d pierde contra %d" },
        { "Your %u came back. %u to spend.", "Tus %u han vuelto. Quedan %u." },
        { "The bet cost you %u. %u left.", "La apuesta te costó %u. Quedan %u." },
        { "Nothing bet, and nothing decided.", "Sin apostar, y sin decidir nada." },
        { "Nothing bet, but a win is a win.", "Sin apostar, pero ganar es ganar." },
        { "%u in a row", "%u seguidas" },
        { "Roll again", "Tirar otra vez" },
        { "Bet %u coins - %u back", "Apostar %u monedas - %u de vuelta" },

        // ------------------------------------------------- the lantern wheel
        { "%u coins for a spin", "%u monedas por un giro" },
        { "Watch it for nothing, or put %u coins on it. Every lantern "
          "pays something and %d of the %d are a puzzle piece. You have "
          "%u.",
            "Mira gratis, o pon %u monedas. Cada farolillo paga algo y %d "
            "de los %d son una pieza de puzle. Tienes %u." },
        { "Spin for nothing", "Girar gratis" },
        { "A piece of %s", "Una pieza de %s" },
        { "The piece lantern", "El farolillo de la pieza" },
        { "The %u lantern", "El farolillo de %u" },
        { "Piece %d, and the panel will say the wheel brought it. %u coins left.",
            "Pieza %d, y el panel dirá que la trajo la rueda. Quedan %u monedas." },
        { "%u coins to spend. A spin costs %u.",
            "%u monedas para gastar. Un giro cuesta %u." },
        { "Nothing was on it - that one only pays when you have staked.",
            "No había nada apostado - ese solo paga si apuestas." },
        { "Nothing staked, so nothing won. It would have paid %u.",
            "Sin apostar, así que nada ganado. Habría pagado %u." },
        { "Spin again", "Girar otra vez" },
        { "Bet %u coins", "Apostar %u monedas" },

        // ---------------------------------------------------- the bandit
        { "A coin a spin", "Una moneda por giro" },
        { "A coin a spin, and %u to spend. X changes machines.",
            "Una moneda por giro, y %u para gastar. X cambia de máquina." },
        { "THREE SYMBOLS", "TRES SÍMBOLOS" },
        { "FIVE SYMBOLS", "CINCO SÍMBOLOS" },
        { "three symbols", "tres símbolos" },
        { "five symbols", "cinco símbolos" },
        { "Spin for free", "Girar gratis" },
        { "Bet %u coin", "Apostar %u moneda" },
        { "Two sevens", "Dos sietes" },
        { "Two bells", "Dos campanas" },
        { "Two the same", "Dos iguales" },
        { "Any two the same", "Dos iguales cualesquiera" },
        { "Nothing", "Nada" },
        { "Three %s", "Tres %s" },
        { "suns", "soles" },
        { "moons", "lunas" },
        { "bells", "campanas" },
        { "sevens", "sietes" },
        { "bars", "barras" },
        { "a line about every 3 spins", "una combinación cada 3 giros" },
        { "a line about every 4 spins", "una combinación cada 4 giros" },
        { "%u back, and %u to spend.", "%u de vuelta, y %u para gastar." },
        { "That coin is gone. %u left.", "Esa moneda se fue. Quedan %u." },
        { "Nothing staked, so nothing won - it would have paid %u.",
            "Sin apostar, así que nada ganado - habría pagado %u." },
        { "Nothing staked, and nothing to stake it on.",
            "Sin apostar, y sin nada que apostar." },

        // ---------------------------------------------------- the Mii tower
        { "Stack them up", "Apílalos" },
        { "A drops whoever is swinging. Miss the shoulders below and "
          "they fall; drift too far from the base and the lot goes "
          "over.",
            "A suelta a quien esté oscilando. Falla los hombros de abajo "
            "y se cae; aléjate demasiado de la base y todo se derrumba." },
        { "drop", "soltar" },
        { "lean", "inclinación" },
        { "%d floors", "%d pisos" },
        { "best %u floors", "récord %u pisos" },
        { "floors, best %u", "pisos, récord %u" },
        { "%s had nothing to stand on.", "%s no tenía dónde apoyarse." },
        { "It went over with %s on top.", "Se cayó con %s en la cima." },

        // ---------------------------------------------------- plaza dash
        { "Jump the market", "Salta el mercado" },
        { "A to jump, and hold it to jump higher. It gets quicker until "
          "you hit something.",
            "A para saltar, y mantenlo para saltar más alto. Se acelera "
            "hasta que choques con algo." },
        { "%u m", "%u m" },
        { "best %u m", "récord %u m" },
        { "Best is %u m.", "El récord es %u m." },
        { "A new best.", "Nuevo récord." },
        { "a new best", "nuevo récord" },

        // ------------------------------------------- shared by the games
        { "You", "Tú" },
        { "A stranger", "Un desconocido" },

        // ---------------------------------------------------- the trophies
        { "show %s", "mostrar %s" },
        { "earned only", "solo conseguidos" },
        { "still to earn", "por conseguir" },
        { "all of them", "todos" },
        { "bronze", "bronce" },
        { "silver", "plata" },
        { "gold", "oro" },
        { "platinum", "platino" },
        { "%d of %zu", "%d de %zu" },
        { "earned", "conseguido" },
        { "earned %s", "conseguido %s" },
        { "Nothing earned yet. Go and meet somebody.",
            "Nada conseguido aún. Ve a conocer a alguien." },
        { "Everything here is earned.", "Aquí todo está conseguido." },
        { "A %s trophy.", "Un trofeo de %s." },
        { "%d trophies earned", "%d trofeos conseguidos" },
        { "Your record is in the trophies tab.",
            "Tu historial está en la pestaña de trofeos." },

        { "Somebody's out there", "Hay alguien ahí fuera" },
        { "Cross one other console.", "Crúzate con otra consola." },
        { "Properly introduced", "Presentaciones hechas" },
        { "Give your pass a name, a greeting and something to carry.",
            "Dale a tu tarjeta un nombre, un saludo y algo que llevar." },
        { "Fully laden", "Cargado por completo" },
        { "Carry four things on your pass at once.",
            "Lleva cuatro cosas a la vez en tu tarjeta." },
        { "A corner of something", "Una esquina de algo" },
        { "Take your first puzzle piece off a crossing.",
            "Consigue tu primera pieza de puzle en un cruce." },
        { "Worth keeping", "Vale la pena guardarla" },
        { "Star a card.", "Destaca una tarjeta." },
        { "Ten faces", "Diez caras" },
        { "Cross ten different consoles.", "Crúzate con diez consolas distintas." },
        { "A week of it", "Una semana" },
        { "Open the app on seven different days.",
            "Abre la app en siete días distintos." },
        { "Two down", "Dos hechos" },
        { "Finish two puzzles.", "Termina dos puzles." },
        { "First purchase", "Primera compra" },
        { "Buy something in the shop.", "Compra algo en la tienda." },
        { "Beginner's luck", "Suerte de principiante" },
        { "Win a bet in the games tab.", "Gana una apuesta en la pestaña de juegos." },
        { "First blood", "Primera sangre" },
        { "Win a duel at the dice.", "Gana un duelo de dados." },
        { "Six all", "Seis y seis" },
        { "Roll a six against a six.", "Saca un seis contra un seis." },
        { "Lined up", "Alineados" },
        { "Line up three of a kind at the bandit.",
            "Alinea tres iguales en el bandido." },
        { "The wheel's own", "Regalo de la rueda" },
        { "Win a puzzle piece on the lantern wheel.",
            "Gana una pieza de puzle en la rueda de farolillos." },
        { "Ten storeys", "Diez pisos" },
        { "Stack ten floors in the Mii tower.",
            "Apila diez pisos en la torre de Miis." },
        { "Dead centre", "En pleno centro" },
        { "Land a floor within six pixels of the one below.",
            "Coloca un piso a menos de seis píxeles del de abajo." },
        { "Off the mark", "Ya en marcha" },
        { "Run a hundred metres in the plaza dash.",
            "Corre cien metros en Plaza Dash." },
        { "Your own face", "Tu propia cara" },
        { "Make a face of your own in the Mii maker.",
            "Crea una cara propia en el editor de Miis." },
        { "Redecorated", "Redecorada" },
        { "Give your card a look of your own.",
            "Dale a tu tarjeta un aspecto propio." },
        { "Out in the world", "Por el mundo" },
        { "Have your pass reach somebody.", "Haz que tu tarjeta llegue a alguien." },
        { "Matching outfits", "Vestidos igual" },
        { "Cross somebody whose card wears the same look as yours.",
            "Crúzate con alguien cuya tarjeta lleve tu mismo aspecto." },
        { "Same taste", "Mismo gusto" },
        { "Cross somebody carrying something you carry too.",
            "Crúzate con alguien que lleve algo que tú también llevas." },
        { "The strong silent type", "El tipo callado" },
        { "Cross a pass with nothing written on it.",
            "Crúzate con una tarjeta sin nada escrito." },
        { "A busy afternoon", "Una tarde movida" },
        { "Cross ten consoles in one day.", "Crúzate con diez consolas en un día." },
        { "Fifty faces", "Cincuenta caras" },
        { "Cross fifty different consoles.",
            "Crúzate con cincuenta consolas distintas." },
        { "A hundred faces", "Cien caras" },
        { "Cross a hundred different consoles.",
            "Crúzate con cien consolas distintas." },
        { "A hundred hellos", "Cien holas" },
        { "Cross people a hundred times, the same ones included.",
            "Crúzate cien veces con gente, repetidos incluidos." },
        { "A regular", "Un habitual" },
        { "Cross the same console ten times.",
            "Crúzate diez veces con la misma consola." },
        { "Around town", "Por el barrio" },
        { "Cross people in five different places.",
            "Crúzate con gente en cinco lugares distintos." },
        { "Ten places", "Diez lugares" },
        { "Cross people in ten different places.",
            "Crúzate con gente en diez lugares distintos." },
        { "The late train", "El último tren" },
        { "Cross somebody between midnight and four.",
            "Crúzate con alguien entre medianoche y las cuatro." },
        { "Every day of the week", "Todos los días de la semana" },
        { "Cross somebody on each of the seven weekdays.",
            "Crúzate con alguien en cada uno de los siete días." },
        { "A fortnight", "Dos semanas" },
        { "Open the app on fourteen different days.",
            "Abre la app en catorce días distintos." },
        { "An old friend", "Un viejo conocido" },
        { "Keep a card for six months.", "Guarda una tarjeta seis meses." },
        { "A picture at last", "Una imagen, por fin" },
        { "Finish a puzzle.", "Termina un puzle." },
        { "Halfway through", "A medio camino" },
        { "Hold half of every piece there is.",
            "Ten la mitad de todas las piezas que existen." },
        { "A picture by committee", "Una imagen entre muchos" },
        { "Take pieces from ten different people.",
            "Consigue piezas de diez personas distintas." },
        { "A shortlist", "Una selección" },
        { "Star twenty-five cards.", "Destaca veinticinco tarjetas." },
        { "Nothing left unread", "Nada sin leer" },
        { "Open every card you hold, with fifty of them.",
            "Abre todas las tarjetas que tienes, con cincuenta de ellas." },
        { "Reciprocated", "Correspondido" },
        { "Send something back to twenty-five people.",
            "Devuelve algo a veinticinco personas." },
        { "Namesake", "Tocayo" },
        { "Cross somebody who chose the same name as you.",
            "Crúzate con alguien que eligió tu mismo nombre." },
        { "Somebody with a life", "Alguien con vida propia" },
        { "Cross a pass carrying a thousand hours in one title.",
            "Crúzate con una tarjeta con mil horas en un solo juego." },
        { "The shop's best customer", "El mejor cliente de la tienda" },
        { "Spend five hundred coins.", "Gasta quinientas monedas." },
        { "Saving up", "Ahorrando" },
        { "Have five hundred coins at once.", "Ten quinientas monedas a la vez." },
        { "On a run", "En racha" },
        { "Win five duels at the dice in a row.",
            "Gana cinco duelos de dados seguidos." },
        { "A good day at the tables", "Un buen día en las mesas" },
        { "Win fifty coins betting in the games tab.",
            "Gana cincuenta monedas apostando en la pestaña de juegos." },
        { "Sevens", "Tres sietes" },
        { "Line up three sevens at the bandit.", "Alinea tres sietes en el bandido." },
        { "Twice lucky", "Suerte por dos" },
        { "Win two puzzle pieces on the lantern wheel.",
            "Gana dos piezas de puzle en la rueda de farolillos." },
        { "Twenty up", "Veinte pisos" },
        { "Stack twenty floors in the Mii tower.",
            "Apila veinte pisos en la torre de Miis." },
        { "Steady hands", "Pulso firme" },
        { "Land five floors in a row dead centre.",
            "Coloca cinco pisos seguidos en pleno centro." },
        { "Talked it down", "Recuperada a tiempo" },
        { "Lean a tower to the edge of going over, and bring it back.",
            "Inclina una torre al borde de caer y recupérala." },
        { "A good run", "Una buena carrera" },
        { "Run five hundred metres in the plaza dash.",
            "Corre quinientos metros en Plaza Dash." },
        { "Five hundred faces", "Quinientas caras" },
        { "Cross five hundred different consoles.",
            "Crúzate con quinientas consolas distintas." },
        { "A thousand faces", "Mil caras" },
        { "Cross a thousand different consoles.",
            "Crúzate con mil consolas distintas." },
        { "A thousand hellos", "Mil holas" },
        { "Cross people a thousand times, the same ones included.",
            "Crúzate mil veces con gente, repetidos incluidos." },
        { "Practically neighbours", "Casi vecinos" },
        { "Cross the same console fifty times.",
            "Crúzate cincuenta veces con la misma consola." },
        { "Far travelled", "Gran viajero" },
        { "Cross people in twenty-five different places.",
            "Crúzate con gente en veinticinco lugares distintos." },
        { "Fifty places", "Cincuenta lugares" },
        { "Cross people in fifty different places.",
            "Crúzate con gente en cincuenta lugares distintos." },
        { "A month of it", "Un mes" },
        { "Open the app on thirty different days.",
            "Abre la app en treinta días distintos." },
        { "A hundred days", "Cien días" },
        { "Open the app on a hundred different days.",
            "Abre la app en cien días distintos." },
        { "A year of it", "Un año" },
        { "Open the app on three hundred and sixty-five different days.",
            "Abre la app en trescientos sesenta y cinco días distintos." },
        { "Known you for a year", "Un año de conocerse" },
        { "Keep a card for a year.", "Guarda una tarjeta un año." },
        { "Every picture", "Todas las imágenes" },
        { "Finish every puzzle.", "Termina todos los puzles." },
        { "By hand alone", "Sin comprar nada" },
        { "Finish a puzzle without buying a single piece.",
            "Termina un puzle sin comprar ni una pieza." },
        { "The full set", "La colección completa" },
        { "Line up three of a kind of every symbol the bandit has.",
            "Alinea tres iguales de cada símbolo del bandido." },
        { "Five from the wheel", "Cinco de la rueda" },
        { "Win five puzzle pieces on the lantern wheel.",
            "Gana cinco piezas de puzle en la rueda de farolillos." },
        { "Thirty storeys", "Treinta pisos" },
        { "Stack thirty floors in the Mii tower.",
            "Apila treinta pisos en la torre de Miis." },
        { "A kilometre of plaza", "Un kilómetro de plaza" },
        { "Run a thousand metres in the plaza dash.",
            "Corre mil metros en Plaza Dash." },
        { "Seven in a row", "Siete seguidos" },
        { "Win seven duels at the dice in a row.",
            "Gana siete duelos de dados seguidos." },
        { "The bookmaker's problem", "El problema del corredor de apuestas" },
        { "Win two hundred coins betting in the games tab.",
            "Gana doscientas monedas apostando en la pestaña de juegos." },
        { "Fifty contributors", "Cincuenta contribuyentes" },
        { "Take pieces from fifty different people.",
            "Consigue piezas de cincuenta personas distintas." },
        { "The whole plaza", "El plaza entero" },
        { "Earn everything else.", "Consigue todo lo demás." },

        // ------------------------------------------- settings, the rest of it
        { "following the console, currently %s", "sigue a la consola, ahora %s" },
        { "light", "claro" },
        { "dark", "oscuro" },
        { "light by default", "claro por defecto" },
        { "http://host:port of your own server",
            "http://host:puerto de tu propio servidor" },
        { "where this build trades passes", "dónde esta versión intercambia tarjetas" },
        { "no Wi-Fi name to match on - wired, or not connected",
            "sin nombre de Wi-Fi que comparar - por cable o sin conexión" },
        { "consoles on \"%s\" share this", "las consolas en \"%s\" comparten esto" },
        { "Nobody is blocked here. A asks the plaza to drop any it "
          "still has",
            "Aquí no hay nadie bloqueado. A pide al plaza que suelte los "
            "que aún guarde" },
        { "Nobody is blocked here. Needs the plaza, and this console is "
          "offline",
            "Aquí no hay nadie bloqueado. Necesita el plaza, y esta "
            "consola está sin conexión" },
        { " - blocked %s", " - bloqueado %s" },
        { ". A lets them cross you again", ". A les deja volver a cruzarse contigo" },
        { ". Offline - unblocking needs the plaza",
            ". Sin conexión - desbloquear necesita el plaza" },
        { "Clears all %zu at once, on this console and on the plaza",
            "Desbloquea las %zu de golpe, en esta consola y en el plaza" },
        { "Offline - clearing the list needs the plaza, or the two "
          "would disagree",
            "Sin conexión - vaciar la lista necesita el plaza, o los dos "
            "discreparían" },
        { "Off. Turn it on before reporting a problem, then off again",
            "Desactivado. Actívalo antes de informar de un problema y luego apágalo" },
        { "plaza.log, beside your pass on the SD card - it names this "
          "console and the server",
            "plaza.log, junto a tu tarjeta en la tarjeta SD - nombra esta "
            "consola y el servidor" },

        // -------------------------------------- the rest of the hint strip
        //
        // The verbs, from screens whose own words are still English: the strip
        // along the bottom is chrome, like the tabs, and reads as one thing
        // wherever you are rather than changing language with the screen.
        { "buy", "comprar" },
        { "star", "destacar" },
        { "unstar", "quitar destaque" },
        { "delete", "borrar" },
        { "save", "guardar" },
        { "load this face", "cargar esta cara" },
        { "look at it", "verla" },
        { "look at them", "verlos" },
        { "carry it", "llevarlo" },
        { "put it back", "devolverlo" },
        { "trade back", "devolver algo" },
        { "toggle", "alternar" },
        { "block - offline", "bloquear - sin conexión" },
        { "make my pass", "crear mi tarjeta" },
        { "not now", "ahora no" },
        { "your details", "tus datos" },
        { "your mii", "tu Mii" },

        // ------------------------------------------------------ how long ago
        //
        // The one place a French sentence will not take the English shape:
        // "3 days ago" puts the number in the middle, "il y a 3 jours" puts it
        // at the end, which is why relativeTime() hands the whole line to
        // format() rather than gluing a number to a word.
        { "unknown", "desconocido" },
        { "just now", "ahora mismo" },
        { "%llum ago", "hace %llu min" },
        { "%lluh ago", "hace %llu h" },
        { "Yesterday", "Ayer" },
        { "%d days ago", "hace %d días" },
        { "%d %s", "%d %s" },
        { "Jan", "ene" },
        { "Feb", "feb" },
        { "Mar", "mar" },
        { "Apr", "abr" },
        { "May", "may" },
        { "Jun", "jun" },
        { "Jul", "jul" },
        { "Aug", "ago" },
        { "Sep", "sep" },
        { "Oct", "oct" },
        { "Nov", "nov" },
        { "Dec", "dic" },
        { "Sun", "dom" },
        { "Mon", "lun" },
        { "Tue", "mar" },
        { "Wed", "mié" },
        { "Thu", "jue" },
        { "Fri", "vie" },
        { "Sat", "sáb" },

        // ------------------------------------------------------- the plaza
        { "the plaza - today", "el plaza - hoy" },
        { "Nobody has crossed you yet", "Nadie se ha cruzado contigo aún" },
        { "1 person crossed your path", "1 persona se cruzó contigo" },
        { "%u people crossed your path", "%u personas se cruzaron contigo" },
        { "1 pass waiting for you", "1 tarjeta te espera" },
        { "%u passes waiting for you", "%u tarjetas te esperan" },
        { "Nothing new today", "Nada nuevo hoy" },
        { "Take the console outside, or join a busier network. Passes "
          "arrive on their own.",
            "Saca la consola a la calle, o únete a una red con más gente. "
            "Las tarjetas llegan solas." },
        { "Somewhere out there.", "En algún lugar por ahí." },
        { ", ", ", " },
        { ", and ", " y " },
        { "Unopened passes", "Tarjetas sin abrir" },
        { "nothing yet", "nada aún" },
        { "all caught up", "todo al día" },
        { "%u waiting", "%u esperando" },
        { " - oldest %s", " - la más antigua %s" },
        { " - %u crossings, %u place", " - %u cruces, %u lugar" },
        { " - %u crossings, %u places", " - %u cruces, %u lugares" },
        { "new", "nuevo" },
        { "hidden title", "juego oculto" },
        { "%s - %s", "%s - %s" },
        { "%d more", "%d más" },
        { "The plaza is empty", "El plaza está vacío" },
        { "Your console trades a pass with anyone whose Switch is on "
          "the same network, or nearby on the internet. Leave it "
          "running and come back.",
            "Tu consola intercambia una tarjeta con cualquiera cuya "
            "Switch esté en la misma red, o cerca en internet. Déjala "
            "encendida y vuelve luego." },
        { "Looking for passes", "Buscando tarjetas" },
        { "Asking the plaza who else has been around.",
            "Preguntando al plaza quién más ha pasado." },

        // ------------------------------------------------------ the collection
        { "Starred %s", "%s destacado" },
        { "Unstarred %s", "%s sin destacar" },
        { "Kept when the collection fills up.",
            "Se conserva cuando la colección se llena." },
        { "No longer kept when the collection fills up.",
            "Ya no se conserva cuando la colección se llena." },
        { "%u %s met", "%u %s conocidas" },
        { "person", "persona" },
        { "people", "personas" },
        { "%s - %u crossings in total", "%s - %u cruces en total" },
        { "by name", "por nombre" },
        { "starred first", "destacados primero" },
        { "most recent first", "más recientes primero" },
        { "sort by name", "ordenar por nombre" },
        { "sort by starred", "ordenar por destacados" },
        { "sort by recent", "ordenar por recientes" },
        { "Nothing collected yet. The first pass you receive lands here "
          "and stays.",
            "Nada recogido aún. La primera tarjeta que recibas aterriza "
            "aquí y se queda." },
        { "met %u times", "%u veces" },

        // ------------------------------------------------------- the Square
        { "Everyone you cross paths with turns up here.",
            "Todos los que se cruzan contigo aparecen aquí." },
        { "A few of the people you have met, milling about.",
            "Algunas de las personas que has conocido, dando vueltas." },

        // --------------------------------------------------------- nearby
        { "live - scanning", "en directo - buscando" },
        { "live - trading", "en directo - intercambiando" },
        { "offline", "sin conexión" },
        { "cannot reach the plaza", "no se puede acceder al plaza" },
        { "1 console awake near you", "1 consola activa cerca de ti" },
        { "%d consoles awake near you", "%d consolas activas cerca de ti" },
        { "Passes exchange on their own. You do not have to sit here.",
            "Las tarjetas se intercambian solas. No tienes que quedarte aquí." },
        { "Nobody else has checked in here yet. Leave the app open; the "
          "plaza fills faster if you do.",
            "Nadie más se ha conectado aquí todavía. Deja la app abierta; "
            "el plaza se llena más rápido así." },
        { "waiting", "esperando" },
        { "exchanging...", "intercambiando..." },
        { "passed", "cruzado" },
        { "out of range", "fuera de alcance" },
        { "same network", "misma red" },
        { "nearby network", "red cercana" },
        { "somewhere else", "en otro lugar" },
        { "Up to %d per day while the app is open",
            "Hasta %d al día mientras la app está abierta" },
        { " - matching on \"%s\"", " - comparando con \"%s\"" },
        { " - on \"%s\", no name to match", " - en \"%s\", sin nombre que comparar" },

        // ----------------------------------------------------- a peer nearby
        { "awake near you", "activa cerca de ti" },
        { "Someone", "Alguien" },
        { "How close", "Distancia" },
        { "Playing", "Jugando a" },
        { "Right now", "Ahora mismo" },
        { "Trading passes", "Intercambiando tarjetas" },
        { "You have already crossed", "Ya os habéis cruzado" },
        { "Drifted out of range", "Se ha salido de alcance" },
        { "Waiting for the next round", "Esperando la siguiente ronda" },
        { "Passes trade on their own with everyone in range. There is "
          "nothing to press here, and nothing to wait for.",
            "Las tarjetas se intercambian solas con todos los que estén a "
            "alcance. Aquí no hay nada que pulsar ni nada que esperar." },

        // -------------------------------------------------------- the puzzles
        { "Nothing to collect yet", "Nada que coleccionar aún" },
        { "Every puzzle is finished", "Todos los puzles están terminados" },
        { "%d of %zu finished", "%d de %zu terminados" },
        { "Every console you cross brings one piece. Pick which puzzle they go into.",
            "Cada consola que cruzas trae una pieza. Elige a qué puzle van." },
        { "filling", "en curso" },
        { "finished", "terminado" },
        { "%d of %u pieces", "%d de %u piezas" },
        { "already finished", "ya terminado" },
        { "already filling", "ya en curso" },
        { "fill this one next", "llenar este a continuación" },
        { "%s is finished", "%s está terminado" },
        { "Pieces go into the first puzzle that is not.",
            "Las piezas van al primero que no lo esté." },
        { "Already filling %s", "Ya se está llenando %s" },
        { "Every crossing brings a piece of this one.",
            "Cada cruce trae una pieza de este." },
        { "Filling %s", "Llenando %s" },
        { "Crossings go into this one until you pick another.",
            "Los cruces van a este hasta que elijas otro." },
        { "One person brought this", "Una sola persona trajo esto" },
        { "%d people brought this", "%d personas trajeron esto" },
        { " - finished %s", " - terminado %s" },
        { "Piece %d", "Pieza %d" },
        { "Brought by", "Traída por" },
        { "Not found yet", "Aún no encontrada" },
        { "someone", "alguien" },
        { "Cross someone while this puzzle is the one being filled.",
            "Crúzate con alguien mientras este puzle es el que se llena." },
        { "Collected before the app started keeping track.",
            "Recogida antes de que la app llevara la cuenta." },

        // ---------------------------------------------------------- the shop
        { "%u earned - %u spent", "%u ganadas - %u gastadas" },
        { "A piece you do not have yet of %s - the puzzle your "
          "crossings are filling, %d of %u so far. Twice the price, "
          "because you get to say which picture it goes into.",
            "Una pieza de %s que aún no tienes - el puzle que llenan tus "
            "cruces, %d de %u hasta ahora. El doble de precio, porque "
            "eliges a qué imagen va." },
        { "%s is finished. Choose another to fill on the puzzles "
          "screen, or take your chances with any puzzle.",
            "%s está terminado. Elige otro que llenar en la pantalla de "
            "puzles, o prueba suerte con cualquiera." },
        { "A piece of any puzzle", "Una pieza de cualquier puzle" },
        { "Half the price, and you do not choose: one piece drawn from "
          "every unfinished puzzle at once - %d still to find across %d "
          "of them.",
            "Mitad de precio, y no eliges: una pieza sacada de todos los "
            "puzles sin terminar a la vez - faltan %d en %d de ellos." },
        { "Every puzzle is finished. There is nothing left to sell you.",
            "Todos los puzles están terminados. No queda nada que venderte." },
        { "Nothing on the shelf yet.", "Nada en el estante todavía." },
        { "%u more coins needed. Ten arrive on every new day you open the app.",
            "Faltan %u monedas. Llegan diez cada nuevo día que abres la app." },
        { "sold out", "agotado" },
        { "%u coins short", "Faltan %u monedas" },
        { "Nothing to sell there", "Nada que vender ahí" },
        { "There are no pieces left to find there.",
            "Ahí ya no quedan piezas por encontrar." },
        { "Piece %d of %s", "Pieza %d de %s" },
        { "%u coins left.", "Quedan %u monedas." },
        { "Buy %s for %u coins?", "¿Comprar %s por %u monedas?" },
        { "%s That leaves you %u.", "%s Te quedarán %u." },
        { "One you do not hold yet, into the puzzle you are filling.",
            "Una que aún no tengas, para el puzle que estás llenando." },
        { "Drawn from every unfinished puzzle at once, so it may not be "
          "the one you are filling.",
            "Sacada de todos los puzles sin terminar a la vez, así que "
            "puede no ser el que estás llenando." },
        { "Buy it", "Comprar" },

        // -------------------------------------------------------- your pass
        { "your pass", "tu tarjeta" },
        { "This is what they see", "Esto es lo que ven" },
        { "%s theme", "tema %s" },
        { "(no greeting yet)", "(sin saludo aún)" },
        { "Name", "Nombre" },
        { "not set yet", "sin definir" },
        { "Greeting", "Saludo" },
        { "%zu of 60 characters", "%zu de 60 caracteres" },
        { "Card theme", "Tema de la tarjeta" },
        { "%s - 6 unlocked", "%s - 6 desbloqueados" },
        { "What you carry", "Lo que llevas" },
        { "Title on your pass", "Juego en tu tarjeta" },
        { "hidden by privacy settings", "oculto por los ajustes de privacidad" },
        { "reading the play history...", "leyendo el historial de juego..." },
        { "nothing played on this console yet",
            "aún no se ha jugado nada en esta consola" },
        { "hidden", "oculto" },
        { "%s - %uh", "%s - %u h" },
        { "edit", "editar" },
        { "edit your mii", "editar tu Mii" },
        { "next theme", "siguiente tema" },
        { "next title", "siguiente juego" },
        { "The name on your pass", "El nombre de tu tarjeta" },
        { "Up to 60 characters", "Hasta 60 caracteres" },
        { "Your pass never carries your account name, your friend code, "
          "or a precise position - only what you typed and, if you "
          "allow it, the place you named.",
            "Tu tarjeta nunca lleva el nombre de tu cuenta, tu código de "
            "amigo ni una posición precisa - solo lo que escribiste y, si "
            "lo permites, el lugar que nombraste." },

        // ------------------------------------------------------ what you carry
        { "on your pass", "en tu tarjeta" },
        { "%zu of %d", "%zu de %d" },
        { "Four is the limit", "Cuatro es el límite" },
        { "Put something back before picking this up.",
            "Devuelve algo antes de coger esto." },

        // -------------------------------------------------------- a crossing
        { "crossed paths - %s", "os cruzasteis - %s" },
        { "playing %s", "jugando a %s" },
        { "somewhere on the network", "en algún lugar de la red" },
        { "carrying", "lleva" },
        { "time crossed", "vez cruzada" },
        { "times crossed", "veces cruzadas" },
        { "game installed", "juego instalado" },
        { "games installed", "juegos instalados" },
        { "hours played", "horas jugadas" },
        { "in %s", "en %s" },
        { "Already traded back", "Ya devuelto" },
        { "Trade something back", "Devolver algo" },
        { "Take it, send something back", "Cógelo y devuelve algo" },
        { "Star this card", "Destacar esta tarjeta" },
        { "Unstar this card", "Quitar el destaque" },
        { "Sent something back to %s", "Se ha devuelto algo a %s" },
        { "It travels with your pass the next time you cross.",
            "Viajará con tu tarjeta en el próximo cruce." },
        { "Blocking has to reach the server, or they would keep "
          "receiving your pass. Try again when the dot by the tabs is "
          "green.",
            "Bloquear tiene que llegar al servidor, o seguirían "
            "recibiendo tu tarjeta. Inténtalo cuando el punto junto a las "
            "pestañas esté verde." },
        { "Block %s?", "¿Bloquear a %s?" },
        { "Their pass is deleted and this console can never cross you "
          "again. They are not told.",
            "Su tarjeta se borra y esa consola no podrá volver a cruzarse "
            "contigo. No se les avisa." },
        { "Block and forget", "Bloquear y olvidar" },

        // ------------------------------------------------------- your Mii
        { "your face", "tu cara" },
        { "Make your Mii", "Crea tu Mii" },
        { "how others see you", "cómo te ven los demás" },
        { "yes", "sí" },
        { "no", "no" },
        { "%d of %d", "%d de %d" },
        { "Face shape", "Forma de la cara" },
        { "Skin tone", "Tono de piel" },
        { "Hair", "Pelo" },
        { "Hair colour", "Color de pelo" },
        { "Hair flipped", "Pelo invertido" },
        { "Eyes", "Ojos" },
        { "Eye colour", "Color de ojos" },
        { "Eyebrows", "Cejas" },
        { "Eyebrow colour", "Color de cejas" },
        { "Nose", "Nariz" },
        { "Mouth", "Boca" },
        { "Lip colour", "Color de labios" },
        { "Glasses", "Gafas" },
        { "Glasses colour", "Color de gafas" },
        { "Moustache", "Bigote" },
        { "Beard", "Barba" },
        { "Facial hair colour", "Color del vello facial" },
        { "Wrinkles", "Arrugas" },
        { "Makeup", "Maquillaje" },
        { "Mole", "Lunar" },
        { "Headwear", "Sombrero" },
        { "Build", "Corpulencia" },
        { "Height", "Altura" },
        { "Favourite colour", "Color favorito" },
        { "Eye spacing", "Separación de ojos" },
        { "Eye height", "Altura de ojos" },
        { "Eye width", "Anchura de ojos" },
        { "Eye height scale", "Estiramiento de ojos" },
        { "Eye tilt", "Inclinación de ojos" },
        { "Eyebrow spacing", "Separación de cejas" },
        { "Eyebrow height", "Altura de cejas" },
        { "Eyebrow width", "Anchura de cejas" },
        { "Eyebrow thickness", "Grosor de cejas" },
        { "Eyebrow tilt", "Inclinación de cejas" },
        { "Nose height", "Altura de la nariz" },
        { "Nose size", "Tamaño de la nariz" },
        { "Mouth height", "Altura de la boca" },
        { "Mouth width", "Anchura de la boca" },
        { "Mouth thickness", "Grosor de la boca" },
        { "Moustache height", "Altura del bigote" },
        { "Moustache size", "Tamaño del bigote" },
        { "Beard height", "Altura de la barba" },
        { "Beard size", "Tamaño de la barba" },
        { "Glasses height", "Altura de las gafas" },
        { "Glasses size", "Tamaño de las gafas" },
        { "Mole across", "Lunar horizontal" },
        { "Mole down", "Lunar vertical" },
        { "Mole size", "Tamaño del lunar" },

        // -------------------------------------------------- faces on the card
        { "faces on the sd card", "caras en la tarjeta sd" },
        { "Save and load", "Guardar y cargar" },
        { "Save this face...", "Guardar esta cara..." },
        { "Name this face", "Ponle nombre a esta cara" },
        { "Needs a name", "Necesita un nombre" },
        { "That name has nothing in it a file can be called.",
            "Ese nombre no tiene nada con lo que llamar a un archivo." },
        { "Saved", "Guardado" },
        { "%s is in the export folder.", "%s está en la carpeta de exportación." },
        { "Not saved", "No guardado" },
        { "Replace %s?", "¿Reemplazar %s?" },
        { "There is already a face saved under that name. Replacing it "
          "cannot be undone.",
            "Ya hay una cara guardada con ese nombre. Reemplazarla no se "
            "puede deshacer." },
        { "Replace", "Reemplazar" },
        { "Delete %s?", "¿Borrar %s?" },
        { "It is removed from the SD card for good. Anyone you sent it "
          "to still has their copy.",
            "Se elimina de la tarjeta SD para siempre. Quien la recibió "
            "sigue teniendo su copia." },
        { "Delete", "Borrar" },
        { "Deleted", "Borrado" },
        { "%s is gone from the export folder.",
            "%s ha desaparecido de la carpeta de exportación." },
        { "Not deleted", "No borrado" },
        { "Cannot load that one", "No se puede cargar esa" },
        { "Not a face this version can read",
            "No es una cara que esta versión pueda leer" },
        { "Nothing saved yet. Faces you save show up here, and so does "
          "anything you drop into the folder yourself.",
            "Nada guardado aún. Las caras que guardes aparecen aquí, y "
            "también lo que dejes tú en la carpeta." },

        // --------------------------------------------------------- first run
        { "Leave it open.", "Déjala abierta." },
        { "While this is open, your console swaps a small pass with the "
          "others that are open too - a face, a greeting, whatever you "
          "chose to carry. Who you meet is whoever is awake within the "
          "reach you set.",
            "Mientras esto esté abierto, tu consola intercambia una "
            "pequeña tarjeta con las demás que también lo estén - una "
            "cara, un saludo, lo que elegiste llevar. Te cruzas con quien "
            "esté activo dentro del alcance que fijes." },
        { "Make your pass - a face, a greeting, one thing to trade",
            "Crea tu tarjeta - una cara, un saludo, algo que intercambiar" },
        { "Leave it open; it checks in on its own", "Déjala abierta; se conecta sola" },
        { "Open the plaza and see who you crossed",
            "Abre el plaza y mira con quién te cruzaste" },
        { "A greeting, up to 60 characters", "Un saludo, hasta 60 caracteres" },
        { "pair this console", "emparejar esta consola" },
        { "A picture of this console's id. It lives on the SD card, is "
          "tied to nothing about the hardware, and you can throw it "
          "away.",
            "Una imagen del id de esta consola. Vive en la tarjeta SD, no "
            "está atada a nada del hardware y puedes tirarla." },

        // ------------------------------------------- updates, and the app itself
        { "Version %s is out", "La versión %s ya está" },
        { "Settings -> About -> Check for updates to install it.",
            "Ajustes -> Acerca de -> Buscar actualizaciones para instalarla." },
        { "Puzzle art downloaded", "Imágenes descargadas" },
        { "Restart the app to see the pictures.",
            "Reinicia la app para ver las imágenes." },
        { "Update installed", "Actualización instalada" },
        { "Restart from Settings -> \"About\" to run version %s.",
            "Reinicia desde Ajustes -> \"Acerca de\" para usar la versión %s." },
        { "Up to date", "Al día" },
        { "%s is the latest release.", "%s es la última versión." },
        { "Could not download puzzle art", "No se pudieron descargar las imágenes" },
        { "Could not check for updates", "No se pudieron buscar actualizaciones" },
        { "Install version %s?", "¿Instalar la versión %s?" },
        { "The new version is downloaded, checked, and only then "
          "written over this one. The copy you are running now is kept "
          "until the new one has been verified.",
            "La nueva versión se descarga, se comprueba y solo entonces "
            "se escribe sobre esta. La copia que usas ahora se conserva "
            "hasta verificar la nueva." },
        { "Install", "Instalar" },
        { "Restart into version %s?", "¿Reiniciar en la versión %s?" },
        { "The app closes and opens again on the new version. Your "
          "passes and your collection are untouched.",
            "La app se cierra y se vuelve a abrir en la nueva versión. "
            "Tus tarjetas y tu colección quedan intactas." },
        { "Restart", "Reiniciar" },
        { "%s passed you", "%s se cruzó contigo" },
        { "%s and %zu others passed you", "%s y %zu más se cruzaron contigo" },
        { "%zu new passes", "%zu tarjetas nuevas" },
        { "a piece of %s", "una pieza de %s" },
        { "%d pieces of %s", "%d piezas de %s" },
        { "one of them is carrying %s", "uno de ellos lleva %s" },
        { "Open the plaza to see who.", "Abre el plaza para ver quién." },
        { "Keep everything", "Conservar todo" },

        // ------------------------------------------- settings, the dialogs
        { "Where are you? A district, a station, a shop",
            "¿Dónde estás? Un barrio, una estación, una tienda" },
        { "Which city", "Qué ciudad" },
        { "Plaza server address", "Dirección del servidor del plaza" },
        { "Clear any block the plaza still has?",
            "¿Borrar los bloqueos que el plaza aún tenga?" },
        { "Clear all %zu?", "¿Desbloquear las %zu?" },
        { "This console has none listed, but the plaza keeps its own "
          "copy and a restored backup can leave the two disagreeing. "
          "Nothing happens if it has none either.",
            "Esta consola no tiene ninguna listada, pero el plaza guarda "
            "su propia copia y un respaldo restaurado puede dejarlos en "
            "desacuerdo. Si él tampoco tiene, no pasa nada." },
        { "Every console you have blocked can cross you again, except "
          "any that blocked you as well. Their old passes are not "
          "coming back; only the block is lifted.",
            "Todas las consolas que has bloqueado podrán volver a "
            "cruzarse contigo, salvo las que también te bloquearon. Sus "
            "tarjetas antiguas no vuelven; solo se levanta el bloqueo." },
        { "Clear them", "Desbloquear todos" },
        { "Block list cleared", "Lista de bloqueos vaciada" },
        { "This console has none left, and the plaza has been asked to "
          "drop the blocks it was holding for you.",
            "Esta consola ya no tiene ninguna, y se ha pedido al plaza "
            "que suelte los bloqueos que guardaba por ti." },
        { "Delete every pass?", "¿Borrar todas las tarjetas?" },
        { "Every pass you have collected is removed from this console. "
          "Your own pass and your identity stay.",
            "Todas las tarjetas que has recogido se eliminan de esta "
            "consola. Tu propia tarjeta y tu identidad se quedan." },
        { "Delete them all", "Borrar todas" },
        { "Collection cleared", "Colección vaciada" },
        { "The plaza is empty again.", "El plaza está vacío otra vez." },
        { "Start over as someone new?", "¿Empezar de cero como otra persona?" },
        { "This console gets a brand new id. Passes you already handed "
          "out can no longer be linked to you, and your collection is "
          "deleted.",
            "Esta consola recibe un id totalmente nuevo. Las tarjetas ya "
            "repartidas no podrán vincularse a ti, y tu colección se "
            "borra." },
        { "Start over", "Empezar de cero" },
        { "You are someone new", "Eres otra persona" },
        { "Your code is now %s", "Tu código ahora es %s" },

        // ------------------------------------------- what the plaza is doing
        //
        // These come off the sync and update threads, and are read back on
        // screen in Settings and in Nearby. Whole sentences are translated;
        // the protocol diagnostics they sometimes carry - an HTTP status, a
        // libnx result code - stay as they are, because they exist to be
        // pasted into a bug report.
        { "Trading passes...", "Intercambiando tarjetas..." },
        { "Connected over LAN: matching by network area only.",
            "Conectado por LAN: solo se compara por zona de red." },
        { "Nobody else is awake here yet.", "Nadie más está activo aquí todavía." },
        { "No plaza server set yet. Settings > Plaza server.",
            "Aún no hay servidor del plaza. Ajustes > Servidor del plaza." },
        { "Server sent something that was not JSON",
            "El servidor envió algo que no era JSON" },
        { "Server said %ld on %s", "El servidor respondió %ld en %s" },
        { "Server said %ld on hello", "El servidor respondió %ld en hello" },
        { "Checking for updates", "Buscando actualizaciones" },
        { "Downloading", "Descargando" },
        { "Unpacking", "Descomprimiendo" },
        { "Installing", "Instalando" },
        { "nx-plaza %s is the latest version.", "nx-plaza %s es la última versión." },
        { "Release %s has no .nro to install.",
            "La versión %s no tiene ningún .nro que instalar." },
        { "Version %s is available.", "La versión %s está disponible." },
        { "The download is version %s, not %s.",
            "La descarga es la versión %s, no la %s." },
        { "Version %s is installed. Restart to run it.",
            "La versión %s está instalada. Reinicia para usarla." },
        { "%d puzzle pictures downloaded. Restart to see them.",
            "%d imágenes de puzle descargadas. Reinicia para verlas." },

        // ------------------------------------------- the last of the settings
        { "Asking GitHub for the latest release",
            "Preguntando a GitHub por la última versión" },
        { "Press A to download and install it",
            "Pulsa A para descargarla e instalarla" },
        { "Press A to restart into it", "Pulsa A para reiniciar en ella" },
        { "You are on the latest release", "Tienes la última versión" },
        { "up to date", "al día" },
        { "Looks at the releases on GitHub", "Consulta las versiones en GitHub" },
        { "If the puzzles show numbered squares, get the pictures here "
          "and restart",
            "Si los puzles muestran cuadros numerados, consigue las "
            "imágenes aquí y reinicia" },
        { "failed", "falló" },
        { "Somebody", "Alguien" },
        { "keep everything", "conservar todo" },
        { "switch tab", "cambiar pestaña" },

        // ------------------------------------------------- the puzzle pictures
        { "Forest in the Rain", "Bosque bajo la lluvia" },
        { "Mountain in the Fog", "Montaña en la niebla" },
        { "Mystical Swamp", "Pantano místico" },
        { "Old Farm", "Granja vieja" },
        { "Castle Blue", "Castillo azul" },
        { "Beach at Dusk", "Playa al atardecer" },

        // --------------------------------------------------- the card themes
        { "Amber lantern", "Farolillo ámbar" },
        { "Dusk market", "Mercado al atardecer" },
        { "Tidepool", "Charca de marea" },
        { "Paper lantern", "Farolillo de papel" },
        { "Rose market", "Mercado rosa" },
        { "Night express", "Expreso nocturno" },

        // ----------------------------------------------- the pass you start with
        { "Traveller", "Viajero" },
        { "Just passing through.", "Solo estoy de paso." },

        // ------------------------------------------- what the plaza is saying
        { "Looking around...", "Buscando alrededor..." },
        { "Publishing your pass...", "Publicando tu tarjeta..." },
        { "Blocking a console...", "Bloqueando una consola..." },
        { "Unblocking a console...", "Desbloqueando una consola..." },
        { "Clearing the block list...", "Vaciando la lista de bloqueos..." },
        { "Asking the server to forget us...",
            "Pidiendo al servidor que nos olvide..." },
        { "Daily crossing limit reached. Back tomorrow.",
            "Límite de cruces del día alcanzado. Vuelve mañana." },
        { "Networking is unavailable.", "La red no está disponible." },
        { "No internet connection.", "Sin conexión a internet." },

        // ------------------------------------------- when an update goes wrong
        { "This console would not start the update worker.",
            "Esta consola no pudo iniciar el proceso de actualización." },
        { "The release list could not be read.",
            "No se pudo leer la lista de versiones." },
        { "The release list carried no version.",
            "La lista de versiones no traía ninguna versión." },
        { "The download did not finish: %s", "La descarga no terminó: %s" },
        { "The downloaded archive held no nx-plaza build.",
            "El archivo descargado no contenía ninguna versión de nx-plaza." },
        { "The downloaded file is not a valid nx-plaza build.",
            "El archivo descargado no es una versión válida de nx-plaza." },
        { "This build does not know its own path, so it cannot replace itself.",
            "Esta versión no conoce su propia ruta, así que no puede reemplazarse." },
        { "The current version could not be backed up.",
            "No se pudo respaldar la versión actual." },
        { "The update could not be written over the current one - %s",
            "No se pudo escribir la actualización sobre la actual - %s" },
        { "The installed update did not verify, so it was rolled back.",
            "La actualización instalada no se verificó, así que se revirtió." },
        { "That release publishes no puzzle art.",
            "Esa versión no publica imágenes de puzle." },
        { "That release's archive holds no puzzle art.",
            "El archivo de esa versión no contiene imágenes de puzle." },
        { "The puzzle art that arrived was not readable.",
            "Las imágenes que llegaron no se pudieron leer." },
        { "The folder for the puzzle art could not be made.",
            "No se pudo crear la carpeta para las imágenes." },
        { "The puzzle art could not be written - %s",
            "No se pudieron escribir las imágenes - %s" },

        // ------------------------------------------ the settings sections
        //
        // The eight names down the left of the screen, and the pills on the
        // rows that offer a choice.
        { "Privacy", "Privacidad" },
        { "Exchange", "Intercambio" },
        { "Appearance", "Apariencia" },
        { "Languages", "Idiomas" },
        { "This console", "Esta consola" },
        { "Data", "Datos" },
        { "About", "Acerca de" },
        { "Off", "No" },
        { "District", "Barrio" },
        { "City", "Ciudad" },
        { "Same network", "Misma red" },
        { "Anywhere", "En cualquier lugar" },
        { "Light", "Claro" },
        { "Dark", "Oscuro" },

        // -------------------------------------- when the SD card says no
        { "Could not make the export folder on the SD card.",
            "No se pudo crear la carpeta de exportación en la tarjeta SD." },
        { "Could not write to the SD card.", "No se pudo escribir en la tarjeta SD." },
        { "That file could not be read.", "No se pudo leer ese archivo." },
        { "That is not a face this app saved.",
            "Esa no es una cara guardada por esta app." },
        { "That face was saved by a different version of the app.",
            "Esa cara la guardó otra versión de la app." },
        { "Could not delete that file from the SD card.",
            "No se pudo borrar ese archivo de la tarjeta SD." },
        { "could not make the backup folder",
            "no se pudo crear la carpeta de respaldo" },
        { "could not copy %s", "no se pudo copiar %s" },
        { "there was nothing to back up", "no había nada que respaldar" },

        // ------------------------------------------------------- your plaza
        //
        // The stats page off the pass. Its captions sit under a number, so
        // they are fragments rather than sentences: "croisements en tout"
        // under 214, the way a caption reads on a card.
        { "your record", "tu historial" },
        { "Everything so far", "Todo hasta ahora" },
        { "crossings in total", "cruces en total" },
        { "the one you cross most", "con quien más te cruzas" },
        { "places", "lugares" },
        { "your oldest card", "tu tarjeta más antigua" },
        { "starred", "destacadas" },
        { "days you have crossed somebody", "días en que te cruzaste con alguien" },
        { "%u days", "%u días" },
        { "%u months", "%u meses" },
        { "%u years", "%u años" },
        { "sent something back", "devoluciones" },
        { "still unopened", "sin abrir todavía" },
        { "pieces", "piezas" },
        { "pictures finished", "imágenes terminadas" },
        { "people gave you a piece", "personas te dieron una pieza" },
        { "coins", "monedas" },
        { "earned by turning up", "ganadas por aparecer" },
        { "spent", "gastadas" },
        { "won at the games", "ganadas en los juegos" },
        { "the longest run", "la carrera más larga" },
        { "the tallest tower", "la torre más alta" },
        { "duels in a row", "duelos seguidos" },

        // --------------------------------------------------------- the quest
        //
        // The tower off the games shelf. "Étage" throughout for a floor,
        // never "niveau": a level is a thing a game has and a floor is a
        // thing a building has. The party is "il" in the singular - French
        // has no neutral singular that reads as anything but a construction,
        // and a pass is a card rather than a person's own gender.
        //
        // The class names are one word each because they sit in a stat block
        // eighteen pixels high: Lame, Garde, Éclat, Soigneur. Nothing longer
        // fits, and a role in a party game is a noun anyway.
        { "The quest", "La búsqueda" },
        { "A tower with no top, a shadow on every floor, and a party "
          "made of the people you have crossed.\nEvery shadow can leave "
          "something behind. Gear them up, pick who goes, and the fight "
          "runs itself.",
            "Una torre sin cima, una sombra en cada piso, y un grupo "
            "hecho con la gente que has cruzado.\nCada sombra puede dejar "
            "algo. Equípalos, elige quién sube y el combate se resuelve "
            "solo." },
        { "Floor %d", "Piso %d" },
        { "best floor %u", "mejor piso %u" },
        { "%d of %d places", "%d de %d plazas" },
        { "Nobody has crossed you yet - you climb alone.",
            "Nadie te ha cruzado todavía: subes solo." },

        { "Guard", "Guardia" },
        { "Blade", "Filo" },
        { "Spark", "Chispa" },
        { "Mender", "Sanador" },

        { "%s stands in front", "%s se pone delante" },
        { "%s falls", "%s cae" },
        { "The party falls", "El grupo cae" },
        { "nothing this time", "nada esta vez" },
        { "next floor", "piso siguiente" },
        { "pick again", "elegir otra vez" },
        { "Floor %d is yours", "El piso %d es tuyo" },

        { "You came back down", "Has vuelto a bajar" },
        { "%d floors, and %u coins for the ones you had not reached.",
            "%d pisos, y %u monedas por los que no habías alcanzado." },
        { "Not one floor. Cross a few more people and bring them along.",
            "Ni un piso. Cruza a unas cuantas personas más y llévatelas." },
        { "bring along", "llevar" },
        { "leave behind", "dejar" },
        { "climb", "subir" },
        { "stop", "parar" },
        { "stop here", "parar aquí" },

        { "gear", "equipo" },
        { "what they carry", "lo que llevan" },
        { "in the bag", "en la bolsa" },
        { "the bag", "la bolsa" },
        { "everything", "todo" },
        { "from floor %u", "del piso %u" },
        { "worn by %s", "lo lleva %s" },
        { "Somebody who has gone", "Alguien que ya no está" },
        { "Nothing here yet. The tower is where it comes from.",
            "Nada todavía. La torre es de donde sale." },
        { "Somebody is wearing that", "Alguien lo lleva puesto" },
        { "Take it off in the gear screen first.",
            "Quítaselo primero en la pantalla de equipo." },
        { "%zu of %zu in the bag", "%zu de %zu en la bolsa" },
        { "Nobody to dress", "Nadie a quien equipar" },
        { "Nothing here that would fit.", "Aquí no hay nada que encaje." },
        { "nothing on this peg", "nada en esta ranura" },
        { "worn", "puesto" },
        { "wear it", "equipar" },
        { "what would fit", "lo que encajaría" },
        { "take it off", "quitar" },
        { "back to the pegs", "volver a las ranuras" },
        { "throw away", "tirar" },
        { "somebody else", "otra persona" },
        { "Throw away the %s?", "¿Tirar %s?" },
        { "A %s piece from floor %u. It does not come back.",
            "Una pieza %s del piso %u. No vuelve." },
        { "Throw it away", "Tirarla" },
        { "Your bag is full", "Tu bolsa está llena" },
        { "Nothing in it was worse than what fell, so what fell stayed on the floor.",
            "Nada dentro era peor que lo que cayó, así que se quedó en el suelo." },
        { "%s was thrown out to make room.", "%s se tiró para hacer sitio." },
        { "clear out", "limpiar" },
        { "Nothing to clear out", "Nada que limpiar" },
        { "Everything spare is better than something being worn, or "
          "sits on a peg with nothing on it.",
            "Todo lo que sobra es mejor que algo puesto, o va en una "
            "ranura vacía." },
        { "Throw away %zu pieces?", "¿Tirar %zu piezas?" },
        { "Everything in the bag that is worse than what %s has on. "
          "Nothing being worn is touched.",
            "Todo lo de la bolsa que es peor que lo que lleva %s. No se "
            "toca nada puesto." },
        { "Throw them away", "Tirarlas todas" },

        { "every floor pays this week", "esta semana pagan todos los pisos" },
        { "floors up to %u have paid this week",
            "los pisos hasta el %u ya han pagado esta semana" },
        { "the week turns when the plaza is next reached",
            "la semana cambia la próxima vez que se llegue al plaza" },
        { "One %s piece came back with you.", "Una pieza %s volvió contigo." },
        { "%d pieces came back with you, the best of them %s.",
            "%d piezas volvieron contigo, la mejor %s." },

        { "weapon", "arma" },
        { "armour", "armadura" },
        { "ring", "anillo" },
        { "accessory", "accesorio" },

        { "common", "común" },
        { "uncommon", "poco común" },
        { "rare", "raro" },
        { "epic", "épico" },
        { "legendary", "legendario" },
        { "godlike", "divino" },

        { "Baton", "Bastón" },
        { "Cleaver", "Cuchilla" },
        { "Lance", "Lanza" },
        { "Hammer", "Martillo" },
        { "Jerkin", "Jubón" },
        { "Plate", "Peto" },
        { "Cloak", "Capa" },
        { "Carapace", "Caparazón" },
        { "Band", "Aro" },
        { "Signet", "Sello" },
        { "Circlet", "Diadema" },
        { "Seal", "Sigilo" },
        { "Charm", "Amuleto" },
        { "Talisman", "Talismán" },
        { "Pendant", "Colgante" },
        { "Feather", "Pluma" },

        // ------------------------------------------------- the blessings
        //
        // Drawn three at a time during a climb and gone when it ends.
        // Each is a name and one line saying what it does, and the line
        // sits in a card 420 pixels wide over four lines at most - so
        // they are written short in every language, and a fraction is
        // written as a word because "20 %%" in a sentence reads like a
        // statistic rather than like a blessing.
        { "Whetstone", "Piedra de afilar" },
        { "The party hits a fifth harder.", "El grupo golpea un quinto más fuerte." },
        { "Ironclad", "Acorazado" },
        { "The party takes a fifth less.", "El grupo recibe un quinto menos." },
        { "Hale", "Vigor" },
        { "A fifth more health, and it fills now.",
            "Un quinto más de salud, y se llena ahora." },
        { "Fleet", "Ligereza" },
        { "Everybody is three quicker.", "Todos son tres más rápidos." },
        { "Reckless", "Temerario" },
        { "A third harder, and a quarter softer.",
            "Un tercio más fuerte, y un cuarto más frágil." },
        { "Bulwark", "Baluarte" },
        { "A third tougher, and a fifth weaker.",
            "Un tercio más duro, y un quinto más débil." },
        { "Keen edge", "Filo agudo" },
        { "Telling blows land three times as often.",
            "Los golpes decisivos caen tres veces más a menudo." },
        { "Second wind", "Segundo aliento" },
        { "The first to fall gets up once, at a third.",
            "El primero en caer se levanta una vez, a un tercio." },
        { "Rally", "Arenga" },
        { "Each one who falls makes the rest hit a fifth harder.",
            "Cada uno que cae hace que el resto golpee un quinto más fuerte." },
        { "Momentum", "Impulso" },
        { "The party hits a twentieth harder for every floor from here.",
            "El grupo golpea un veinteavo más fuerte por cada piso desde aquí." },
        { "Last stand", "Última defensa" },
        { "Alone, the last one standing hits twice as hard.",
            "Solo, el último en pie golpea el doble de fuerte." },
        { "Deep breath", "Respiro hondo" },
        { "Twice as much wind back between floors.",
            "El doble de aliento entre pisos." },
        { "Battle rhythm", "Ritmo de combate" },
        { "Everybody starts each floor with their wind full.",
            "Todos empiezan cada piso con el aliento lleno." },
        { "Cheap tricks", "Trucos baratos" },
        { "Specials cost four instead of six.",
            "Las especiales cuestan cuatro en vez de seis." },
        { "Long watch", "Guardia larga" },
        { "Standing in front covers the sweep as well.",
            "Ponerse delante cubre también el barrido." },
        { "Mending hands", "Manos sanadoras" },
        { "The Mender heals half again, and steps in sooner.",
            "El sanador cura la mitad más, y entra antes." },
        { "Bright spark", "Chispa viva" },
        { "The Spark takes twice as much off the shadow's arm.",
            "La chispa le quita el doble de brazo a la sombra." },
        { "Scavenger", "Rebuscador" },
        { "The shadow leaves something four times in five.",
            "La sombra deja algo cuatro de cada cinco veces." },
        { "The stair offers you something", "La escalera te ofrece algo" },
        { "It lasts as long as the climb does.", "Dura lo que dure la subida." },
        { "take it", "tomarla" },
        { "%s gets back up", "%s se levanta" },

        // ------------------------------------------------- the same in French
        //
        // Listed on purpose rather than left out, so the scanner can tell a
        // word that needs no translation from one nobody has looked at yet.
        // tr() drops these rows: falling back to the English is the same
        // answer, and cheaper.
        { "Plaza", "Plaza" },
        { "Collection", "Colección" },
        { "collection", "colección" },
        { "Puzzles", "Puzles" },
        { "puzzles", "puzles" },
        { "plaza dash", "plaza dash" },
        { "sections", "secciones" },
        { "m", "m" },
        { "-", "-" },
        { "%d", "%d" },
        { "Notifications", "Notificaciones" },
        { "Console", "Consola" },
        { "nx-plaza ", "nx-plaza " },
        { "(none)", "(ninguno)" },
        { "NX Plaza - Online StreetPass | ", "NX Plaza - Online StreetPass | " },
        { "https://github.com/Insektaure/NX-Plaza",
            "https://github.com/Insektaure/NX-Plaza" },
    };

} // namespace

Catalog spanishCatalog()
{
    return Catalog { kEntries, sizeof(kEntries) / sizeof(kEntries[0]) };
}

} // namespace nxp
