#include "core/i18n.h"

// Russian.
//
// Generated by tools/gen_lang_tables.py from tools/lang_data.py, in the shape
// of lang_fr.cpp - same sections, same order - so any two languages can be
// read side by side. Edit the table, not this file.
//
// Left column: the English exactly as it is written in the code, which is the
// key. Reword a line in a scene and the row here stops matching in silence,
// which is what `tools/i18n_scan.py --lang ru` is for. A string this
// language has not been given yet is simply absent, and comes out in English.

namespace nxp {
namespace {

    const Translation kEntries[] = {
        // ------------------------------------------------------------- tabs
        { "Nearby", "Рядом" },
        { "The Square", "Площадь" },
        { "Games", "Игры" },
        { "The shop", "Магазин" },
        { "Trophies", "Трофеи" },
        { "Your pass", "Ваша карточка" },
        { "Settings", "Настройки" },

        // ------------------------------------------------- the hint strip
        { "again", "снова" },
        { "back", "назад" },
        { "block", "заблокировать" },
        { "cancel", "отмена" },
        { "change", "изменить" },
        { "choose", "выбрать" },
        { "close", "закрыть" },
        { "done", "готово" },
        { "fill the screen", "на весь экран" },
        { "give up", "сдаться" },
        { "jump - hold to go higher", "прыжок - держите для высокого" },
        { "jump ten", "на десять" },
        { "left and right to change", "влево и вправо, чтобы изменить" },
        { "look now", "искать сейчас" },
        { "mark read", "прочитано" },
        { "next pass", "следующая карточка" },
        { "open", "открыть" },
        { "open section", "открыть раздел" },
        { "play", "играть" },
        { "roll", "бросить" },
        { "roll again", "бросить снова" },
        { "run", "бежать" },
        { "run again", "бежать снова" },
        { "save / load", "сохранить / загрузить" },
        { "save face", "сохранить лицо" },
        { "shuffle", "случайно" },
        { "shuffle face", "случайное лицо" },
        { "spin", "крутить" },
        { "start", "начать" },

        // --------------------------------------------------------- buttons
        { "Make my pass", "Создать карточку" },
        { "Not now", "Не сейчас" },
        { "Run", "Бежать" },
        { "Run again", "Бежать снова" },
        { "Start stacking", "Начать складывать" },
        { "Stack again", "Сложить снова" },

        // ------------------------------------------- eyebrows and captions
        { "games", "игры" },
        { "trophies", "трофеи" },
        { "the shop", "магазин" },
        { "the square", "площадь" },
        { "the mii race", "гонка Mii" },
        { "the mii tower", "башня Mii" },
        { "the dice duel", "дуэль на кубиках" },
        { "the wheel", "колесо" },
        { "the quest", "восхождение" },
        { "what it pays", "выплаты" },
        { "your prediction", "ваш прогноз" },
        { "your pairing code", "ваш код сопряжения" },
        { "people met", "человек встречено" },
        { "times your pass was sent", "раз отправлена ваша карточка" },
        { "floors", "этажей" },
        { "best %u %s", "рекорд %u %s" },

        // ------------------------------------------------------ the games
        { "Something to do", "Чем заняться" },
        { "Played with the faces and names in your collection, so the "
          "more people you have crossed, the more there is here.",
            "Играется с лицами и именами из вашей коллекции: чем больше "
            "людей вы встретили, тем больше здесь занятий." },

        { "The Mii race", "Гонка Mii" },
        { "Three of the people you have crossed, against your own Mii, "
          "and nobody is faster than anybody.\nWatch for nothing, bet a "
          "coin for three back, or call first and second for eleven.",
            "Трое встреченных вами против вашего Mii, и никто не быстрее "
            "других.\nСмотрите бесплатно, монета ради трёх, или назовите "
            "первого и второго ради одиннадцати." },

        { "The dice duel", "Дуэль на кубиках" },
        { "One roll each against somebody you have crossed, and the "
          "highest takes it.\nRoll for nothing, or bet two coins for "
          "three back - and a draw hands your two back.",
            "По одному броску против встреченного вами, побеждает "
            "больший.\nБросайте бесплатно или ставьте две монеты ради "
            "трёх - при ничьей ваши две вернутся." },

        { "The lantern wheel", "Колесо фонарей" },
        { "Twelve lanterns and a needle, and two of them are a puzzle "
          "piece.\nWatch it for nothing, or ten coins a spin - every "
          "lantern pays something, and one in six is a piece.",
            "Двенадцать фонарей и стрелка, и два из них - кусочек "
            "пазла.\nСмотрите бесплатно или десять монет за оборот: "
            "каждый фонарь что-то даёт, и каждый шестой - кусочек." },

        { "The bandit", "Однорукий бандит" },
        { "Three reels, and two machines: three symbols that pay small "
          "and often, or five that pay rarely and big.\nA coin a spin, "
          "or spin for nothing - two bells hand the coin back, and the "
          "board on the wall lists every line it pays.",
            "Три барабана и два автомата: три символа, что платят мало и "
            "часто, или пять - редко и много.\nМонета за оборот или "
            "бесплатно: два колокольчика возвращают монету, а табло на "
            "стене перечисляет все выплаты." },

        { "The Mii tower", "Башня Mii" },
        { "Stack the people you have crossed, one drop at a time.\nMiss "
          "the shoulders below and they fall; drift too far from the "
          "base and the lot goes over.",
            "Складывайте встреченных вами - по одному за "
            "раз.\nПромахнётесь мимо плеч - упадёт; уйдёте далеко от "
            "основания - повалится всё." },

        { "Plaza dash", "Plaza Dash" },
        { "Your own Mii running through the plaza, jumping what the "
          "market leaves in the way.\nIt gets quicker. Nothing staked, "
          "nothing won - only how far you got.",
            "Ваш Mii бежит по плазе и прыгает через то, что оставил "
            "рынок.\nСтановится быстрее. Ставок нет и выигрыша нет - "
            "только пройденное расстояние." },

        // ------------------------------------------------ settings: sections
        { "%s never sends your name or an exact position. You choose "
          "how much of a pass leaves the console.",
            "%s никогда не отправляет ваше имя или точное положение. Вы "
            "решаете, что именно уходит с консоли." },
        { "How passes find their way to you.", "Как карточки находят дорогу к вам." },
        { "Nothing interrupts a game. The plaza waits.",
            "Ничто не прерывает игру. Плаза подождёт." },
        { "The app opens in daylight. Dark is for a dim room, or match "
          "whatever the console is set to.",
            "Приложение открывается в светлой теме. Тёмная - для "
            "полумрака, либо следуйте за консолью." },
        { "The app is written in English and says what it has been "
          "taught to say in anything else. Whatever a language is "
          "missing stays in English.",
            "Приложение написано по-английски и на других языках говорит "
            "то, чему его научили. Чего языку не хватает - остаётся "
            "по-английски." },
        { "Where your passes go, and how another console recognises this one.",
            "Куда уходят ваши карточки и как другая консоль узнаёт эту." },
        { "Everything the app keeps lives on the SD card, and all of it can go.",
            "Всё, что хранит приложение, лежит на SD-карте, и всё это можно удалить." },
        { "What this build of %s is, who made it, and where it came from.",
            "Что это за сборка %s, кто её сделал и откуда она." },

        // ---------------------------------------------------- settings: rows
        { "English - what the app is written in",
            "Английский - язык, на котором написано приложение" },
        { "Share where we crossed", "Показывать место встречи" },
        { "District only - never a street or a venue you did not name",
            "Только район - никогда улица или место, которое вы не назвали" },
        { "District label", "Название района" },
        { "e.g. Namba Station", "напр. Namba Station" },
        { "City label", "Название города" },
        { "used when sharing is set to City",
            "используется, когда выбран режим «Город»" },
        { "Show what I am playing", "Показывать, во что я играю" },
        { "The title, your hours in it, and how many games you have. "
          "Hidden titles stay hidden, always",
            "Игра, ваши часы в ней и сколько у вас игр. Скрытые игры "
            "остаются скрытыми, всегда" },
        { "Exchange passes automatically", "Обмениваться карточками автоматически" },
        { "Trades happen while the app is open",
            "Обмен идёт, пока приложение открыто" },
        { "How far a crossing reaches", "Дальность встречи" },
        { "Same network is the closest thing to walking past someone",
            "Та же сеть - ближе всего к настоящей встрече на улице" },
        { "Crossings per day", "Встреч в день" },
        { "Tell me when passes arrive", "Сообщать о новых карточках" },
        { "A card in the corner, never an interruption",
            "Карточка в углу, и никаких прерываний" },
        { "Theme", "Тема" },
        { "Hold the scenery still", "Не двигать фон" },
        { "On, for anybody the Plaza Dash minigame makes queasy: the "
          "background stops moving and only what you have to dodge "
          "does. Turn it off for the full parallax",
            "Включено для тех, кому от мини-игры Plaza Dash становится "
            "плохо: фон замирает, движется только то, что нужно обходить. "
            "Выключите ради полного параллакса" },
        { "Plaza server", "Сервер плазы" },
        { "Wi-Fi match token", "Токен Wi-Fi" },
        { "Check in now", "Подключиться сейчас" },
        { "Blocked consoles", "Заблокированные консоли" },
        { "Clear the whole list", "Очистить весь список" },
        { "unblock", "разблокировать" },
        { "none", "нет" },
        { "Write a log file", "Вести файл журнала" },
        { "Copy everything to a backup folder",
            "Скопировать всё в папку резервной копии" },
        { "Your identity, your pass and your collection, into backup/ on this card",
            "Ваша личность, карточка и коллекция - в backup/ на этой карте" },
        { "Download puzzle art", "Скачать картинки пазлов" },
        { "Delete every pass you have collected", "Удалить все собранные карточки" },
        { "This cannot be undone", "Это необратимо" },
        { "Start over as someone new", "Начать заново с новой личностью" },
        { "New id, new pass; everything you handed out goes unlinkable",
            "Новый идентификатор и карточка; всё выданное станет несвязуемым" },
        { "Check for updates", "Проверить обновления" },
        { "Check on every launch", "Проверять при запуске" },
        { "One request when the app opens; it never installs on its own",
            "Один запрос при запуске; ничего не ставится само" },
        { "Developed by Insektaure", "Разработано Insektaure" },
        { "Find us on GitHub !", "Мы на GitHub !" },
        { "This console's id", "Идентификатор этой консоли" },

        // -------------------------------------------------- settings: toasts
        { "Not connected to the plaza", "Нет связи с плазой" },
        { "This one needs the server. The dot by the tabs turns green "
          "when it can be reached.",
            "Для этого нужен сервер. Точка у вкладок зеленеет, когда он "
            "доступен." },
        { "Busy with another download", "Идёт другая загрузка" },
        { "Wait for the update in About to finish, then try again.",
            "Дождитесь окончания обновления в разделе «О программе» и повторите." },
        { "Downloading puzzle art", "Загрузка картинок" },
        { "This row shows how it is going.", "Этот пункт показывает, как идут дела." },
        { "Could not back up", "Не удалось сделать резервную копию" },
        { "Backed up to %s", "Копия сохранена в %s" },
        { "It is on the same card. Copy the backup folder to a computer "
          "to be safe from losing the card itself.",
            "Копия на той же карте. Скопируйте папку резервной копии на "
            "компьютер, чтобы не зависеть от карты." },
        { "Checking in", "Подключение" },
        { "Unblocked %s", "%s разблокирован" },
        { "They can cross you again, unless they blocked you as well.",
            "Они снова смогут вас встретить, если сами вас не заблокировали." },

        // ---------------------------------------------------- the Mii race
        { "Four runners, one line", "Четыре бегуна, одна линия" },
        { "Nobody is faster than anybody. Nothing you do changes that.",
            "Никто не быстрее других. Ваши действия этого не меняют." },
        { "Race for free", "Гонка бесплатно" },
        { "Bet 1 coin - your Mii to win", "1 монета - на победу вашего Mii" },
        { "Predict 1st and 2nd", "Назвать первого и второго" },
        { "Just to watch.", "Просто посмотреть." },
        { "%u back if it comes in.", "%u обратно, если получится." },
        { "For free, or bet 1 coin for %u back.",
            "Бесплатно или 1 монета ради %u обратно." },
        { "Nothing to bet with.", "Ставить нечего." },
        { "Nothing to bet", "Ставить нечего" },
        { "Ten coins arrive on each new day you open the app.",
            "Десять монет приходят в каждый новый день, когда вы "
            "открываете приложение." },
        { "Who comes first?", "Кто будет первым?" },
        { "And who comes second?", "А кто будет вторым?" },
        { "That is your call", "Это ваш прогноз" },
        { "First and second, in order. Eleven for a coin if you call "
          "it, or watch for nothing.",
            "Первый и второй, по порядку. Одиннадцать за монету, если "
            "угадаете, или смотрите бесплатно." },
        { "%s to win. Now who is behind them?", "%s победит. А кто следом?" },
        { "%s first, %s second.", "%s первый, %s второй." },
        { "race", "гонка" },
        { "Go", "Марш" },
        { "You are in front", "Вы впереди" },
        { "%s is in front", "%s впереди" },
        { "predict again", "снова прогноз" },
        { "race again", "гонка снова" },
        { "Called it", "В точку" },
        { "You won", "Вы победили" },
        { "%s won", "%s победил" },
        { "Nobody", "Никто" },
        { "You said %s then %s - they came %s and %s.",
            "Вы назвали %s, затем %s - они пришли %s и %s." },
        { "The bet paid %u - %u coins to spend.",
            "Ставка принесла %u - осталось %u монет." },
        { "The bet cost you a coin. %u left.", "Ставка стоила монету. Осталось %u." },
        { "Nothing bet, but right is right.",
            "Ставки не было, но угадали - значит угадали." },
        { "Nothing bet, nothing lost.", "Ставки не было - и потерь нет." },
        { "Predict again", "Снова прогноз" },
        { "Race again", "Гонка снова" },
        { "Bet %u coin - %u back", "Ставка %u монета - %u обратно" },
        { "1st", "1-й" },
        { "2nd", "2-й" },
        { "3rd", "3-й" },
        { "4th", "4-й" },

        // ---------------------------------------------------- the dice duel
        { "One roll each", "По одному броску" },
        { "Highest roll takes it. A draw hands your %u back.",
            "Побеждает больший бросок. При ничьей ваши %u вернутся." },
        { "Roll for free", "Бросить бесплатно" },
        { "%u coins to play", "%u монет за игру" },
        { "Ten arrive on each new day you open the app.",
            "Десять приходят в каждый новый день, когда вы открываете приложение." },
        { "%d all - nobody takes it", "По %d - никто не выиграл" },
        { "%d beats %d", "%d бьёт %d" },
        { "%d loses to %d", "%d проигрывает %d" },
        { "Your %u came back. %u to spend.", "Ваши %u вернулись. Осталось %u." },
        { "The bet cost you %u. %u left.", "Ставка стоила %u. Осталось %u." },
        { "Nothing bet, and nothing decided.",
            "Ставки не было, и ничего не решилось." },
        { "Nothing bet, but a win is a win.",
            "Ставки не было, но победа есть победа." },
        { "%u in a row", "%u подряд" },
        { "Roll again", "Бросить снова" },
        { "Bet %u coins - %u back", "Ставка %u монет - %u обратно" },

        // ------------------------------------------------- the lantern wheel
        { "%u coins for a spin", "%u монет за оборот" },
        { "Watch it for nothing, or put %u coins on it. Every lantern "
          "pays something and %d of the %d are a puzzle piece. You have "
          "%u.",
            "Смотрите бесплатно или поставьте %u монет. Каждый фонарь "
            "что-то даёт, а %d из %d - кусочек пазла. У вас %u." },
        { "Spin for nothing", "Крутить бесплатно" },
        { "A piece of %s", "Кусочек «%s»" },
        { "The piece lantern", "Фонарь с кусочком пазла" },
        { "The %u lantern", "Фонарь на %u" },
        { "Piece %d, and the panel will say the wheel brought it. %u "
          "coins left.",
            "Кусочек %d, и в панели будет сказано, что его принесло "
            "колесо. Осталось %u монет." },
        { "%u coins to spend. A spin costs %u.",
            "%u монет на руках. Оборот стоит %u." },
        { "Nothing was on it - that one only pays when you have staked.",
            "Ставки не было - этот платит только со ставкой." },
        { "Nothing staked, so nothing won. It would have paid %u.",
            "Ставки не было, значит и выигрыша нет. Дало бы %u." },
        { "Spin again", "Крутить снова" },
        { "Bet %u coins", "Ставка %u монет" },

        // ---------------------------------------------------- the bandit
        { "A coin a spin", "Монета за оборот" },
        { "A coin a spin, and %u to spend. X changes machines.",
            "Монета за оборот, у вас %u. X меняет автомат." },
        { "THREE SYMBOLS", "ТРИ СИМВОЛА" },
        { "FIVE SYMBOLS", "ПЯТЬ СИМВОЛОВ" },
        { "three symbols", "три символа" },
        { "five symbols", "пять символов" },
        { "Spin for free", "Крутить бесплатно" },
        { "Bet %u coin", "Ставка %u монета" },
        { "Two sevens", "Две семёрки" },
        { "Two bells", "Два колокольчика" },
        { "Two the same", "Два одинаковых" },
        { "Any two the same", "Любые два одинаковых" },
        { "Nothing", "Ничего" },
        { "Three %s", "Три %s" },
        { "suns", "солнца" },
        { "moons", "луны" },
        { "bells", "колокольчика" },
        { "sevens", "семёрки" },
        { "bars", "полоски" },
        { "a line about every 3 spins", "выигрыш примерно каждые 3 оборота" },
        { "a line about every 4 spins", "выигрыш примерно каждые 4 оборота" },
        { "%u back, and %u to spend.", "%u обратно, на руках %u." },
        { "That coin is gone. %u left.", "Монета ушла. Осталось %u." },
        { "Nothing staked, so nothing won - it would have paid %u.",
            "Ставки не было, значит и выигрыша нет - дало бы %u." },
        { "Nothing staked, and nothing to stake it on.",
            "Ставки не было, и ставить нечего." },

        // ---------------------------------------------------- the Mii tower
        { "Stack them up", "Складывайте их" },
        { "A drops whoever is swinging. Miss the shoulders below and "
          "they fall; drift too far from the base and the lot goes "
          "over.",
            "A отпускает того, кто качается. Промахнётесь мимо плеч - "
            "упадёт; уйдёте далеко от основания - повалится всё." },
        { "drop", "отпустить" },
        { "lean", "наклон" },
        { "%d floors", "Этажей: %d" },
        { "best %u floors", "рекорд %u этажей" },
        { "floors, best %u", "этажей, рекорд %u" },
        { "%s had nothing to stand on.", "%s было не на что встать." },
        { "It went over with %s on top.", "Всё повалилось, а сверху был %s." },

        // ---------------------------------------------------- plaza dash
        { "Jump the market", "Перепрыгни рынок" },
        { "A to jump, and hold it to jump higher. It gets quicker until "
          "you hit something.",
            "A - прыжок, держите - выше. Разгоняется, пока во что-нибудь "
            "не влетите." },
        { "%u m", "%u м" },
        { "best %u m", "рекорд %u м" },
        { "Best is %u m.", "Рекорд - %u м." },
        { "A new best.", "Новый рекорд." },
        { "a new best", "новый рекорд" },

        // ------------------------------------------- shared by the games
        { "You", "Вы" },
        { "A stranger", "Незнакомец" },

        // ---------------------------------------------------- the trophies
        { "show %s", "показать: %s" },
        { "earned only", "только полученные" },
        { "still to earn", "ещё не получены" },
        { "all of them", "все" },
        { "bronze", "бронза" },
        { "silver", "серебро" },
        { "gold", "золото" },
        { "platinum", "платина" },
        { "%d of %zu", "%d из %zu" },
        { "earned", "получен" },
        { "earned %s", "получен %s" },
        { "Nothing earned yet. Go and meet somebody.",
            "Пока ничего не получено. Пойдите кого-нибудь встретить." },
        { "Everything here is earned.", "Здесь получено всё." },
        { "A %s trophy.", "Трофей: %s." },
        { "%d trophies earned", "Получено трофеев: %d" },
        { "Your record is in the trophies tab.",
            "Ваши достижения - во вкладке трофеев." },

        { "Somebody's out there", "Кто-то там есть" },
        { "Cross one other console.", "Встретьте одну другую консоль." },
        { "Properly introduced", "Как положено представлен" },
        { "Give your pass a name, a greeting and something to carry.",
            "Дайте карточке имя, приветствие и что-нибудь с собой." },
        { "Fully laden", "Загружен полностью" },
        { "Carry four things on your pass at once.",
            "Носите на карточке четыре вещи сразу." },
        { "A corner of something", "Уголок чего-то" },
        { "Take your first puzzle piece off a crossing.",
            "Получите первый кусочек пазла со встречи." },
        { "Worth keeping", "Стоит сохранить" },
        { "Star a card.", "Отметьте карточку." },
        { "Ten faces", "Десять лиц" },
        { "Cross ten different consoles.", "Встретьте десять разных консолей." },
        { "A week of it", "Целая неделя" },
        { "Open the app on seven different days.",
            "Откройте приложение в семь разных дней." },
        { "Two down", "Два готово" },
        { "Finish two puzzles.", "Соберите два пазла." },
        { "First purchase", "Первая покупка" },
        { "Buy something in the shop.", "Купите что-нибудь в магазине." },
        { "Beginner's luck", "Везение новичка" },
        { "Win a bet in the games tab.", "Выиграйте ставку во вкладке игр." },
        { "First blood", "Первая кровь" },
        { "Win a duel at the dice.", "Выиграйте дуэль на кубиках." },
        { "Six all", "Шесть на шесть" },
        { "Roll a six against a six.", "Выбросьте шестёрку против шестёрки." },
        { "Lined up", "Выстроились" },
        { "Line up three of a kind at the bandit.",
            "Соберите три одинаковых на автомате." },
        { "The wheel's own", "Подарок колеса" },
        { "Win a puzzle piece on the lantern wheel.",
            "Выиграйте кусочек пазла на колесе фонарей." },
        { "Ten storeys", "Десять этажей" },
        { "Stack ten floors in the Mii tower.", "Сложите десять этажей в башне Mii." },
        { "Dead centre", "Точно по центру" },
        { "Land a floor within six pixels of the one below.",
            "Поставьте этаж в пределах шести пикселей от нижнего." },
        { "Off the mark", "Со старта" },
        { "Run a hundred metres in the plaza dash.",
            "Пробегите сто метров в Plaza Dash." },
        { "Your own face", "Своё лицо" },
        { "Make a face of your own in the Mii maker.",
            "Создайте своё лицо в редакторе Mii." },
        { "Redecorated", "Оформлено по-своему" },
        { "Give your card a look of your own.", "Придайте карточке свой вид." },
        { "Out in the world", "В большом мире" },
        { "Have your pass reach somebody.",
            "Пусть ваша карточка дойдёт до кого-нибудь." },
        { "Matching outfits", "Одинаковый наряд" },
        { "Cross somebody whose card wears the same look as yours.",
            "Встретьте того, чья карточка выглядит как ваша." },
        { "Same taste", "Одинаковый вкус" },
        { "Cross somebody carrying something you carry too.",
            "Встретьте того, кто несёт то же, что и вы." },
        { "The strong silent type", "Молчаливый тип" },
        { "Cross a pass with nothing written on it.",
            "Встретьте карточку без единой надписи." },
        { "A busy afternoon", "Насыщенный день" },
        { "Cross ten consoles in one day.", "Встретьте десять консолей за один день." },
        { "Fifty faces", "Пятьдесят лиц" },
        { "Cross fifty different consoles.", "Встретьте пятьдесят разных консолей." },
        { "A hundred faces", "Сто лиц" },
        { "Cross a hundred different consoles.", "Встретьте сто разных консолей." },
        { "A hundred hellos", "Сто приветствий" },
        { "Cross people a hundred times, the same ones included.",
            "Встретьте людей сто раз, включая повторные встречи." },
        { "A regular", "Постоянный знакомый" },
        { "Cross the same console ten times.", "Встретьте одну консоль десять раз." },
        { "Around town", "По окрестностям" },
        { "Cross people in five different places.",
            "Встретьте людей в пяти разных местах." },
        { "Ten places", "Десять мест" },
        { "Cross people in ten different places.",
            "Встретьте людей в десяти разных местах." },
        { "The late train", "Последний поезд" },
        { "Cross somebody between midnight and four.",
            "Встретьте кого-нибудь между полуночью и четырьмя." },
        { "Every day of the week", "Каждый день недели" },
        { "Cross somebody on each of the seven weekdays.",
            "Встретьте кого-нибудь в каждый из семи дней недели." },
        { "A fortnight", "Две недели" },
        { "Open the app on fourteen different days.",
            "Откройте приложение в четырнадцать разных дней." },
        { "An old friend", "Старый знакомый" },
        { "Keep a card for six months.", "Храните карточку полгода." },
        { "A picture at last", "Наконец картина" },
        { "Finish a puzzle.", "Соберите пазл." },
        { "Halfway through", "На полпути" },
        { "Hold half of every piece there is.",
            "Соберите половину всех существующих кусочков." },
        { "A picture by committee", "Картина в складчину" },
        { "Take pieces from ten different people.",
            "Получите кусочки от десяти разных людей." },
        { "A shortlist", "Короткий список" },
        { "Star twenty-five cards.", "Отметьте двадцать пять карточек." },
        { "Nothing left unread", "Ничего непрочитанного" },
        { "Open every card you hold, with fifty of them.",
            "Откройте все карточки, имея пятьдесят." },
        { "Reciprocated", "Ответили взаимностью" },
        { "Send something back to twenty-five people.",
            "Отправьте что-нибудь в ответ двадцати пяти людям." },
        { "Namesake", "Тёзка" },
        { "Cross somebody who chose the same name as you.",
            "Встретьте того, кто выбрал такое же имя." },
        { "Somebody with a life", "У кого-то есть жизнь" },
        { "Cross a pass carrying a thousand hours in one title.",
            "Встретьте карточку с тысячей часов в одной игре." },
        { "The shop's best customer", "Лучший покупатель магазина" },
        { "Spend five hundred coins.", "Потратьте пятьсот монет." },
        { "Saving up", "Копилка" },
        { "Have five hundred coins at once.", "Имейте пятьсот монет одновременно." },
        { "On a run", "На серии" },
        { "Win five duels at the dice in a row.",
            "Выиграйте пять дуэлей на кубиках подряд." },
        { "A good day at the tables", "Удачный день за столом" },
        { "Win fifty coins betting in the games tab.",
            "Выиграйте пятьдесят монет ставками во вкладке игр." },
        { "Sevens", "Три семёрки" },
        { "Line up three sevens at the bandit.", "Соберите три семёрки на автомате." },
        { "Twice lucky", "Дважды повезло" },
        { "Win two puzzle pieces on the lantern wheel.",
            "Выиграйте два кусочка пазла на колесе фонарей." },
        { "Twenty up", "Двадцать этажей" },
        { "Stack twenty floors in the Mii tower.",
            "Сложите двадцать этажей в башне Mii." },
        { "Steady hands", "Твёрдая рука" },
        { "Land five floors in a row dead centre.",
            "Поставьте пять этажей подряд точно по центру." },
        { "Talked it down", "Выправил в последний миг" },
        { "Lean a tower to the edge of going over, and bring it back.",
            "Наклоните башню на грань падения и выправьте её." },
        { "A good run", "Хороший забег" },
        { "Run five hundred metres in the plaza dash.",
            "Пробегите пятьсот метров в Plaza Dash." },
        { "Five hundred faces", "Пятьсот лиц" },
        { "Cross five hundred different consoles.",
            "Встретьте пятьсот разных консолей." },
        { "A thousand faces", "Тысяча лиц" },
        { "Cross a thousand different consoles.", "Встретьте тысячу разных консолей." },
        { "A thousand hellos", "Тысяча приветствий" },
        { "Cross people a thousand times, the same ones included.",
            "Встретьте людей тысячу раз, включая повторные встречи." },
        { "Practically neighbours", "Почти соседи" },
        { "Cross the same console fifty times.",
            "Встретьте одну консоль пятьдесят раз." },
        { "Far travelled", "Много путешествовал" },
        { "Cross people in twenty-five different places.",
            "Встретьте людей в двадцати пяти разных местах." },
        { "Fifty places", "Пятьдесят мест" },
        { "Cross people in fifty different places.",
            "Встретьте людей в пятидесяти разных местах." },
        { "A month of it", "Целый месяц" },
        { "Open the app on thirty different days.",
            "Откройте приложение в тридцать разных дней." },
        { "A hundred days", "Сто дней" },
        { "Open the app on a hundred different days.",
            "Откройте приложение в сто разных дней." },
        { "A year of it", "Целый год" },
        { "Open the app on three hundred and sixty-five different days.",
            "Откройте приложение в триста шестьдесят пять разных дней." },
        { "Known you for a year", "Знакомы уже год" },
        { "Keep a card for a year.", "Храните карточку год." },
        { "Every picture", "Все картины" },
        { "Finish every puzzle.", "Соберите все пазлы." },
        { "By hand alone", "Без единой покупки" },
        { "Finish a puzzle without buying a single piece.",
            "Соберите пазл, не купив ни одного кусочка." },
        { "The full set", "Полный набор" },
        { "Line up three of a kind of every symbol the bandit has.",
            "Соберите по три одинаковых из каждого символа автомата." },
        { "Five from the wheel", "Пять с колеса" },
        { "Win five puzzle pieces on the lantern wheel.",
            "Выиграйте пять кусочков пазла на колесе фонарей." },
        { "Thirty storeys", "Тридцать этажей" },
        { "Stack thirty floors in the Mii tower.",
            "Сложите тридцать этажей в башне Mii." },
        { "A kilometre of plaza", "Километр по плазе" },
        { "Run a thousand metres in the plaza dash.",
            "Пробегите тысячу метров в Plaza Dash." },
        { "Seven in a row", "Семь подряд" },
        { "Win seven duels at the dice in a row.",
            "Выиграйте семь дуэлей на кубиках подряд." },
        { "The bookmaker's problem", "Головная боль букмекера" },
        { "Win two hundred coins betting in the games tab.",
            "Выиграйте двести монет ставками во вкладке игр." },
        { "Fifty contributors", "Пятьдесят участников" },

        { "A shadow on the stair", "Тень на лестнице" },
        { "Clear a floor of the quest.", "Пройти этаж восхождения." },
        { "Something to wear", "Есть что надеть" },
        { "Find your first piece of gear in the quest.",
            "Найти первую вещь снаряжения в восхождении." },
        { "Ten floors up", "Десять этажей вверх" },
        { "Reach the tenth floor of the quest.",
            "Дойти до десятого этажа восхождения." },
        { "Well turned out", "Хорошо снаряжён" },
        { "Have somebody wearing a weapon, armour, a ring and an accessory at once.",
            "Одеть кого-нибудь сразу в оружие, броню, кольцо и аксессуар." },
        { "A full stair", "Полная лестница" },
        { "Take five up the tower at once.", "Подняться в башню впятером." },
        { "Twenty floors up", "Двадцать этажей вверх" },
        { "Reach the twentieth floor of the quest.",
            "Дойти до двадцатого этажа восхождения." },
        { "Legendary", "Легендарная" },
        { "Hold a legendary piece of gear.", "Иметь легендарную вещь снаряжения." },
        { "Godlike", "Божественная" },
        { "Hold a godlike piece of gear.", "Иметь божественную вещь снаряжения." },

        { "Take pieces from fifty different people.",
            "Получите кусочки от пятидесяти разных людей." },
        { "The whole plaza", "Вся плаза" },
        { "Earn everything else.", "Получите всё остальное." },

        // ------------------------------------------- settings, the rest of it
        { "following the console, currently %s", "следует за консолью, сейчас %s" },
        { "light", "светлая" },
        { "dark", "тёмная" },
        { "light by default", "по умолчанию светлая" },
        { "http://host:port of your own server", "http://хост:порт вашего сервера" },
        { "where this build trades passes", "где эта сборка обменивается карточками" },
        { "no Wi-Fi name to match on - wired, or not connected",
            "нет имени Wi-Fi для сопоставления - кабель или нет сети" },
        { "consoles on \"%s\" share this", "консоли в сети \"%s\" совпадают по нему" },
        { "Nobody is blocked here. A asks the plaza to drop any it "
          "still has",
            "Здесь никто не заблокирован. A попросит плазу снять "
            "оставшиеся блокировки" },
        { "Nobody is blocked here. Needs the plaza, and this console is offline",
            "Здесь никто не заблокирован. Нужна плаза, а консоль не в сети" },
        { " - blocked %s", " - заблокирован %s" },
        { ". A lets them cross you again", ". A разрешит им снова вас встречать" },
        { ". Offline - unblocking needs the plaza",
            ". Нет сети - для разблокировки нужна плаза" },
        { "Clears all %zu at once, on this console and on the plaza",
            "Снимает все %zu сразу - и здесь, и на плазе" },
        { "Offline - clearing the list needs the plaza, or the two would disagree",
            "Нет сети - чтобы очистить список, нужна плаза, иначе они разойдутся" },
        { "Off. Turn it on before reporting a problem, then off again",
            "Выключено. Включите перед отчётом о проблеме, потом выключите" },
        { "plaza.log, beside your pass on the SD card - it names this "
          "console and the server",
            "plaza.log, рядом с вашей карточкой на SD-карте - в нём "
            "указаны эта консоль и сервер" },

        // -------------------------------------- the rest of the hint strip
        //
        // The verbs, from screens whose own words are still English: the strip
        // along the bottom is chrome, like the tabs, and reads as one thing
        // wherever you are rather than changing language with the screen.
        { "buy", "купить" },
        { "star", "в избранное" },
        { "unstar", "убрать из избранного" },
        { "delete", "удалить" },
        { "save", "сохранить" },
        { "load this face", "загрузить это лицо" },
        { "look at it", "посмотреть" },
        { "look at them", "посмотреть" },
        { "carry it", "взять" },
        { "put it back", "вернуть" },
        { "trade back", "ответить" },
        { "toggle", "переключить" },
        { "block - offline", "заблокировать - нет сети" },
        { "make my pass", "создать карточку" },
        { "not now", "не сейчас" },
        { "your details", "ваши данные" },
        { "your mii", "ваш Mii" },

        // ------------------------------------------------------ how long ago
        //
        // The one place a French sentence will not take the English shape:
        // "3 days ago" puts the number in the middle, "il y a 3 jours" puts it
        // at the end, which is why relativeTime() hands the whole line to
        // format() rather than gluing a number to a word.
        { "unknown", "неизвестно" },
        { "just now", "только что" },
        { "%llum ago", "%llu мин назад" },
        { "%lluh ago", "%llu ч назад" },
        { "Yesterday", "Вчера" },
        { "%d days ago", "%d дн. назад" },
        { "%d %s", "%d %s" },
        { "Jan", "янв." },
        { "Feb", "февр." },
        { "Mar", "марта" },
        { "Apr", "апр." },
        { "May", "мая" },
        { "Jun", "июня" },
        { "Jul", "июля" },
        { "Aug", "авг." },
        { "Sep", "сент." },
        { "Oct", "окт." },
        { "Nov", "нояб." },
        { "Dec", "дек." },
        { "Sun", "вс" },
        { "Mon", "пн" },
        { "Tue", "вт" },
        { "Wed", "ср" },
        { "Thu", "чт" },
        { "Fri", "пт" },
        { "Sat", "сб" },

        // ------------------------------------------------------- the plaza
        { "the plaza - today", "плаза - сегодня" },
        { "Nobody has crossed you yet", "Вас пока никто не встретил" },
        { "1 person crossed your path", "Вас встретил 1 человек" },
        { "%u people crossed your path", "Вас встретили %u человек" },
        { "1 pass waiting for you", "Вас ждёт 1 карточка" },
        { "%u passes waiting for you", "Вас ждут %u карточек" },
        { "Nothing new today", "Сегодня ничего нового" },
        { "Take the console outside, or join a busier network. Passes "
          "arrive on their own.",
            "Выйдите с консолью на улицу или подключитесь к более людной "
            "сети. Карточки придут сами." },
        { "Somewhere out there.", "Где-то там." },
        { ", ", ", " },
        { ", and ", " и " },
        { "Unopened passes", "Неоткрытые карточки" },
        { "nothing yet", "пока ничего" },
        { "all caught up", "всё прочитано" },
        { "%u waiting", "%u в ожидании" },
        { " - oldest %s", " - самая старая %s" },
        { " - %u crossings, %u place", " - %u встреч, %u место" },
        { " - %u crossings, %u places", " - %u встреч, мест: %u" },
        { "new", "новое" },
        { "hidden title", "скрытая игра" },
        { "%s - %s", "%s - %s" },
        { "%d more", "ещё %d" },
        { "The plaza is empty", "Плаза пуста" },
        { "Your console trades a pass with anyone whose Switch is on "
          "the same network, or nearby on the internet. Leave it "
          "running and come back.",
            "Ваша консоль обменивается карточкой со всеми, чей Switch в "
            "той же сети или рядом в интернете. Оставьте её работать и "
            "вернитесь позже." },
        { "Looking for passes", "Поиск карточек" },
        { "Asking the plaza who else has been around.",
            "Спрашиваем у плазы, кто ещё был рядом." },

        // ------------------------------------------------------ the collection
        { "Starred %s", "%s в избранном" },
        { "Unstarred %s", "%s убран из избранного" },
        { "Kept when the collection fills up.",
            "Останется, когда коллекция заполнится." },
        { "No longer kept when the collection fills up.",
            "Больше не останется, когда коллекция заполнится." },
        { "%u %s met", "Встречено: %u %s" },
        { "person", "человек" },
        { "people", "人" },
        { "%s - %u crossings in total", "%s - всего встреч: %u" },
        { "by name", "по имени" },
        { "starred first", "избранные сначала" },
        { "most recent first", "сначала новые" },
        { "sort by name", "сортировать по имени" },
        { "sort by starred", "сортировать по избранным" },
        { "sort by recent", "сортировать по дате" },
        { "Nothing collected yet. The first pass you receive lands here "
          "and stays.",
            "Пока ничего не собрано. Первая полученная карточка появится "
            "здесь и останется." },
        { "met %u times", "встреч: %u" },

        // ------------------------------------------------------- the Square
        { "Everyone you cross paths with turns up here.",
            "Все, кого вы встречаете, появляются здесь." },
        { "A few of the people you have met, milling about.",
            "Некоторые из встреченных вами, гуляют здесь." },

        // --------------------------------------------------------- nearby
        { "live - scanning", "в эфире - поиск" },
        { "live - trading", "в эфире - обмен" },
        { "offline", "нет сети" },
        { "cannot reach the plaza", "плаза недоступна" },
        { "1 console awake near you", "Рядом активна 1 консоль" },
        { "%d consoles awake near you", "Рядом активны консоли: %d" },
        { "Passes exchange on their own. You do not have to sit here.",
            "Карточки обмениваются сами. Сидеть здесь не нужно." },
        { "Nobody else has checked in here yet. Leave the app open; the "
          "plaza fills faster if you do.",
            "Здесь пока никто больше не отметился. Оставьте приложение "
            "открытым - плаза наполняется быстрее." },
        { "waiting", "ожидание" },
        { "exchanging...", "обмен..." },
        { "passed", "встречено" },
        { "out of range", "вне зоны" },
        { "same network", "та же сеть" },
        { "nearby network", "сеть поблизости" },
        { "somewhere else", "где-то ещё" },
        { "Up to %d per day while the app is open",
            "До %d в день, пока приложение открыто" },
        { " - matching on \"%s\"", " - сопоставление по \"%s\"" },
        { " - on \"%s\", no name to match",
            " - в \"%s\", нет имени для сопоставления" },

        // ----------------------------------------------------- a peer nearby
        { "awake near you", "активна рядом" },
        { "Someone", "Кто-то" },
        { "How close", "Близость" },
        { "Playing", "Играет" },
        { "Right now", "Прямо сейчас" },
        { "Trading passes", "Обмен карточками" },
        { "You have already crossed", "Вы уже встречались" },
        { "Drifted out of range", "Вышел из зоны" },
        { "Waiting for the next round", "Ждём следующего круга" },
        { "Passes trade on their own with everyone in range. There is "
          "nothing to press here, and nothing to wait for.",
            "Карточки обмениваются сами со всеми в зоне действия. Здесь "
            "нечего нажимать и нечего ждать." },

        // -------------------------------------------------------- the puzzles
        { "Nothing to collect yet", "Пока нечего собирать" },
        { "Every puzzle is finished", "Все пазлы собраны" },
        { "%d of %zu finished", "%d из %zu собрано" },
        { "Every console you cross brings one piece. Pick which puzzle "
          "they go into.",
            "Каждая встреченная консоль приносит кусочек. Выберите, в "
            "какой пазл они пойдут." },
        { "filling", "заполняется" },
        { "finished", "готово" },
        { "%d of %u pieces", "%d из %u кусочков" },
        { "already finished", "уже собран" },
        { "already filling", "уже заполняется" },
        { "fill this one next", "заполнять следующим этот" },
        { "%s is finished", "«%s» собран" },
        { "Pieces go into the first puzzle that is not.",
            "Кусочки идут в первый несобранный." },
        { "Already filling %s", "«%s» уже заполняется" },
        { "Every crossing brings a piece of this one.",
            "Каждая встреча приносит кусочек этого пазла." },
        { "Filling %s", "Заполняется «%s»" },
        { "Crossings go into this one until you pick another.",
            "Встречи идут в этот пазл, пока не выберете другой." },
        { "One person brought this", "Это принёс один человек" },
        { "%d people brought this", "Это принесли %d человек" },
        { " - finished %s", " - собран %s" },
        { "Piece %d", "Кусочек %d" },
        { "Brought by", "Принёс" },
        { "Not found yet", "Пока не найден" },
        { "someone", "кто-то" },
        { "Cross someone while this puzzle is the one being filled.",
            "Встретьте кого-нибудь, пока заполняется этот пазл." },
        { "Collected before the app started keeping track.",
            "Получен до того, как приложение начало вести учёт." },

        // ---------------------------------------------------------- the shop
        { "%u earned - %u spent", "получено %u - потрачено %u" },
        { "A piece you do not have yet of %s - the puzzle your "
          "crossings are filling, %d of %u so far. Twice the price, "
          "because you get to say which picture it goes into.",
            "Кусочек «%s», которого у вас нет - пазл, что заполняют ваши "
            "встречи, пока %d из %u. Двойная цена, потому что картину "
            "выбираете вы." },
        { "%s is finished. Choose another to fill on the puzzles "
          "screen, or take your chances with any puzzle.",
            "«%s» собран. Выберите другой на экране пазлов или попробуйте "
            "удачу с любым." },
        { "A piece of any puzzle", "Кусочек любого пазла" },
        { "Half the price, and you do not choose: one piece drawn from "
          "every unfinished puzzle at once - %d still to find across %d "
          "of them.",
            "Половина цены, и вы не выбираете: кусочек берётся сразу из "
            "всех несобранных пазлов - осталось найти %d в %d из них." },
        { "Every puzzle is finished. There is nothing left to sell you.",
            "Все пазлы собраны. Продавать больше нечего." },
        { "Nothing on the shelf yet.", "На полке пока ничего." },
        { "%u more coins needed. Ten arrive on every new day you open "
          "the app.",
            "Не хватает %u монет. Десять приходят в каждый новый день, "
            "когда вы открываете приложение." },
        { "sold out", "распродано" },
        { "%u coins short", "Не хватает %u монет" },
        { "Nothing to sell there", "Тут продавать нечего" },
        { "There are no pieces left to find there.", "Там больше нет кусочков." },
        { "Piece %d of %s", "Кусочек %d из «%s»" },
        { "%u coins left.", "Осталось %u монет." },
        { "Buy %s for %u coins?", "Купить %s за %u монет?" },
        { "%s That leaves you %u.", "%s Останется %u." },
        { "One you do not hold yet, into the puzzle you are filling.",
            "Тот, которого у вас нет, в заполняемый пазл." },
        { "Drawn from every unfinished puzzle at once, so it may not be "
          "the one you are filling.",
            "Берётся сразу из всех несобранных пазлов, так что может "
            "оказаться не тот, что вы заполняете." },
        { "Buy it", "Купить" },

        // -------------------------------------------------------- your pass
        { "your pass", "ваша карточка" },
        { "This is what they see", "Вот что видят другие" },
        { "%s theme", "тема %s" },
        { "(no greeting yet)", "(приветствия пока нет)" },
        { "Name", "Имя" },
        { "not set yet", "пока не задано" },
        { "Greeting", "Приветствие" },
        { "%zu of 60 characters", "%zu из 60 символов" },
        { "Card theme", "Тема карточки" },
        { "%s - 6 unlocked", "%s - открыто 6" },
        { "What you carry", "Что вы носите" },
        { "Title on your pass", "Игра на вашей карточке" },
        { "hidden by privacy settings", "скрыто настройками приватности" },
        { "reading the play history...", "читаем историю игр..." },
        { "nothing played on this console yet", "на этой консоли пока не играли" },
        { "hidden", "скрыто" },
        { "%s - %uh", "%s - %u ч" },
        { "edit", "изменить" },
        { "edit your mii", "изменить Mii" },
        { "next theme", "следующая тема" },
        { "next title", "следующая игра" },
        { "The name on your pass", "Имя на вашей карточке" },
        { "Up to 60 characters", "До 60 символов" },
        { "Your pass never carries your account name, your friend code, "
          "or a precise position - only what you typed and, if you "
          "allow it, the place you named.",
            "Ваша карточка никогда не несёт имя аккаунта, код друга или "
            "точное положение - только то, что вы написали, и, если "
            "разрешите, названное вами место." },

        // ------------------------------------------------------ what you carry
        { "on your pass", "на вашей карточке" },
        { "%zu of %d", "%zu из %d" },
        { "Four is the limit", "Максимум четыре" },
        { "Put something back before picking this up.",
            "Верните что-нибудь, прежде чем взять это." },

        // -------------------------------------------------------- a crossing
        { "crossed paths - %s", "встретились - %s" },
        { "playing %s", "играет в %s" },
        { "somewhere on the network", "где-то в сети" },
        { "carrying", "несёт" },
        { "time crossed", "раз встречено" },
        { "times crossed", "раз встречено" },
        { "game installed", "игра установлена" },
        { "games installed", "игр установлено" },
        { "hours played", "часов в игре" },
        { "in %s", "в %s" },
        { "Already traded back", "Уже отправлено в ответ" },
        { "Trade something back", "Отправить что-нибудь в ответ" },
        { "Take it, send something back", "Взять и отправить что-нибудь в ответ" },
        { "Star this card", "В избранное" },
        { "Unstar this card", "Убрать из избранного" },
        { "Sent something back to %s", "%s отправлен ответ" },
        { "It travels with your pass the next time you cross.",
            "Оно поедет с вашей карточкой при следующей встрече." },
        { "Blocking has to reach the server, or they would keep "
          "receiving your pass. Try again when the dot by the tabs is "
          "green.",
            "Блокировка должна дойти до сервера, иначе они продолжат "
            "получать вашу карточку. Повторите, когда точка у вкладок "
            "станет зелёной." },
        { "Block %s?", "Заблокировать %s?" },
        { "Their pass is deleted and this console can never cross you "
          "again. They are not told.",
            "Их карточка удаляется, и эта консоль больше никогда вас не "
            "встретит. Им об этом не сообщают." },
        { "Block and forget", "Заблокировать и забыть" },

        // ------------------------------------------------------- your Mii
        { "your face", "ваше лицо" },
        { "Make your Mii", "Создайте свой Mii" },
        { "how others see you", "как вас видят другие" },
        { "yes", "да" },
        { "no", "нет" },
        { "%d of %d", "%d из %d" },
        { "Face shape", "Форма лица" },
        { "Skin tone", "Тон кожи" },
        { "Hair", "Волосы" },
        { "Hair colour", "Цвет волос" },
        { "Hair flipped", "Волосы отражены" },
        { "Eyes", "Глаза" },
        { "Eye colour", "Цвет глаз" },
        { "Eyebrows", "Брови" },
        { "Eyebrow colour", "Цвет бровей" },
        { "Nose", "Нос" },
        { "Mouth", "Рот" },
        { "Lip colour", "Цвет губ" },
        { "Glasses", "Очки" },
        { "Glasses colour", "Цвет очков" },
        { "Moustache", "Усы" },
        { "Beard", "Борода" },
        { "Facial hair colour", "Цвет бороды" },
        { "Wrinkles", "Морщины" },
        { "Makeup", "Макияж" },
        { "Mole", "Родинка" },
        { "Headwear", "Головной убор" },
        { "Build", "Телосложение" },
        { "Height", "Рост" },
        { "Favourite colour", "Любимый цвет" },
        { "Eye spacing", "Расстояние между глазами" },
        { "Eye height", "Высота глаз" },
        { "Eye width", "Ширина глаз" },
        { "Eye height scale", "Растяжение глаз" },
        { "Eye tilt", "Наклон глаз" },
        { "Eyebrow spacing", "Расстояние между бровями" },
        { "Eyebrow height", "Высота бровей" },
        { "Eyebrow width", "Ширина бровей" },
        { "Eyebrow thickness", "Толщина бровей" },
        { "Eyebrow tilt", "Наклон бровей" },
        { "Nose height", "Высота носа" },
        { "Nose size", "Размер носа" },
        { "Mouth height", "Высота рта" },
        { "Mouth width", "Ширина рта" },
        { "Mouth thickness", "Толщина рта" },
        { "Moustache height", "Высота усов" },
        { "Moustache size", "Размер усов" },
        { "Beard height", "Высота бороды" },
        { "Beard size", "Размер бороды" },
        { "Glasses height", "Высота очков" },
        { "Glasses size", "Размер очков" },
        { "Mole across", "Родинка по горизонтали" },
        { "Mole down", "Родинка по вертикали" },
        { "Mole size", "Размер родинки" },

        // -------------------------------------------------- faces on the card
        { "faces on the sd card", "лица на sd-карте" },
        { "Save and load", "Сохранить и загрузить" },
        { "Save this face...", "Сохранить это лицо..." },
        { "Name this face", "Назовите это лицо" },
        { "Needs a name", "Нужно имя" },
        { "That name has nothing in it a file can be called.",
            "В этом имени нет ничего, чем можно назвать файл." },
        { "Saved", "Сохранено" },
        { "%s is in the export folder.", "%s лежит в папке экспорта." },
        { "Not saved", "Не сохранено" },
        { "Replace %s?", "Заменить %s?" },
        { "There is already a face saved under that name. Replacing it "
          "cannot be undone.",
            "Лицо с таким именем уже сохранено. Замену отменить нельзя." },
        { "Replace", "Заменить" },
        { "Delete %s?", "Удалить %s?" },
        { "It is removed from the SD card for good. Anyone you sent it "
          "to still has their copy.",
            "Он навсегда удаляется с SD-карты. У тех, кому вы его "
            "отправили, копия останется." },
        { "Delete", "Удалить" },
        { "Deleted", "Удалено" },
        { "%s is gone from the export folder.", "%s удалён из папки экспорта." },
        { "Not deleted", "Не удалено" },
        { "Cannot load that one", "Это не загрузить" },
        { "Not a face this version can read", "Это лицо не читается этой версией" },
        { "Nothing saved yet. Faces you save show up here, and so does "
          "anything you drop into the folder yourself.",
            "Пока ничего не сохранено. Сохранённые лица появятся здесь, "
            "как и всё, что вы сами положите в папку." },

        // --------------------------------------------------------- first run
        { "Leave it open.", "Оставьте открытым." },
        { "While this is open, your console swaps a small pass with the "
          "others that are open too - a face, a greeting, whatever you "
          "chose to carry. Who you meet is whoever is awake within the "
          "reach you set.",
            "Пока это открыто, ваша консоль обменивается небольшой "
            "карточкой с другими, которые тоже открыты - лицо, "
            "приветствие и то, что вы взяли с собой. Вы встречаете все "
            "активные консоли в заданной дальности." },
        { "Make your pass - a face, a greeting, one thing to trade",
            "Создайте карточку - лицо, приветствие и одну вещь для обмена" },
        { "Leave it open; it checks in on its own",
            "Оставьте открытым; оно подключается само" },
        { "Open the plaza and see who you crossed",
            "Откройте плазу и посмотрите, кого встретили" },
        { "A greeting, up to 60 characters", "Приветствие, до 60 символов" },
        { "pair this console", "сопряжение этой консоли" },
        { "A picture of this console's id. It lives on the SD card, is "
          "tied to nothing about the hardware, and you can throw it "
          "away.",
            "Картинка с идентификатором этой консоли. Она лежит на "
            "SD-карте, ни с чем в железе не связана, и её можно "
            "выбросить." },

        // ------------------------------------------- updates, and the app itself
        { "Version %s is out", "Вышла версия %s" },
        { "Settings -> About -> Check for updates to install it.",
            "Настройки -> О программе -> Проверить обновления, чтобы установить." },
        { "Puzzle art downloaded", "Картинки загружены" },
        { "Restart the app to see the pictures.",
            "Перезапустите приложение, чтобы увидеть картинки." },
        { "Update installed", "Обновление установлено" },
        { "Restart from Settings -> \"About\" to run version %s.",
            "Перезапустите через Настройки -> «О программе», чтобы "
            "запустить версию %s." },
        { "Up to date", "Актуально" },
        { "%s is the latest release.", "%s - последний выпуск." },
        { "Could not download puzzle art", "Не удалось загрузить картинки" },
        { "Could not check for updates", "Не удалось проверить обновления" },
        { "Install version %s?", "Установить версию %s?" },
        { "The new version is downloaded, checked, and only then "
          "written over this one. The copy you are running now is kept "
          "until the new one has been verified.",
            "Новая версия скачивается, проверяется и только затем "
            "записывается поверх этой. Текущая копия сохраняется, пока "
            "новая не проверена." },
        { "Install", "Установить" },
        { "Restart into version %s?", "Перезапуститься в версию %s?" },
        { "The app closes and opens again on the new version. Your "
          "passes and your collection are untouched.",
            "Приложение закроется и откроется в новой версии. Ваши "
            "карточки и коллекция не тронуты." },
        { "Restart", "Перезапустить" },
        { "%s passed you", "%s встретил вас" },
        { "%s and %zu others passed you", "%s и ещё %zu встретили вас" },
        { "%zu new passes", "%zu новых карточек" },
        { "a piece of %s", "кусочек «%s»" },
        { "%d pieces of %s", "%d кусочка «%s»" },
        { "one of them is carrying %s", "один из них несёт %s" },
        { "Open the plaza to see who.", "Откройте плазу, чтобы увидеть кого." },
        { "Keep everything", "Оставить всё" },

        // ------------------------------------------- settings, the dialogs
        { "Where are you? A district, a station, a shop",
            "Где вы? Район, станция, магазин" },
        { "Which city", "Какой город" },
        { "Plaza server address", "Адрес сервера плазы" },
        { "Clear any block the plaza still has?",
            "Снять блокировки, которые ещё держит плаза?" },
        { "Clear all %zu?", "Разблокировать все %zu?" },
        { "This console has none listed, but the plaza keeps its own "
          "copy and a restored backup can leave the two disagreeing. "
          "Nothing happens if it has none either.",
            "На этой консоли их нет, но плаза хранит свой список, а "
            "восстановленная копия может их развести. Если и у неё нет - "
            "ничего не произойдёт." },
        { "Every console you have blocked can cross you again, except "
          "any that blocked you as well. Their old passes are not "
          "coming back; only the block is lifted.",
            "Каждая заблокированная вами консоль сможет снова вас "
            "встречать, кроме тех, что заблокировали и вас. Старые "
            "карточки не вернутся; снимается только блокировка." },
        { "Clear them", "Разблокировать всех" },
        { "Block list cleared", "Список блокировок очищен" },
        { "This console has none left, and the plaza has been asked to "
          "drop the blocks it was holding for you.",
            "На этой консоли их больше нет, и плазу попросили снять "
            "блокировки, которые она держала для вас." },
        { "Delete every pass?", "Удалить все карточки?" },
        { "Every pass you have collected is removed from this console. "
          "Your own pass and your identity stay.",
            "Все собранные карточки удаляются с этой консоли. Ваша "
            "собственная карточка и личность остаются." },
        { "Delete them all", "Удалить всё" },
        { "Collection cleared", "Коллекция очищена" },
        { "The plaza is empty again.", "Плаза снова пуста." },
        { "Start over as someone new?", "Начать заново с новой личностью?" },
        { "This console gets a brand new id. Passes you already handed "
          "out can no longer be linked to you, and your collection is "
          "deleted.",
            "Эта консоль получает совершенно новый идентификатор. Уже "
            "выданные карточки больше нельзя связать с вами, а коллекция "
            "удаляется." },
        { "Start over", "Начать заново" },
        { "You are someone new", "Вы теперь другой человек" },
        { "Your code is now %s", "Ваш код теперь %s" },

        // ------------------------------------------- what the plaza is doing
        //
        // These come off the sync and update threads, and are read back on
        // screen in Settings and in Nearby. Whole sentences are translated;
        // the protocol diagnostics they sometimes carry - an HTTP status, a
        // libnx result code - stay as they are, because they exist to be
        // pasted into a bug report.
        { "Trading passes...", "Обмен карточками..." },
        { "Connected over LAN: matching by network area only.",
            "Подключено по локальной сети: сопоставление только по сетевой зоне." },
        { "Nobody else is awake here yet.",
            "Здесь пока нет других активных консолей." },
        { "No plaza server set yet. Settings > Plaza server.",
            "Сервер плазы не задан. Настройки > Сервер плазы." },
        { "Server sent something that was not JSON", "Сервер прислал не JSON" },
        { "Server said %ld on %s", "Сервер ответил %ld на %s" },
        { "Server said %ld on hello", "Сервер ответил %ld на hello" },
        { "Checking for updates", "Проверка обновлений" },
        { "Downloading", "Загрузка" },
        { "Unpacking", "Распаковка" },
        { "Installing", "Установка" },
        { "nx-plaza %s is the latest version.", "nx-plaza %s - последняя версия." },
        { "Release %s has no .nro to install.",
            "В выпуске %s нет .nro для установки." },
        { "Version %s is available.", "Доступна версия %s." },
        { "The download is version %s, not %s.", "Загружена версия %s, а не %s." },
        { "Version %s is installed. Restart to run it.",
            "Версия %s установлена. Перезапустите, чтобы запустить её." },
        { "%d puzzle pictures downloaded. Restart to see them.",
            "Загружено картинок пазлов: %d. Перезапустите, чтобы увидеть." },

        // ------------------------------------------- the last of the settings
        { "Asking GitHub for the latest release",
            "Спрашиваем у GitHub последнюю версию" },
        { "Press A to download and install it",
            "Нажмите A, чтобы скачать и установить" },
        { "Press A to restart into it", "Нажмите A, чтобы перезапустить" },
        { "You are on the latest release", "У вас последняя версия" },
        { "up to date", "актуально" },
        { "Looks at the releases on GitHub", "Смотрит выпуски на GitHub" },
        { "If the puzzles show numbered squares, get the pictures here "
          "and restart",
            "Если пазлы показывают нумерованные квадраты, скачайте "
            "картинки здесь и перезапустите" },
        { "failed", "ошибка" },
        { "Somebody", "Кто-то" },
        { "keep everything", "оставить всё" },
        { "switch tab", "сменить вкладку" },

        // ------------------------------------------------- the puzzle pictures
        { "Forest in the Rain", "Лес под дождём" },
        { "Mountain in the Fog", "Гора в тумане" },
        { "Mystical Swamp", "Мистическое болото" },
        { "Old Farm", "Старая усадьба" },
        { "Castle Blue", "Синий замок" },
        { "Beach at Dusk", "Пляж в сумерках" },

        // --------------------------------------------------- the card themes
        { "Amber lantern", "Янтарный фонарь" },
        { "Dusk market", "Сумеречный рынок" },
        { "Tidepool", "Приливная заводь" },
        { "Paper lantern", "Бумажный фонарь" },
        { "Rose market", "Розовый рынок" },
        { "Night express", "Ночной экспресс" },

        // ----------------------------------------------- the pass you start with
        { "Traveller", "Путник" },
        { "Just passing through.", "Просто прохожу мимо." },

        // ------------------------------------------- what the plaza is saying
        { "Looking around...", "Смотрим вокруг..." },
        { "Publishing your pass...", "Публикуем вашу карточку..." },
        { "Blocking a console...", "Блокируем консоль..." },
        { "Unblocking a console...", "Разблокируем консоль..." },
        { "Clearing the block list...", "Очищаем список блокировок..." },
        { "Asking the server to forget us...", "Просим сервер забыть нас..." },
        { "Daily crossing limit reached. Back tomorrow.",
            "Дневной предел встреч достигнут. До завтра." },
        { "Networking is unavailable.", "Сеть недоступна." },
        { "No internet connection.", "Нет подключения к интернету." },

        // ------------------------------------------- when an update goes wrong
        { "This console would not start the update worker.",
            "Эта консоль не смогла запустить процесс обновления." },
        { "The release list could not be read.",
            "Не удалось прочитать список выпусков." },
        { "The release list carried no version.",
            "В списке выпусков не оказалось версии." },
        { "The download did not finish: %s", "Загрузка не завершилась: %s" },
        { "The downloaded archive held no nx-plaza build.",
            "В загруженном архиве не оказалось сборки nx-plaza." },
        { "The downloaded file is not a valid nx-plaza build.",
            "Загруженный файл - не действительная сборка nx-plaza." },
        { "This build does not know its own path, so it cannot replace itself.",
            "Эта сборка не знает своего пути, поэтому не может заменить себя." },
        { "The current version could not be backed up.",
            "Не удалось создать копию текущей версии." },
        { "The update could not be written over the current one - %s",
            "Не удалось записать обновление поверх текущей версии - %s" },
        { "The installed update did not verify, so it was rolled back.",
            "Установленное обновление не прошло проверку и было откатано." },
        { "That release publishes no puzzle art.",
            "В этом выпуске нет картинок пазлов." },
        { "That release's archive holds no puzzle art.",
            "В архиве этого выпуска нет картинок пазлов." },
        { "The puzzle art that arrived was not readable.",
            "Полученные картинки не читаются." },
        { "The folder for the puzzle art could not be made.",
            "Не удалось создать папку для картинок пазлов." },
        { "The puzzle art could not be written - %s",
            "Не удалось записать картинки пазлов - %s" },

        // ------------------------------------------ the settings sections
        //
        // The eight names down the left of the screen, and the pills on the
        // rows that offer a choice.
        { "Privacy", "Приватность" },
        { "Exchange", "Обмен" },
        { "Appearance", "Оформление" },
        { "Languages", "Языки" },
        { "This console", "Эта консоль" },
        { "Data", "Данные" },
        { "About", "О программе" },
        { "Off", "Выкл." },
        { "District", "Район" },
        { "City", "Город" },
        { "Same network", "Та же сеть" },
        { "Anywhere", "Везде" },
        { "Light", "Светлая" },
        { "Dark", "Тёмная" },

        // -------------------------------------- when the SD card says no
        { "Could not make the export folder on the SD card.",
            "Не удалось создать папку экспорта на SD-карте." },
        { "Could not write to the SD card.", "Не удалось записать на SD-карту." },
        { "That file could not be read.", "Этот файл не удалось прочитать." },
        { "That is not a face this app saved.",
            "Это лицо сохранено не этим приложением." },
        { "That face was saved by a different version of the app.",
            "Это лицо сохранила другая версия приложения." },
        { "Could not delete that file from the SD card.",
            "Не удалось удалить этот файл с SD-карты." },
        { "could not make the backup folder",
            "не удалось создать папку резервной копии" },
        { "could not copy %s", "не удалось скопировать %s" },
        { "there was nothing to back up", "копировать было нечего" },

        // ------------------------------------------------------- your plaza
        //
        // The stats page off the pass. Its captions sit under a number, so
        // they are fragments rather than sentences: "croisements en tout"
        // under 214, the way a caption reads on a card.
        { "your record", "ваша статистика" },
        { "Everything so far", "Итоги на сегодня" },
        { "crossings in total", "встреч всего" },
        { "the one you cross most", "кого встречаете чаще всех" },
        { "places", "мест" },
        { "your oldest card", "самая старая карточка" },
        { "starred", "в избранном" },
        { "days you have crossed somebody", "дни, когда вы кого-то встретили" },
        { "%u days", "%u дн." },
        { "%u months", "%u мес." },
        { "%u years", "%u г." },
        { "sent something back", "ответов отправлено" },
        { "still unopened", "ещё не открыто" },
        { "pieces", "кусочков" },
        { "pictures finished", "картин собрано" },
        { "people gave you a piece", "человек дали вам кусочек" },
        { "coins", "монеты" },
        { "earned by turning up", "получено за появления" },
        { "spent", "потрачено" },
        { "won at the games", "выиграно в играх" },
        { "the longest run", "самый долгий забег" },
        { "the tallest tower", "самая высокая башня" },
        { "duels in a row", "дуэлей подряд" },

        // --------------------------------------------------------- the quest
        //
        // The tower off the games shelf. "Étage" throughout for a floor,
        // never "niveau": a level is a thing a game has and a floor is a
        // thing a building has. The party is "il" in the singular - French
        // has no neutral singular that reads as anything but a construction,
        // and a pass is a card rather than a person's own gender.
        //
        // The class names are one word each because they sit in a stat block
        // eighteen pixels high: Lame, Garde, Éclat, Soigneur. Nothing longer
        // fits, and a role in a party game is a noun anyway.
        { "The quest", "Восхождение" },
        { "A tower with no top, a shadow on every floor, and a party "
          "made of the people you have crossed.\nEvery shadow can leave "
          "something behind. Gear them up, pick who goes, and the fight "
          "runs itself.",
            "Башня без вершины, на каждом этаже тень, и отряд из тех, "
            "кого вы встретили.\nКаждая тень может что-нибудь оставить. "
            "Снарядите их, выберите, кто идёт, - бой идёт сам." },
        { "Floor %d", "Этаж %d" },
        { "best floor %u", "лучший этаж %u" },
        { "%d of %d places", "%d из %d мест" },
        { "Nobody has crossed you yet - you climb alone.",
            "Вас пока никто не встретил - вы поднимаетесь один." },

        { "Guard", "Страж" },
        { "Blade", "Клинок" },
        { "Spark", "Искра" },
        { "Mender", "Лекарь" },

        { "%s stands in front", "%s встаёт впереди" },
        { "%s falls", "%s падает" },
        { "The party falls", "Отряд пал" },
        { "nothing this time", "в этот раз ничего" },
        { "next floor", "следующий этаж" },
        { "pick again", "выбрать заново" },
        { "Floor %d is yours", "Этаж %d ваш" },

        { "You came back down", "Вы спустились обратно" },
        { "%d floors, and %u coins for the ones you had not reached.",
            "%d этажей и %u монет за те, до которых вы ещё не доходили." },
        { "Not one floor. Cross a few more people and bring them along.",
            "Ни одного этажа. Встретьте ещё нескольких и возьмите их с собой." },
        { "bring along", "взять с собой" },
        { "leave behind", "оставить" },
        { "climb", "подняться" },
        { "stop", "остановиться" },
        { "stop here", "остановиться здесь" },

        { "gear", "снаряжение" },
        { "what they carry", "что они несут" },
        { "in the bag", "в сумке" },
        { "the bag", "сумка" },
        { "everything", "всё" },
        { "from floor %u", "с этажа %u" },
        { "worn by %s", "носит %s" },
        { "Somebody who has gone", "Тот, кого больше нет" },
        { "Nothing here yet. The tower is where it comes from.",
            "Пока ничего. Всё это даёт башня." },
        { "Somebody is wearing that", "Это кто-то носит" },
        { "Take it off in the gear screen first.",
            "Сначала снимите это на экране снаряжения." },
        { "%zu of %zu in the bag", "%zu из %zu в сумке" },
        { "Nobody to dress", "Некого снаряжать" },
        { "Nothing here that would fit.", "Здесь нет ничего подходящего." },
        { "nothing on this peg", "здесь пусто" },
        { "worn", "надето" },
        { "wear it", "надеть" },
        { "what would fit", "что сюда подойдёт" },
        { "take it off", "снять" },
        { "back to the pegs", "назад к слотам" },
        { "throw away", "выбросить" },
        { "somebody else", "кто-то другой" },
        { "Throw away the %s?", "Выбросить %s?" },
        { "A %s piece from floor %u. It does not come back.",
            "%s вещь с этажа %u. Она не вернётся." },
        { "Throw it away", "Выбросить" },
        { "Your bag is full", "Сумка полна" },
        { "Nothing in it was worse than what fell, so what fell stayed "
          "on the floor.",
            "Ничего в ней не было хуже того, что выпало, так что оно "
            "осталось на полу." },
        { "%s was thrown out to make room.", "%s выброшено, чтобы освободить место." },
        { "clear out", "разобрать" },
        { "Nothing to clear out", "Разбирать нечего" },
        { "Everything spare is better than something being worn, or "
          "sits on a peg with nothing on it.",
            "Всё лишнее лучше того, что надето, или ждёт пустого места." },
        { "Throw away %zu pieces?", "Выбросить %zu вещей?" },
        { "Everything in the bag that is worse than what %s has on. "
          "Nothing being worn is touched.",
            "Всё в сумке, что хуже надетого на %s. Надетое не трогаем." },
        { "Throw them away", "Выбросить всё" },

        { "every floor pays this week", "на этой неделе платит каждый этаж" },
        { "floors up to %u have paid this week",
            "этажи до %u на этой неделе уже заплатили" },
        { "the week turns when the plaza is next reached",
            "неделя сменится при следующей связи с плазой" },
        { "One %s piece came back with you.", "Одна %s вещь вернулась с вами." },
        { "%d pieces came back with you, the best of them %s.",
            "%d вещей вернулось с вами, лучшая - %s." },

        { "weapon", "оружие" },
        { "armour", "броня" },
        { "ring", "кольцо" },
        { "accessory", "аксессуар" },

        { "common", "обычное" },
        { "uncommon", "необычное" },
        { "rare", "редкое" },
        { "epic", "эпическое" },
        { "legendary", "легендарное" },
        { "godlike", "божественное" },

        { "Baton", "Дубина" },
        { "Cleaver", "Тесак" },
        { "Lance", "Копьё" },
        { "Hammer", "Молот" },
        { "Jerkin", "Куртка" },
        { "Plate", "Панцирь" },
        { "Cloak", "Плащ" },
        { "Carapace", "Хитин" },
        { "Band", "Обруч" },
        { "Signet", "Печатка" },
        { "Circlet", "Венец" },
        { "Seal", "Печать" },
        { "Charm", "Оберег" },
        { "Talisman", "Талисман" },
        { "Pendant", "Кулон" },
        { "Feather", "Перо" },

        // ------------------------------------------------- the blessings
        //
        // Drawn three at a time during a climb and gone when it ends.
        // Each is a name and one line saying what it does, and the line
        // sits in a card 420 pixels wide over four lines at most - so
        // they are written short in every language, and a fraction is
        // written as a word because "20 %%" in a sentence reads like a
        // statistic rather than like a blessing.
        { "Whetstone", "Точило" },
        { "The party hits a fifth harder.", "Отряд бьёт на пятую часть сильнее." },
        { "Ironclad", "Броня" },
        { "The party takes a fifth less.", "Отряд получает на пятую часть меньше." },
        { "Hale", "Крепость" },
        { "A fifth more health, and it fills now.",
            "На пятую часть больше здоровья, и оно сразу полное." },
        { "Fleet", "Резвость" },
        { "Everybody is three quicker.", "Все на три быстрее." },
        { "Reckless", "Безрассудство" },
        { "A third harder, and a quarter softer.",
            "На треть сильнее и на четверть уязвимее." },
        { "Bulwark", "Оплот" },
        { "A third tougher, and a fifth weaker.",
            "На треть крепче и на пятую часть слабее." },
        { "Keen edge", "Острая грань" },
        { "Telling blows land three times as often.",
            "Решающие удары случаются втрое чаще." },
        { "Second wind", "Второе дыхание" },
        { "The first to fall gets up once, at a third.",
            "Первый упавший один раз встаёт, с третью здоровья." },
        { "Rally", "Сплочение" },
        { "Each one who falls makes the rest hit a fifth harder.",
            "Каждый упавший заставляет остальных бить на пятую часть сильнее." },
        { "Momentum", "Разгон" },
        { "The party hits a twentieth harder for every floor from here.",
            "Отряд бьёт на двадцатую часть сильнее за каждый этаж отсюда." },
        { "Last stand", "Последний рубеж" },
        { "Alone, the last one standing hits twice as hard.",
            "В одиночку последний стоящий бьёт вдвое сильнее." },
        { "Deep breath", "Глубокий вдох" },
        { "Twice as much wind back between floors.",
            "Вдвое больше дыхания между этажами." },
        { "Battle rhythm", "Ритм боя" },
        { "Everybody starts each floor with their wind full.",
            "Все начинают этаж с полным дыханием." },
        { "Cheap tricks", "Дешёвые приёмы" },
        { "Specials cost four instead of six.",
            "Особые приёмы стоят четыре вместо шести." },
        { "Long watch", "Долгая стража" },
        { "Standing in front covers the sweep as well.",
            "Тот, кто впереди, прикрывает и от размаха." },
        { "Mending hands", "Целящие руки" },
        { "The Mender heals half again, and steps in sooner.",
            "Лекарь лечит в полтора раза больше и вступает раньше." },
        { "Bright spark", "Яркая искра" },
        { "The Spark takes twice as much off the shadow's arm.",
            "Искра отнимает у тени вдвое больше руки." },
        { "Scavenger", "Собиратель" },
        { "The shadow leaves something four times in five.",
            "Тень оставляет что-нибудь четыре раза из пяти." },
        { "The stair offers you something", "Лестница что-то вам предлагает" },
        { "It lasts as long as the climb does.",
            "Это держится, пока длится восхождение." },
        { "take it", "взять" },
        { "blessings", "благословения" },
        { "keep going on its own", "идти дальше само" },
        { "stop on each floor", "останавливаться на каждом этаже" },
        { "%s gets back up", "%s снова встаёт" },

        // ---------------------------------------------- the whetstone
        //
        // A shop item spent on a piece of the quest's gear. "Pierre à
        // aiguiser" in full where there is room and "pierre" where
        // there is not, because the noun is feminine and the short
        // form agrees the same way.
        { "A whetstone", "Точильный камень" },
        { "One whetstone", "Точильный камень" },
        { "No whetstones", "Точильных камней нет" },
        { "Use a whetstone", "Использовать камень" },
        { "%u left", "осталось %u" },
        { "as it stands", "как есть" },
        { "whatever it becomes", "во что превратится" },
        { "before", "было" },
        { "after", "стало" },
        { "It came out better.", "Бросок вышел лучше." },
        { "It came out worse.", "Бросок вышел хуже." },
        { "It came out much the same.", "Бросок вышел примерно тем же." },

        { "roll it again", "перебросить" },
        { "They are %u coins in the shop.", "В лавке они стоят %u монет." },
        { "%u in the bag. Use one on a piece of gear to roll it again.",
            "%u в сумке. Используйте один на вещи снаряжения, чтобы перебросить её." },
        { "It rolls one piece of gear again, keeping its rank.",
            "Он перебрасывает вещь снаряжения, сохраняя её ранг." },
        { "Rolls one piece of the quest's gear again, keeping its rank. You have %u.",
            "Перебрасывает вещь снаряжения восхождения, сохраняя ранг. У вас %u." },
        { "Rolls one piece of the quest's gear again. Same rank, new "
          "numbers - a badly rolled epic gets another go at being a "
          "good one.",
            "Перебрасывает вещь снаряжения восхождения. Тот же ранг, "
            "новые числа - неудачная эпическая получит ещё один шанс." },

        // ------------------------------------------------- the same in French
        //
        // Listed on purpose rather than left out, so the scanner can tell a
        // word that needs no translation from one nobody has looked at yet.
        // tr() drops these rows: falling back to the English is the same
        // answer, and cheaper.
        { "Plaza", "Плаза" },
        { "Collection", "Коллекция" },
        { "collection", "коллекция" },
        { "Puzzles", "Пазлы" },
        { "puzzles", "пазлы" },
        { "plaza dash", "plaza dash" },
        { "sections", "разделы" },
        { "m", "м" },
        { "-", "-" },
        { "%d", "%d" },
        { "Notifications", "Уведомления" },
        { "Console", "Консоль" },
        { "nx-plaza ", "nx-plaza " },
        { "(none)", "(нет)" },
        { "NX Plaza - Online StreetPass | ", "NX Plaza - Online StreetPass | " },
        { "https://github.com/Insektaure/NX-Plaza",
            "https://github.com/Insektaure/NX-Plaza" },
    };

} // namespace

Catalog russianCatalog()
{
    return Catalog { kEntries, sizeof(kEntries) / sizeof(kEntries[0]) };
}

} // namespace nxp
