#include "core/i18n.h"

// Dutch.
//
// Generated by tools/gen_lang_tables.py from tools/lang_data.py, in the shape
// of lang_fr.cpp - same sections, same order - so any two languages can be
// read side by side. Edit the table, not this file.
//
// Left column: the English exactly as it is written in the code, which is the
// key. Reword a line in a scene and the row here stops matching in silence,
// which is what `tools/i18n_scan.py --lang nl` is for. A string this
// language has not been given yet is simply absent, and comes out in English.

namespace nxp {
namespace {

    const Translation kEntries[] = {
        // ------------------------------------------------------------- tabs
        { "Nearby", "Dichtbij" },
        { "The Square", "Het plein" },
        { "Games", "Spellen" },
        { "The shop", "De winkel" },
        { "Trophies", "Trofeeën" },
        { "Your pass", "Jouw kaart" },
        { "Settings", "Instellingen" },

        // ------------------------------------------------- the hint strip
        { "again", "opnieuw" },
        { "back", "terug" },
        { "block", "blokkeren" },
        { "cancel", "annuleren" },
        { "change", "wijzigen" },
        { "choose", "kiezen" },
        { "close", "sluiten" },
        { "done", "klaar" },
        { "fill the screen", "volledig scherm" },
        { "give up", "opgeven" },
        { "jump - hold to go higher", "springen - houd vast voor hoger" },
        { "jump ten", "tien verder" },
        { "left and right to change", "links en rechts om te wijzigen" },
        { "look now", "nu zoeken" },
        { "mark read", "gelezen" },
        { "next pass", "volgende kaart" },
        { "open", "openen" },
        { "open section", "sectie openen" },
        { "play", "spelen" },
        { "roll", "gooien" },
        { "roll again", "opnieuw gooien" },
        { "run", "rennen" },
        { "run again", "opnieuw rennen" },
        { "save / load", "opslaan / laden" },
        { "save face", "gezicht opslaan" },
        { "shuffle", "willekeurig" },
        { "shuffle face", "gezicht willekeurig" },
        { "spin", "draaien" },
        { "start", "starten" },

        // --------------------------------------------------------- buttons
        { "Make my pass", "Kaart maken" },
        { "Not now", "Later" },
        { "Run", "Rennen" },
        { "Run again", "Opnieuw rennen" },
        { "Start stacking", "Beginnen met stapelen" },
        { "Stack again", "Opnieuw stapelen" },

        // ------------------------------------------- eyebrows and captions
        { "games", "spellen" },
        { "trophies", "trofeeën" },
        { "the shop", "de winkel" },
        { "the square", "het plein" },
        { "the mii race", "de Mii-race" },
        { "the mii tower", "de Mii-toren" },
        { "the dice duel", "het dobbelduel" },
        { "what it pays", "wat het uitbetaalt" },
        { "your prediction", "jouw voorspelling" },
        { "your pairing code", "jouw koppelcode" },
        { "people met", "personen ontmoet" },
        { "times your pass was sent", "keer is jouw kaart verstuurd" },
        { "floors", "verdiepingen" },
        { "best %u %s", "record %u %s" },

        // ------------------------------------------------------ the games
        { "Something to do", "Iets te doen" },
        { "Played with the faces and names in your collection, so the "
          "more people you have crossed, the more there is here.",
            "Gespeeld met de gezichten en namen uit je collectie: hoe "
            "meer mensen je kruiste, hoe meer er hier is." },

        { "The Mii race", "De Mii-race" },
        { "Three of the people you have crossed, against your own Mii, "
          "and nobody is faster than anybody.\nWatch for nothing, bet a "
          "coin for three back, or call first and second for eleven.",
            "Drie mensen die je kruiste, tegen jouw eigen Mii, en niemand "
            "is sneller dan een ander.\nGratis kijken, één munt voor drie "
            "terug, of eerste en tweede voor elf." },

        { "The dice duel", "Het dobbelduel" },
        { "One roll each against somebody you have crossed, and the "
          "highest takes it.\nRoll for nothing, or bet two coins for "
          "three back - and a draw hands your two back.",
            "Eén worp elk tegen iemand die je kruiste, en de hoogste "
            "wint.\nGratis gooien, of twee munten voor drie terug - bij "
            "gelijkspel krijg je je twee terug." },

        { "The lantern wheel", "Het lantaarnrad" },
        { "Twelve lanterns and a needle, and two of them are a puzzle "
          "piece.\nWatch it for nothing, or ten coins a spin - every "
          "lantern pays something, and one in six is a piece.",
            "Twaalf lantaarns en een naald, en twee ervan zijn een "
            "puzzelstukje.\nGratis kijken, of tien munten per draai - "
            "elke lantaarn betaalt iets, en één op zes is een stukje." },

        { "The bandit", "De bandiet" },
        { "Three reels, and two machines: three symbols that pay small "
          "and often, or five that pay rarely and big.\nA coin a spin, "
          "or spin for nothing - two bells hand the coin back, and the "
          "board on the wall lists every line it pays.",
            "Drie rollen en twee machines: drie symbolen die klein en "
            "vaak betalen, of vijf die zelden en groot betalen.\nEén munt "
            "per draai, of gratis - twee bellen geven de munt terug, en "
            "het bord aan de muur toont elke combinatie." },

        { "The Mii tower", "De Mii-toren" },
        { "Stack the people you have crossed, one drop at a time.\nMiss "
          "the shoulders below and they fall; drift too far from the "
          "base and the lot goes over.",
            "Stapel de mensen die je kruiste, één per keer.\nMis de "
            "schouders eronder en ze vallen; wijk te ver van de basis af "
            "en alles gaat om." },

        { "Plaza dash", "Plaza Dash" },
        { "Your own Mii running through the plaza, jumping what the "
          "market leaves in the way.\nIt gets quicker. Nothing staked, "
          "nothing won - only how far you got.",
            "Jouw eigen Mii rent door de plaza en springt over wat de "
            "markt in de weg laat.\nHet wordt sneller. Niets ingezet, "
            "niets gewonnen - alleen hoe ver je kwam." },

        // ------------------------------------------------ settings: sections
        { "%s never sends your name or an exact position. You choose "
          "how much of a pass leaves the console.",
            "%s stuurt nooit je naam of een precieze positie. Jij kiest "
            "hoeveel van een kaart de console verlaat." },
        { "How passes find their way to you.", "Hoe kaarten hun weg naar je vinden." },
        { "Nothing interrupts a game. The plaza waits.",
            "Niets onderbreekt een spel. De plaza wacht." },
        { "The app opens in daylight. Dark is for a dim room, or match "
          "whatever the console is set to.",
            "De app opent in licht. Donker is voor een schemerige kamer, "
            "of volg de console." },
        { "The app is written in English and says what it has been "
          "taught to say in anything else. Whatever a language is "
          "missing stays in English.",
            "De app is in het Engels geschreven en zegt in andere talen "
            "wat hem is geleerd. Wat een taal mist blijft Engels." },
        { "Where your passes go, and how another console recognises this one.",
            "Waar jouw kaarten heen gaan, en hoe een andere console deze herkent." },
        { "Everything the app keeps lives on the SD card, and all of it can go.",
            "Alles wat de app bewaart staat op de SD-kaart, en alles kan weg." },
        { "What this build of %s is, who made it, and where it came from.",
            "Wat deze versie van %s is, wie hem maakte en waar hij vandaan komt." },

        // ---------------------------------------------------- settings: rows
        { "English - what the app is written in",
            "Engels - de taal waarin de app is geschreven" },
        { "Share where we crossed", "Deel waar we elkaar kruisten" },
        { "District only - never a street or a venue you did not name",
            "Alleen de wijk - nooit een straat of plek die je niet noemde" },
        { "District label", "Naam van de wijk" },
        { "e.g. Namba Station", "bv. Namba Station" },
        { "City label", "Naam van de stad" },
        { "used when sharing is set to City",
            "wordt gebruikt als delen op Stad staat" },
        { "Show what I am playing", "Laat zien wat ik speel" },
        { "The title, your hours in it, and how many games you have. "
          "Hidden titles stay hidden, always",
            "Het spel, jouw uren erin en hoeveel spellen je hebt. "
            "Verborgen spellen blijven verborgen, altijd" },
        { "Exchange passes automatically", "Kaarten automatisch uitwisselen" },
        { "Trades happen while the app is open",
            "Uitwisselen gebeurt zolang de app open is" },
        { "How far a crossing reaches", "Bereik van een ontmoeting" },
        { "Same network is the closest thing to walking past someone",
            "Zelfde netwerk komt het dichtst bij elkaar echt tegenkomen" },
        { "Crossings per day", "Ontmoetingen per dag" },
        { "Tell me when passes arrive", "Waarschuw me bij nieuwe kaarten" },
        { "A card in the corner, never an interruption",
            "Een kaartje in de hoek, nooit een onderbreking" },
        { "Theme", "Thema" },
        { "Hold the scenery still", "Houd de achtergrond stil" },
        { "On, for anybody the Plaza Dash minigame makes queasy: the "
          "background stops moving and only what you have to dodge "
          "does. Turn it off for the full parallax",
            "Aan, voor wie misselijk wordt van het minispel Plaza Dash: "
            "de achtergrond staat stil en alleen wat je moet ontwijken "
            "beweegt. Zet uit voor volle parallax" },
        { "Plaza server", "Plaza-server" },
        { "Wi-Fi match token", "Wifi-token" },
        { "Check in now", "Nu aanmelden" },
        { "Blocked consoles", "Geblokkeerde consoles" },
        { "Clear the whole list", "Hele lijst wissen" },
        { "unblock", "vrijgeven" },
        { "none", "geen" },
        { "Write a log file", "Logbestand schrijven" },
        { "Copy everything to a backup folder", "Alles naar een back-upmap kopiëren" },
        { "Your identity, your pass and your collection, into backup/ on this card",
            "Jouw identiteit, kaart en collectie, naar backup/ op deze kaart" },
        { "Download puzzle art", "Puzzelafbeeldingen downloaden" },
        { "Delete every pass you have collected",
            "Alle verzamelde kaarten verwijderen" },
        { "This cannot be undone", "Dit kan niet worden teruggedraaid" },
        { "Start over as someone new", "Opnieuw beginnen als iemand anders" },
        { "New id, new pass; everything you handed out goes unlinkable",
            "Nieuwe id, nieuwe kaart; alles wat je uitdeelde is niet meer "
            "te koppelen" },
        { "Check for updates", "Naar updates zoeken" },
        { "Check on every launch", "Bij elke start controleren" },
        { "One request when the app opens; it never installs on its own",
            "Één verzoek bij het openen; installeert nooit zelf" },
        { "Developed by Insektaure", "Ontwikkeld door Insektaure" },
        { "Find us on GitHub !", "Vind ons op GitHub !" },
        { "This console's id", "Id van deze console" },

        // -------------------------------------------------- settings: toasts
        { "Not connected to the plaza", "Geen verbinding met de plaza" },
        { "This one needs the server. The dot by the tabs turns green "
          "when it can be reached.",
            "Dit vereist de server. Het stipje bij de tabs wordt groen "
            "als die bereikbaar is." },
        { "Busy with another download", "Er loopt al een download" },
        { "Wait for the update in About to finish, then try again.",
            "Wacht tot de update onder Over klaar is en probeer het opnieuw." },
        { "Downloading puzzle art", "Puzzelafbeeldingen downloaden" },
        { "This row shows how it is going.", "Deze regel laat zien hoe het gaat." },
        { "Could not back up", "Back-up mislukt" },
        { "Backed up to %s", "Geback-upt naar %s" },
        { "It is on the same card. Copy the backup folder to a computer "
          "to be safe from losing the card itself.",
            "Het staat op dezelfde kaart. Kopieer de back-upmap naar een "
            "computer om niet van de kaart af te hangen." },
        { "Checking in", "Aanmelden" },
        { "Unblocked %s", "%s vrijgegeven" },
        { "They can cross you again, unless they blocked you as well.",
            "Ze kunnen je weer kruisen, tenzij zij jou ook blokkeerden." },

        // ---------------------------------------------------- the Mii race
        { "Four runners, one line", "Vier lopers, één finish" },
        { "Nobody is faster than anybody. Nothing you do changes that.",
            "Niemand is sneller dan een ander. Niets wat je doet verandert dat." },
        { "Race for free", "Gratis racen" },
        { "Bet 1 coin - your Mii to win", "Zet 1 munt - jouw Mii wint" },
        { "Predict 1st and 2nd", "Voorspel 1e en 2e" },
        { "Just to watch.", "Alleen kijken." },
        { "%u back if it comes in.", "%u terug als het lukt." },
        { "For free, or bet 1 coin for %u back.",
            "Gratis, of zet 1 munt voor %u terug." },
        { "Nothing to bet with.", "Niets om mee te wedden." },
        { "Nothing to bet", "Niets om te wedden" },
        { "Ten coins arrive on each new day you open the app.",
            "Er komen tien munten op elke nieuwe dag dat je de app opent." },
        { "Who comes first?", "Wie wordt eerste?" },
        { "And who comes second?", "En wie wordt tweede?" },
        { "That is your call", "Dat is jouw voorspelling" },
        { "First and second, in order. Eleven for a coin if you call "
          "it, or watch for nothing.",
            "Eerste en tweede, in die volgorde. Elf voor een munt als je "
            "het goed hebt, of gratis kijken." },
        { "%s to win. Now who is behind them?", "%s wint. En wie erachter?" },
        { "%s first, %s second.", "%s eerste, %s tweede." },
        { "race", "racen" },
        { "Go", "Start" },
        { "You are in front", "Jij loopt voorop" },
        { "%s is in front", "%s loopt voorop" },
        { "predict again", "opnieuw voorspellen" },
        { "race again", "opnieuw racen" },
        { "Called it", "Goed voorspeld" },
        { "You won", "Jij hebt gewonnen" },
        { "%s won", "%s heeft gewonnen" },
        { "Nobody", "Niemand" },
        { "You said %s then %s - they came %s and %s.",
            "Je zei %s en dan %s - ze werden %s en %s." },
        { "The bet paid %u - %u coins to spend.",
            "De inzet betaalt %u - %u munten over." },
        { "The bet cost you a coin. %u left.", "De inzet kostte een munt. %u over." },
        { "Nothing bet, but right is right.", "Niets ingezet, maar goed is goed." },
        { "Nothing bet, nothing lost.", "Niets ingezet, niets verloren." },
        { "Predict again", "Opnieuw voorspellen" },
        { "Race again", "Opnieuw racen" },
        { "Bet %u coin - %u back", "Zet %u munt - %u terug" },
        { "1st", "1e" },
        { "2nd", "2e" },
        { "3rd", "3e" },
        { "4th", "4e" },

        // ---------------------------------------------------- the dice duel
        { "One roll each", "Eén worp elk" },
        { "Highest roll takes it. A draw hands your %u back.",
            "De hoogste worp wint. Bij gelijkspel krijg je je %u terug." },
        { "Roll for free", "Gratis gooien" },
        { "%u coins to play", "%u munten om te spelen" },
        { "Ten arrive on each new day you open the app.",
            "Er komen tien op elke nieuwe dag dat je de app opent." },
        { "%d all - nobody takes it", "%d gelijk - niemand wint" },
        { "%d beats %d", "%d verslaat %d" },
        { "%d loses to %d", "%d verliest van %d" },
        { "Your %u came back. %u to spend.", "Jouw %u zijn terug. %u over." },
        { "The bet cost you %u. %u left.", "De inzet kostte %u. %u over." },
        { "Nothing bet, and nothing decided.", "Niets ingezet, en niets beslist." },
        { "Nothing bet, but a win is a win.", "Niets ingezet, maar winst is winst." },
        { "%u in a row", "%u op een rij" },
        { "Roll again", "Opnieuw gooien" },
        { "Bet %u coins - %u back", "Zet %u munten - %u terug" },

        // ------------------------------------------------- the lantern wheel
        { "%u coins for a spin", "%u munten voor een draai" },
        { "Watch it for nothing, or put %u coins on it. Every lantern "
          "pays something and %d of the %d are a puzzle piece. You have "
          "%u.",
            "Gratis kijken, of zet %u munten in. Elke lantaarn betaalt "
            "iets en %d van de %d zijn een puzzelstukje. Je hebt %u." },
        { "Spin for nothing", "Gratis draaien" },
        { "A piece of %s", "Een stukje van %s" },
        { "The piece lantern", "De puzzelstuk-lantaarn" },
        { "The %u lantern", "De %u-lantaarn" },
        { "Piece %d, and the panel will say the wheel brought it. %u coins left.",
            "Stukje %d, en het paneel zegt dat het rad het bracht. %u munten over." },
        { "%u coins to spend. A spin costs %u.", "%u munten over. Een draai kost %u." },
        { "Nothing was on it - that one only pays when you have staked.",
            "Er stond niets op - die betaalt alleen met inzet." },
        { "Nothing staked, so nothing won. It would have paid %u.",
            "Niets ingezet, dus niets gewonnen. Het had %u betaald." },
        { "Spin again", "Opnieuw draaien" },
        { "Bet %u coins", "Zet %u munten" },

        // ---------------------------------------------------- the bandit
        { "A coin a spin", "Eén munt per draai" },
        { "A coin a spin, and %u to spend. X changes machines.",
            "Eén munt per draai, en %u over. X wisselt van machine." },
        { "THREE SYMBOLS", "DRIE SYMBOLEN" },
        { "FIVE SYMBOLS", "VIJF SYMBOLEN" },
        { "three symbols", "drie symbolen" },
        { "five symbols", "vijf symbolen" },
        { "Spin for free", "Gratis draaien" },
        { "Bet %u coin", "Zet %u munt" },
        { "Two sevens", "Twee zevens" },
        { "Two bells", "Twee bellen" },
        { "Two the same", "Twee gelijke" },
        { "Any two the same", "Twee willekeurige gelijke" },
        { "Nothing", "Niets" },
        { "Three %s", "Drie %s" },
        { "suns", "zonnen" },
        { "moons", "manen" },
        { "bells", "bellen" },
        { "sevens", "zevens" },
        { "bars", "balken" },
        { "a line about every 3 spins", "ongeveer elke 3 draaien iets" },
        { "a line about every 4 spins", "ongeveer elke 4 draaien iets" },
        { "%u back, and %u to spend.", "%u terug, en %u over." },
        { "That coin is gone. %u left.", "Die munt is weg. %u over." },
        { "Nothing staked, so nothing won - it would have paid %u.",
            "Niets ingezet, dus niets gewonnen - het had %u betaald." },
        { "Nothing staked, and nothing to stake it on.",
            "Niets ingezet, en niets om in te zetten." },

        // ---------------------------------------------------- the Mii tower
        { "Stack them up", "Stapel ze op" },
        { "A drops whoever is swinging. Miss the shoulders below and "
          "they fall; drift too far from the base and the lot goes "
          "over.",
            "A laat vallen wie er zwaait. Mis de schouders eronder en hij "
            "valt; wijk te ver van de basis af en alles gaat om." },
        { "drop", "laten vallen" },
        { "lean", "helling" },
        { "%d floors", "%d verdiepingen" },
        { "best %u floors", "record %u verdiepingen" },
        { "floors, best %u", "verdiepingen, record %u" },
        { "%s had nothing to stand on.", "%s had niets om op te staan." },
        { "It went over with %s on top.", "Hij viel om met %s bovenop." },

        // ---------------------------------------------------- plaza dash
        { "Jump the market", "Spring over de markt" },
        { "A to jump, and hold it to jump higher. It gets quicker until "
          "you hit something.",
            "A om te springen, houd vast om hoger te springen. Het wordt "
            "sneller tot je iets raakt." },
        { "%u m", "%u m" },
        { "best %u m", "record %u m" },
        { "Best is %u m.", "Het record is %u m." },
        { "A new best.", "Nieuw record." },
        { "a new best", "nieuw record" },

        // ------------------------------------------- shared by the games
        { "You", "Jij" },
        { "A stranger", "Een onbekende" },

        // ---------------------------------------------------- the trophies
        { "show %s", "%s tonen" },
        { "earned only", "alleen behaalde" },
        { "still to earn", "nog te behalen" },
        { "all of them", "alle" },
        { "bronze", "brons" },
        { "silver", "zilver" },
        { "gold", "goud" },
        { "platinum", "platina" },
        { "%d of %zu", "%d van %zu" },
        { "earned", "behaald" },
        { "earned %s", "behaald %s" },
        { "Nothing earned yet. Go and meet somebody.",
            "Nog niets behaald. Ga iemand tegenkomen." },
        { "Everything here is earned.", "Hier is alles behaald." },
        { "A %s trophy.", "Een %s trofee." },
        { "%d trophies earned", "%d trofeeën behaald" },
        { "Your record is in the trophies tab.",
            "Jouw overzicht staat in het trofeeën-tabblad." },

        { "Somebody's out there", "Er is iemand" },
        { "Cross one other console.", "Kruis één andere console." },
        { "Properly introduced", "Netjes voorgesteld" },
        { "Give your pass a name, a greeting and something to carry.",
            "Geef je kaart een naam, een groet en iets om mee te nemen." },
        { "Fully laden", "Volgeladen" },
        { "Carry four things on your pass at once.",
            "Draag vier dingen tegelijk op je kaart." },
        { "A corner of something", "Een hoekje van iets" },
        { "Take your first puzzle piece off a crossing.",
            "Haal je eerste puzzelstukje uit een ontmoeting." },
        { "Worth keeping", "Waard om te houden" },
        { "Star a card.", "Markeer een kaart." },
        { "Ten faces", "Tien gezichten" },
        { "Cross ten different consoles.", "Kruis tien verschillende consoles." },
        { "A week of it", "Een week ervan" },
        { "Open the app on seven different days.",
            "Open de app op zeven verschillende dagen." },
        { "Two down", "Twee klaar" },
        { "Finish two puzzles.", "Maak twee puzzels af." },
        { "First purchase", "Eerste aankoop" },
        { "Buy something in the shop.", "Koop iets in de winkel." },
        { "Beginner's luck", "Beginnersgeluk" },
        { "Win a bet in the games tab.", "Win een inzet in het spellen-tabblad." },
        { "First blood", "Eerste bloed" },
        { "Win a duel at the dice.", "Win een dobbelduel." },
        { "Six all", "Zes gelijk" },
        { "Roll a six against a six.", "Gooi een zes tegen een zes." },
        { "Lined up", "Op een rij" },
        { "Line up three of a kind at the bandit.",
            "Krijg drie gelijke bij de bandiet." },
        { "The wheel's own", "Geschenk van het rad" },
        { "Win a puzzle piece on the lantern wheel.",
            "Win een puzzelstukje bij het lantaarnrad." },
        { "Ten storeys", "Tien verdiepingen" },
        { "Stack ten floors in the Mii tower.",
            "Stapel tien verdiepingen in de Mii-toren." },
        { "Dead centre", "Precies in het midden" },
        { "Land a floor within six pixels of the one below.",
            "Zet een verdieping binnen zes pixels van die eronder." },
        { "Off the mark", "Van start" },
        { "Run a hundred metres in the plaza dash.",
            "Ren honderd meter in Plaza Dash." },
        { "Your own face", "Jouw eigen gezicht" },
        { "Make a face of your own in the Mii maker.",
            "Maak een eigen gezicht in de Mii-maker." },
        { "Redecorated", "Opnieuw ingericht" },
        { "Give your card a look of your own.", "Geef je kaart een eigen uiterlijk." },
        { "Out in the world", "De wereld in" },
        { "Have your pass reach somebody.", "Laat je kaart bij iemand aankomen." },
        { "Matching outfits", "Zelfde outfit" },
        { "Cross somebody whose card wears the same look as yours.",
            "Kruis iemand wiens kaart hetzelfde uiterlijk heeft als de jouwe." },
        { "Same taste", "Zelfde smaak" },
        { "Cross somebody carrying something you carry too.",
            "Kruis iemand die iets draagt dat jij ook draagt." },
        { "The strong silent type", "De stille types" },
        { "Cross a pass with nothing written on it.",
            "Kruis een kaart zonder tekst erop." },
        { "A busy afternoon", "Een drukke middag" },
        { "Cross ten consoles in one day.", "Kruis tien consoles op één dag." },
        { "Fifty faces", "Vijftig gezichten" },
        { "Cross fifty different consoles.", "Kruis vijftig verschillende consoles." },
        { "A hundred faces", "Honderd gezichten" },
        { "Cross a hundred different consoles.",
            "Kruis honderd verschillende consoles." },
        { "A hundred hellos", "Honderd keer hallo" },
        { "Cross people a hundred times, the same ones included.",
            "Kruis honderd keer mensen, dezelfde meegerekend." },
        { "A regular", "Een vaste gast" },
        { "Cross the same console ten times.", "Kruis dezelfde console tien keer." },
        { "Around town", "In de buurt" },
        { "Cross people in five different places.",
            "Kruis mensen op vijf verschillende plekken." },
        { "Ten places", "Tien plekken" },
        { "Cross people in ten different places.",
            "Kruis mensen op tien verschillende plekken." },
        { "The late train", "De laatste trein" },
        { "Cross somebody between midnight and four.",
            "Kruis iemand tussen middernacht en vier uur." },
        { "Every day of the week", "Elke dag van de week" },
        { "Cross somebody on each of the seven weekdays.",
            "Kruis iemand op elk van de zeven weekdagen." },
        { "A fortnight", "Twee weken" },
        { "Open the app on fourteen different days.",
            "Open de app op veertien verschillende dagen." },
        { "An old friend", "Een oude bekende" },
        { "Keep a card for six months.", "Bewaar een kaart zes maanden." },
        { "A picture at last", "Eindelijk een plaatje" },
        { "Finish a puzzle.", "Maak een puzzel af." },
        { "Halfway through", "Halverwege" },
        { "Hold half of every piece there is.",
            "Bezit de helft van alle stukjes die er zijn." },
        { "A picture by committee", "Een plaatje van velen" },
        { "Take pieces from ten different people.",
            "Krijg stukjes van tien verschillende mensen." },
        { "A shortlist", "Een korte lijst" },
        { "Star twenty-five cards.", "Markeer vijfentwintig kaarten." },
        { "Nothing left unread", "Niets ongelezen" },
        { "Open every card you hold, with fifty of them.",
            "Open elke kaart die je hebt, met vijftig ervan." },
        { "Reciprocated", "Teruggegeven" },
        { "Send something back to twenty-five people.",
            "Stuur vijfentwintig mensen iets terug." },
        { "Namesake", "Naamgenoot" },
        { "Cross somebody who chose the same name as you.",
            "Kruis iemand die dezelfde naam koos als jij." },
        { "Somebody with a life", "Iemand met een leven" },
        { "Cross a pass carrying a thousand hours in one title.",
            "Kruis een kaart met duizend uur in één spel." },
        { "The shop's best customer", "Beste klant van de winkel" },
        { "Spend five hundred coins.", "Geef vijfhonderd munten uit." },
        { "Saving up", "Sparen" },
        { "Have five hundred coins at once.", "Heb vijfhonderd munten tegelijk." },
        { "On a run", "Op een reeks" },
        { "Win five duels at the dice in a row.", "Win vijf dobbelduels op een rij." },
        { "A good day at the tables", "Een goede dag aan de tafels" },
        { "Win fifty coins betting in the games tab.",
            "Win vijftig munten met inzetten in het spellen-tabblad." },
        { "Sevens", "Drie zevens" },
        { "Line up three sevens at the bandit.", "Krijg drie zevens bij de bandiet." },
        { "Twice lucky", "Twee keer geluk" },
        { "Win two puzzle pieces on the lantern wheel.",
            "Win twee puzzelstukjes bij het lantaarnrad." },
        { "Twenty up", "Twintig verdiepingen" },
        { "Stack twenty floors in the Mii tower.",
            "Stapel twintig verdiepingen in de Mii-toren." },
        { "Steady hands", "Vaste hand" },
        { "Land five floors in a row dead centre.",
            "Zet vijf verdiepingen op een rij precies in het midden." },
        { "Talked it down", "Weer rechtgetrokken" },
        { "Lean a tower to the edge of going over, and bring it back.",
            "Laat een toren bijna omvallen en trek hem terug." },
        { "A good run", "Een goede run" },
        { "Run five hundred metres in the plaza dash.",
            "Ren vijfhonderd meter in Plaza Dash." },
        { "Five hundred faces", "Vijfhonderd gezichten" },
        { "Cross five hundred different consoles.",
            "Kruis vijfhonderd verschillende consoles." },
        { "A thousand faces", "Duizend gezichten" },
        { "Cross a thousand different consoles.",
            "Kruis duizend verschillende consoles." },
        { "A thousand hellos", "Duizend keer hallo" },
        { "Cross people a thousand times, the same ones included.",
            "Kruis duizend keer mensen, dezelfde meegerekend." },
        { "Practically neighbours", "Bijna buren" },
        { "Cross the same console fifty times.",
            "Kruis dezelfde console vijftig keer." },
        { "Far travelled", "Ver gereisd" },
        { "Cross people in twenty-five different places.",
            "Kruis mensen op vijfentwintig verschillende plekken." },
        { "Fifty places", "Vijftig plekken" },
        { "Cross people in fifty different places.",
            "Kruis mensen op vijftig verschillende plekken." },
        { "A month of it", "Een maand ervan" },
        { "Open the app on thirty different days.",
            "Open de app op dertig verschillende dagen." },
        { "A hundred days", "Honderd dagen" },
        { "Open the app on a hundred different days.",
            "Open de app op honderd verschillende dagen." },
        { "A year of it", "Een jaar ervan" },
        { "Open the app on three hundred and sixty-five different days.",
            "Open de app op driehonderdvijfenzestig verschillende dagen." },
        { "Known you for a year", "Al een jaar bekend" },
        { "Keep a card for a year.", "Bewaar een kaart een jaar." },
        { "Every picture", "Alle plaatjes" },
        { "Finish every puzzle.", "Maak alle puzzels af." },
        { "By hand alone", "Zonder iets te kopen" },
        { "Finish a puzzle without buying a single piece.",
            "Maak een puzzel af zonder één stukje te kopen." },
        { "The full set", "De volledige set" },
        { "Line up three of a kind of every symbol the bandit has.",
            "Krijg drie gelijke van elk symbool van de bandiet." },
        { "Five from the wheel", "Vijf van het rad" },
        { "Win five puzzle pieces on the lantern wheel.",
            "Win vijf puzzelstukjes bij het lantaarnrad." },
        { "Thirty storeys", "Dertig verdiepingen" },
        { "Stack thirty floors in the Mii tower.",
            "Stapel dertig verdiepingen in de Mii-toren." },
        { "A kilometre of plaza", "Een kilometer plaza" },
        { "Run a thousand metres in the plaza dash.",
            "Ren duizend meter in Plaza Dash." },
        { "Seven in a row", "Zeven op een rij" },
        { "Win seven duels at the dice in a row.",
            "Win zeven dobbelduels op een rij." },
        { "The bookmaker's problem", "Het probleem van de bookmaker" },
        { "Win two hundred coins betting in the games tab.",
            "Win tweehonderd munten met inzetten in het spellen-tabblad." },
        { "Fifty contributors", "Vijftig bijdragers" },
        { "Take pieces from fifty different people.",
            "Krijg stukjes van vijftig verschillende mensen." },
        { "The whole plaza", "De hele plaza" },
        { "Earn everything else.", "Behaal al het andere." },

        // ------------------------------------------- settings, the rest of it
        { "following the console, currently %s", "volgt de console, nu %s" },
        { "light", "licht" },
        { "dark", "donker" },
        { "light by default", "standaard licht" },
        { "http://host:port of your own server",
            "http://host:poort van je eigen server" },
        { "where this build trades passes", "waar deze versie kaarten uitwisselt" },
        { "no Wi-Fi name to match on - wired, or not connected",
            "geen wifinaam om op te matchen - bekabeld of niet verbonden" },
        { "consoles on \"%s\" share this", "consoles op \"%s\" delen dit" },
        { "Nobody is blocked here. A asks the plaza to drop any it "
          "still has",
            "Hier is niemand geblokkeerd. A vraagt de plaza om er nog "
            "resterende te laten vallen" },
        { "Nobody is blocked here. Needs the plaza, and this console is "
          "offline",
            "Hier is niemand geblokkeerd. Vereist de plaza, en deze "
            "console is offline" },
        { " - blocked %s", " - geblokkeerd %s" },
        { ". A lets them cross you again", ". A laat ze je weer kruisen" },
        { ". Offline - unblocking needs the plaza",
            ". Offline - vrijgeven vereist de plaza" },
        { "Clears all %zu at once, on this console and on the plaza",
            "Geeft alle %zu tegelijk vrij, op deze console en op de plaza" },
        { "Offline - clearing the list needs the plaza, or the two would disagree",
            "Offline - de lijst wissen vereist de plaza, anders lopen de twee uiteen" },
        { "Off. Turn it on before reporting a problem, then off again",
            "Uit. Zet het aan voordat je een probleem meldt, daarna weer uit" },
        { "plaza.log, beside your pass on the SD card - it names this "
          "console and the server",
            "plaza.log, naast jouw kaart op de SD-kaart - het noemt deze "
            "console en de server" },

        // -------------------------------------- the rest of the hint strip
        //
        // The verbs, from screens whose own words are still English: the strip
        // along the bottom is chrome, like the tabs, and reads as one thing
        // wherever you are rather than changing language with the screen.
        { "buy", "kopen" },
        { "star", "markeren" },
        { "unstar", "markering weg" },
        { "delete", "verwijderen" },
        { "save", "opslaan" },
        { "load this face", "dit gezicht laden" },
        { "look at it", "bekijken" },
        { "look at them", "bekijken" },
        { "carry it", "meenemen" },
        { "put it back", "terugleggen" },
        { "trade back", "terugsturen" },
        { "toggle", "omschakelen" },
        { "block - offline", "blokkeren - offline" },
        { "make my pass", "kaart maken" },
        { "not now", "later" },
        { "your details", "jouw gegevens" },
        { "your mii", "jouw Mii" },

        // ------------------------------------------------------ how long ago
        //
        // The one place a French sentence will not take the English shape:
        // "3 days ago" puts the number in the middle, "il y a 3 jours" puts it
        // at the end, which is why relativeTime() hands the whole line to
        // format() rather than gluing a number to a word.
        { "unknown", "onbekend" },
        { "just now", "net nu" },
        { "%llum ago", "%llu min geleden" },
        { "%lluh ago", "%llu uur geleden" },
        { "Yesterday", "Gisteren" },
        { "%d days ago", "%d dagen geleden" },
        { "%d %s", "%d %s" },
        { "Jan", "jan" },
        { "Feb", "feb" },
        { "Mar", "mrt" },
        { "Apr", "apr" },
        { "May", "mei" },
        { "Jun", "jun" },
        { "Jul", "jul" },
        { "Aug", "aug" },
        { "Sep", "sep" },
        { "Oct", "okt" },
        { "Nov", "nov" },
        { "Dec", "dec" },
        { "Sun", "zo" },
        { "Mon", "ma" },
        { "Tue", "di" },
        { "Wed", "wo" },
        { "Thu", "do" },
        { "Fri", "vr" },
        { "Sat", "za" },

        // ------------------------------------------------------- the plaza
        { "the plaza - today", "de plaza - vandaag" },
        { "Nobody has crossed you yet", "Nog niemand is je gekruist" },
        { "1 person crossed your path", "1 persoon kruiste jouw pad" },
        { "%u people crossed your path", "%u personen kruisten jouw pad" },
        { "1 pass waiting for you", "1 kaart wacht op je" },
        { "%u passes waiting for you", "%u kaarten wachten op je" },
        { "Nothing new today", "Vandaag niets nieuws" },
        { "Take the console outside, or join a busier network. Passes "
          "arrive on their own.",
            "Neem de console mee naar buiten, of ga naar een drukker "
            "netwerk. Kaarten komen van zichzelf." },
        { "Somewhere out there.", "Ergens daarbuiten." },
        { ", ", ", " },
        { ", and ", " en " },
        { "Unopened passes", "Ongeopende kaarten" },
        { "nothing yet", "nog niets" },
        { "all caught up", "alles bijgewerkt" },
        { "%u waiting", "%u wachten" },
        { " - oldest %s", " - oudste %s" },
        { " - %u crossings, %u place", " - %u ontmoetingen, %u plek" },
        { " - %u crossings, %u places", " - %u ontmoetingen, %u plekken" },
        { "new", "nieuw" },
        { "hidden title", "verborgen spel" },
        { "%s - %s", "%s - %s" },
        { "%d more", "%d meer" },
        { "The plaza is empty", "De plaza is leeg" },
        { "Your console trades a pass with anyone whose Switch is on "
          "the same network, or nearby on the internet. Leave it "
          "running and come back.",
            "Jouw console wisselt een kaart uit met iedereen wiens Switch "
            "op hetzelfde netwerk zit, of dichtbij op internet. Laat hem "
            "aan en kom later terug." },
        { "Looking for passes", "Kaarten zoeken" },
        { "Asking the plaza who else has been around.",
            "De plaza wordt gevraagd wie er nog was." },

        // ------------------------------------------------------ the collection
        { "Starred %s", "%s gemarkeerd" },
        { "Unstarred %s", "Markering van %s weg" },
        { "Kept when the collection fills up.", "Blijft als de collectie vol raakt." },
        { "No longer kept when the collection fills up.",
            "Blijft niet meer als de collectie vol raakt." },
        { "%u %s met", "%u %s ontmoet" },
        { "person", "persoon" },
        { "people", "personen" },
        { "%s - %u crossings in total", "%s - %u ontmoetingen in totaal" },
        { "by name", "op naam" },
        { "starred first", "gemarkeerde eerst" },
        { "most recent first", "nieuwste eerst" },
        { "sort by name", "sorteer op naam" },
        { "sort by starred", "sorteer op markering" },
        { "sort by recent", "sorteer op datum" },
        { "Nothing collected yet. The first pass you receive lands here and stays.",
            "Nog niets verzameld. De eerste kaart die je krijgt komt hier en blijft." },
        { "met %u times", "%u keer ontmoet" },

        // ------------------------------------------------------- the Square
        { "Everyone you cross paths with turns up here.",
            "Iedereen die je kruist verschijnt hier." },
        { "A few of the people you have met, milling about.",
            "Een paar van de mensen die je ontmoette, slenterend." },

        // --------------------------------------------------------- nearby
        { "live - scanning", "live - zoeken" },
        { "live - trading", "live - uitwisselen" },
        { "offline", "offline" },
        { "cannot reach the plaza", "plaza niet bereikbaar" },
        { "1 console awake near you", "1 console actief dichtbij" },
        { "%d consoles awake near you", "%d consoles actief dichtbij" },
        { "Passes exchange on their own. You do not have to sit here.",
            "Kaarten wisselen zichzelf uit. Je hoeft hier niet te blijven." },
        { "Nobody else has checked in here yet. Leave the app open; the "
          "plaza fills faster if you do.",
            "Er heeft zich hier nog niemand anders aangemeld. Laat de app "
            "open; de plaza vult zich dan sneller." },
        { "waiting", "wachten" },
        { "exchanging...", "uitwisselen..." },
        { "passed", "gekruist" },
        { "out of range", "buiten bereik" },
        { "same network", "zelfde netwerk" },
        { "nearby network", "netwerk dichtbij" },
        { "somewhere else", "ergens anders" },
        { "Up to %d per day while the app is open",
            "Tot %d per dag zolang de app open is" },
        { " - matching on \"%s\"", " - matchen op \"%s\"" },
        { " - on \"%s\", no name to match", " - op \"%s\", geen naam om te matchen" },

        // ----------------------------------------------------- a peer nearby
        { "awake near you", "actief dichtbij" },
        { "Someone", "Iemand" },
        { "How close", "Afstand" },
        { "Playing", "Speelt" },
        { "Right now", "Op dit moment" },
        { "Trading passes", "Kaarten uitwisselen" },
        { "You have already crossed", "Jullie zijn elkaar al gekruist" },
        { "Drifted out of range", "Buiten bereik geraakt" },
        { "Waiting for the next round", "Wacht op de volgende ronde" },
        { "Passes trade on their own with everyone in range. There is "
          "nothing to press here, and nothing to wait for.",
            "Kaarten wisselen zichzelf uit met iedereen in bereik. Er is "
            "hier niets te drukken en niets om op te wachten." },

        // -------------------------------------------------------- the puzzles
        { "Nothing to collect yet", "Nog niets te verzamelen" },
        { "Every puzzle is finished", "Alle puzzels zijn af" },
        { "%d of %zu finished", "%d van %zu af" },
        { "Every console you cross brings one piece. Pick which puzzle "
          "they go into.",
            "Elke console die je kruist brengt één stukje. Kies in welke "
            "puzzel ze gaan." },
        { "filling", "bezig" },
        { "finished", "klaar" },
        { "%d of %u pieces", "%d van %u stukjes" },
        { "already finished", "al af" },
        { "already filling", "al bezig" },
        { "fill this one next", "vul deze hierna" },
        { "%s is finished", "%s is af" },
        { "Pieces go into the first puzzle that is not.",
            "Stukjes gaan naar de eerste die dat niet is." },
        { "Already filling %s", "%s wordt al gevuld" },
        { "Every crossing brings a piece of this one.",
            "Elke ontmoeting brengt een stukje hiervan." },
        { "Filling %s", "%s wordt gevuld" },
        { "Crossings go into this one until you pick another.",
            "Ontmoetingen gaan naar deze tot je een andere kiest." },
        { "One person brought this", "Één persoon bracht dit" },
        { "%d people brought this", "%d personen brachten dit" },
        { " - finished %s", " - af %s" },
        { "Piece %d", "Stukje %d" },
        { "Brought by", "Gebracht door" },
        { "Not found yet", "Nog niet gevonden" },
        { "someone", "iemand" },
        { "Cross someone while this puzzle is the one being filled.",
            "Kruis iemand terwijl deze puzzel wordt gevuld." },
        { "Collected before the app started keeping track.",
            "Verzameld voordat de app dit bijhield." },

        // ---------------------------------------------------------- the shop
        { "%u earned - %u spent", "%u verdiend - %u besteed" },
        { "A piece you do not have yet of %s - the puzzle your "
          "crossings are filling, %d of %u so far. Twice the price, "
          "because you get to say which picture it goes into.",
            "Een stukje van %s dat je nog niet hebt - de puzzel die jouw "
            "ontmoetingen vullen, %d van %u tot nu toe. Dubbele prijs, "
            "omdat jij de afbeelding kiest." },
        { "%s is finished. Choose another to fill on the puzzles "
          "screen, or take your chances with any puzzle.",
            "%s is af. Kies een andere om te vullen op het puzzelscherm, "
            "of waag het met een willekeurige." },
        { "A piece of any puzzle", "Een stukje van een willekeurige puzzel" },
        { "Half the price, and you do not choose: one piece drawn from "
          "every unfinished puzzle at once - %d still to find across %d "
          "of them.",
            "Halve prijs, en je kiest niet: één stukje getrokken uit alle "
            "onafgemaakte puzzels tegelijk - nog %d te vinden over %d "
            "ervan." },
        { "Every puzzle is finished. There is nothing left to sell you.",
            "Alle puzzels zijn af. Er is niets meer te verkopen." },
        { "Nothing on the shelf yet.", "Nog niets op het schap." },
        { "%u more coins needed. Ten arrive on every new day you open "
          "the app.",
            "Er ontbreken %u munten. Er komen tien op elke nieuwe dag dat "
            "je de app opent." },
        { "sold out", "uitverkocht" },
        { "%u coins short", "%u munten te kort" },
        { "Nothing to sell there", "Daar is niets te verkopen" },
        { "There are no pieces left to find there.",
            "Daar zijn geen stukjes meer te vinden." },
        { "Piece %d of %s", "Stukje %d van %s" },
        { "%u coins left.", "%u munten over." },
        { "Buy %s for %u coins?", "%s kopen voor %u munten?" },
        { "%s That leaves you %u.", "%s Dan heb je nog %u." },
        { "One you do not hold yet, into the puzzle you are filling.",
            "Een die je nog niet hebt, in de puzzel die je vult." },
        { "Drawn from every unfinished puzzle at once, so it may not be "
          "the one you are filling.",
            "Getrokken uit alle onafgemaakte puzzels tegelijk, dus "
            "misschien niet die je nu vult." },
        { "Buy it", "Kopen" },

        // -------------------------------------------------------- your pass
        { "your pass", "jouw kaart" },
        { "This is what they see", "Dit is wat zij zien" },
        { "%s theme", "thema %s" },
        { "(no greeting yet)", "(nog geen groet)" },
        { "Name", "Naam" },
        { "not set yet", "nog niet ingesteld" },
        { "Greeting", "Groet" },
        { "%zu of 60 characters", "%zu van 60 tekens" },
        { "Card theme", "Kaartthema" },
        { "%s - 6 unlocked", "%s - 6 vrijgespeeld" },
        { "What you carry", "Wat je draagt" },
        { "Title on your pass", "Spel op jouw kaart" },
        { "hidden by privacy settings", "verborgen door privacy-instellingen" },
        { "reading the play history...", "speelgeschiedenis lezen..." },
        { "nothing played on this console yet", "nog niets gespeeld op deze console" },
        { "hidden", "verborgen" },
        { "%s - %uh", "%s - %u uur" },
        { "edit", "bewerken" },
        { "edit your mii", "Mii bewerken" },
        { "next theme", "volgend thema" },
        { "next title", "volgend spel" },
        { "The name on your pass", "De naam op jouw kaart" },
        { "Up to 60 characters", "Tot 60 tekens" },
        { "Your pass never carries your account name, your friend code, "
          "or a precise position - only what you typed and, if you "
          "allow it, the place you named.",
            "Jouw kaart bevat nooit je accountnaam, je vriendencode of "
            "een precieze positie - alleen wat je typte en, als je dat "
            "toestaat, de plek die je noemde." },

        // ------------------------------------------------------ what you carry
        { "on your pass", "op jouw kaart" },
        { "%zu of %d", "%zu van %d" },
        { "Four is the limit", "Vier is het maximum" },
        { "Put something back before picking this up.",
            "Leg iets terug voordat je dit pakt." },

        // -------------------------------------------------------- a crossing
        { "crossed paths - %s", "elkaar gekruist - %s" },
        { "playing %s", "speelt %s" },
        { "somewhere on the network", "ergens op het netwerk" },
        { "carrying", "draagt" },
        { "time crossed", "keer gekruist" },
        { "times crossed", "keer gekruist" },
        { "game installed", "spel geïnstalleerd" },
        { "games installed", "spellen geïnstalleerd" },
        { "hours played", "uur gespeeld" },
        { "in %s", "in %s" },
        { "Already traded back", "Al teruggegeven" },
        { "Trade something back", "Iets terugsturen" },
        { "Take it, send something back", "Neem het aan en stuur iets terug" },
        { "Star this card", "Deze kaart markeren" },
        { "Unstar this card", "Markering weghalen" },
        { "Sent something back to %s", "Iets teruggestuurd naar %s" },
        { "It travels with your pass the next time you cross.",
            "Het reist mee met jouw kaart bij de volgende ontmoeting." },
        { "Blocking has to reach the server, or they would keep "
          "receiving your pass. Try again when the dot by the tabs is "
          "green.",
            "Blokkeren moet de server bereiken, anders blijven ze jouw "
            "kaart ontvangen. Probeer het als het stipje bij de tabs "
            "groen is." },
        { "Block %s?", "%s blokkeren?" },
        { "Their pass is deleted and this console can never cross you "
          "again. They are not told.",
            "Hun kaart wordt verwijderd en deze console kan je nooit meer "
            "kruisen. Ze worden niet ingelicht." },
        { "Block and forget", "Blokkeren en vergeten" },

        // ------------------------------------------------------- your Mii
        { "your face", "jouw gezicht" },
        { "Make your Mii", "Maak jouw Mii" },
        { "how others see you", "hoe anderen je zien" },
        { "yes", "ja" },
        { "no", "nee" },
        { "%d of %d", "%d van %d" },
        { "Face shape", "Gezichtsvorm" },
        { "Skin tone", "Huidtint" },
        { "Hair", "Haar" },
        { "Hair colour", "Haarkleur" },
        { "Hair flipped", "Haar gespiegeld" },
        { "Eyes", "Ogen" },
        { "Eye colour", "Oogkleur" },
        { "Eyebrows", "Wenkbrauwen" },
        { "Eyebrow colour", "Wenkbrauwkleur" },
        { "Nose", "Neus" },
        { "Mouth", "Mond" },
        { "Lip colour", "Lipkleur" },
        { "Glasses", "Bril" },
        { "Glasses colour", "Brilkleur" },
        { "Moustache", "Snor" },
        { "Beard", "Baard" },
        { "Facial hair colour", "Kleur gezichtshaar" },
        { "Wrinkles", "Rimpels" },
        { "Makeup", "Make-up" },
        { "Mole", "Moedervlek" },
        { "Headwear", "Hoofddeksel" },
        { "Build", "Postuur" },
        { "Height", "Lengte" },
        { "Favourite colour", "Lievelingskleur" },
        { "Eye spacing", "Oogafstand" },
        { "Eye height", "Ooghoogte" },
        { "Eye width", "Oogbreedte" },
        { "Eye height scale", "Oogrekking" },
        { "Eye tilt", "Oogkanteling" },
        { "Eyebrow spacing", "Wenkbrauwafstand" },
        { "Eyebrow height", "Wenkbrauwhoogte" },
        { "Eyebrow width", "Wenkbrauwbreedte" },
        { "Eyebrow thickness", "Wenkbrauwdikte" },
        { "Eyebrow tilt", "Wenkbrauwkanteling" },
        { "Nose height", "Neushoogte" },
        { "Nose size", "Neusgrootte" },
        { "Mouth height", "Mondhoogte" },
        { "Mouth width", "Mondbreedte" },
        { "Mouth thickness", "Monddikte" },
        { "Moustache height", "Snorhoogte" },
        { "Moustache size", "Snorgrootte" },
        { "Beard height", "Baardhoogte" },
        { "Beard size", "Baardgrootte" },
        { "Glasses height", "Brilhoogte" },
        { "Glasses size", "Brilgrootte" },
        { "Mole across", "Moedervlek horizontaal" },
        { "Mole down", "Moedervlek verticaal" },
        { "Mole size", "Grootte moedervlek" },

        // -------------------------------------------------- faces on the card
        { "faces on the sd card", "gezichten op de sd-kaart" },
        { "Save and load", "Opslaan en laden" },
        { "Save this face...", "Dit gezicht opslaan..." },
        { "Name this face", "Geef dit gezicht een naam" },
        { "Needs a name", "Heeft een naam nodig" },
        { "That name has nothing in it a file can be called.",
            "Die naam bevat niets waarmee een bestand kan heten." },
        { "Saved", "Opgeslagen" },
        { "%s is in the export folder.", "%s staat in de exportmap." },
        { "Not saved", "Niet opgeslagen" },
        { "Replace %s?", "%s vervangen?" },
        { "There is already a face saved under that name. Replacing it "
          "cannot be undone.",
            "Er is al een gezicht met die naam opgeslagen. Vervangen kan "
            "niet worden teruggedraaid." },
        { "Replace", "Vervangen" },
        { "Delete %s?", "%s verwijderen?" },
        { "It is removed from the SD card for good. Anyone you sent it "
          "to still has their copy.",
            "Het wordt definitief van de SD-kaart verwijderd. Wie het van "
            "je kreeg houdt zijn kopie." },
        { "Delete", "Verwijderen" },
        { "Deleted", "Verwijderd" },
        { "%s is gone from the export folder.", "%s is verdwenen uit de exportmap." },
        { "Not deleted", "Niet verwijderd" },
        { "Cannot load that one", "Die kan niet worden geladen" },
        { "Not a face this version can read",
            "Geen gezicht dat deze versie kan lezen" },
        { "Nothing saved yet. Faces you save show up here, and so does "
          "anything you drop into the folder yourself.",
            "Nog niets opgeslagen. Gezichten die je opslaat komen hier, "
            "net als alles wat je zelf in de map zet." },

        // --------------------------------------------------------- first run
        { "Leave it open.", "Laat hem open." },
        { "While this is open, your console swaps a small pass with the "
          "others that are open too - a face, a greeting, whatever you "
          "chose to carry. Who you meet is whoever is awake within the "
          "reach you set.",
            "Zolang dit open is, wisselt jouw console een kleine kaart "
            "uit met de andere die ook open zijn - een gezicht, een "
            "groet, wat je koos om mee te nemen. Je kruist wie actief is "
            "binnen het bereik dat je instelt." },
        { "Make your pass - a face, a greeting, one thing to trade",
            "Maak je kaart - een gezicht, een groet, één ding om te ruilen" },
        { "Leave it open; it checks in on its own",
            "Laat hem open; hij meldt zich zelf aan" },
        { "Open the plaza and see who you crossed",
            "Open de plaza en zie wie je kruiste" },
        { "A greeting, up to 60 characters", "Een groet, tot 60 tekens" },
        { "pair this console", "deze console koppelen" },
        { "A picture of this console's id. It lives on the SD card, is "
          "tied to nothing about the hardware, and you can throw it "
          "away.",
            "Een afbeelding van het id van deze console. Hij staat op de "
            "SD-kaart, hangt aan geen hardware vast en je mag hem "
            "weggooien." },

        // ------------------------------------------- updates, and the app itself
        { "Version %s is out", "Versie %s is uit" },
        { "Settings -> About -> Check for updates to install it.",
            "Instellingen -> Over -> Naar updates zoeken om hem te installeren." },
        { "Puzzle art downloaded", "Puzzelafbeeldingen gedownload" },
        { "Restart the app to see the pictures.",
            "Herstart de app om de afbeeldingen te zien." },
        { "Update installed", "Update geïnstalleerd" },
        { "Restart from Settings -> \"About\" to run version %s.",
            "Herstart via Instellingen -> \"Over\" om versie %s te gebruiken." },
        { "Up to date", "Up-to-date" },
        { "%s is the latest release.", "%s is de nieuwste release." },
        { "Could not download puzzle art", "Kon puzzelafbeeldingen niet downloaden" },
        { "Could not check for updates", "Kon niet naar updates zoeken" },
        { "Install version %s?", "Versie %s installeren?" },
        { "The new version is downloaded, checked, and only then "
          "written over this one. The copy you are running now is kept "
          "until the new one has been verified.",
            "De nieuwe versie wordt gedownload, gecontroleerd en pas "
            "daarna over deze geschreven. De draaiende kopie blijft tot "
            "de nieuwe is gecontroleerd." },
        { "Install", "Installeren" },
        { "Restart into version %s?", "Herstarten in versie %s?" },
        { "The app closes and opens again on the new version. Your "
          "passes and your collection are untouched.",
            "De app sluit en opent opnieuw op de nieuwe versie. Jouw "
            "kaarten en collectie blijven onaangeroerd." },
        { "Restart", "Herstarten" },
        { "%s passed you", "%s kruiste jou" },
        { "%s and %zu others passed you", "%s en %zu anderen kruisten jou" },
        { "%zu new passes", "%zu nieuwe kaarten" },
        { "a piece of %s", "een stukje van %s" },
        { "%d pieces of %s", "%d stukjes van %s" },
        { "one of them is carrying %s", "een van hen draagt %s" },
        { "Open the plaza to see who.", "Open de plaza om te zien wie." },
        { "Keep everything", "Alles houden" },

        // ------------------------------------------- settings, the dialogs
        { "Where are you? A district, a station, a shop",
            "Waar ben je? Een wijk, een station, een winkel" },
        { "Which city", "Welke stad" },
        { "Plaza server address", "Adres van de plaza-server" },
        { "Clear any block the plaza still has?",
            "Alle blokkades wissen die de plaza nog heeft?" },
        { "Clear all %zu?", "Alle %zu vrijgeven?" },
        { "This console has none listed, but the plaza keeps its own "
          "copy and a restored backup can leave the two disagreeing. "
          "Nothing happens if it has none either.",
            "Deze console heeft er geen, maar de plaza houdt zijn eigen "
            "lijst en een teruggezette back-up kan de twee laten "
            "verschillen. Heeft hij er ook geen, dan gebeurt er niets." },
        { "Every console you have blocked can cross you again, except "
          "any that blocked you as well. Their old passes are not "
          "coming back; only the block is lifted.",
            "Elke console die je blokkeerde kan je weer kruisen, behalve "
            "die jou ook blokkeerden. Hun oude kaarten komen niet terug; "
            "alleen de blokkade gaat eraf." },
        { "Clear them", "Alles vrijgeven" },
        { "Block list cleared", "Blokkeerlijst gewist" },
        { "This console has none left, and the plaza has been asked to "
          "drop the blocks it was holding for you.",
            "Deze console heeft er geen meer, en de plaza is gevraagd de "
            "blokkades die hij voor je hield te laten vallen." },
        { "Delete every pass?", "Alle kaarten verwijderen?" },
        { "Every pass you have collected is removed from this console. "
          "Your own pass and your identity stay.",
            "Elke kaart die je verzamelde wordt van deze console "
            "verwijderd. Jouw eigen kaart en identiteit blijven." },
        { "Delete them all", "Alles verwijderen" },
        { "Collection cleared", "Collectie gewist" },
        { "The plaza is empty again.", "De plaza is weer leeg." },
        { "Start over as someone new?", "Opnieuw beginnen als iemand anders?" },
        { "This console gets a brand new id. Passes you already handed "
          "out can no longer be linked to you, and your collection is "
          "deleted.",
            "Deze console krijgt een compleet nieuw id. Al uitgedeelde "
            "kaarten zijn niet meer aan jou te koppelen, en je collectie "
            "wordt verwijderd." },
        { "Start over", "Opnieuw beginnen" },
        { "You are someone new", "Je bent iemand anders" },
        { "Your code is now %s", "Jouw code is nu %s" },

        // ------------------------------------------- what the plaza is doing
        //
        // These come off the sync and update threads, and are read back on
        // screen in Settings and in Nearby. Whole sentences are translated;
        // the protocol diagnostics they sometimes carry - an HTTP status, a
        // libnx result code - stay as they are, because they exist to be
        // pasted into a bug report.
        { "Trading passes...", "Kaarten uitwisselen..." },
        { "Connected over LAN: matching by network area only.",
            "Verbonden via LAN: alleen matchen op netwerkgebied." },
        { "Nobody else is awake here yet.", "Er is hier nog niemand anders actief." },
        { "No plaza server set yet. Settings > Plaza server.",
            "Nog geen plaza-server ingesteld. Instellingen > Plaza-server." },
        { "Server sent something that was not JSON",
            "De server stuurde iets dat geen JSON was" },
        { "Server said %ld on %s", "Server antwoordde %ld op %s" },
        { "Server said %ld on hello", "Server antwoordde %ld op hello" },
        { "Checking for updates", "Naar updates zoeken" },
        { "Downloading", "Downloaden" },
        { "Unpacking", "Uitpakken" },
        { "Installing", "Installeren" },
        { "nx-plaza %s is the latest version.", "nx-plaza %s is de nieuwste versie." },
        { "Release %s has no .nro to install.",
            "Release %s heeft geen .nro om te installeren." },
        { "Version %s is available.", "Versie %s is beschikbaar." },
        { "The download is version %s, not %s.", "De download is versie %s, niet %s." },
        { "Version %s is installed. Restart to run it.",
            "Versie %s is geïnstalleerd. Herstart om hem te gebruiken." },
        { "%d puzzle pictures downloaded. Restart to see them.",
            "%d puzzelafbeeldingen gedownload. Herstart om ze te zien." },

        // ------------------------------------------- the last of the settings
        { "Asking GitHub for the latest release",
            "GitHub wordt om de nieuwste versie gevraagd" },
        { "Press A to download and install it",
            "Druk op A om te downloaden en installeren" },
        { "Press A to restart into it", "Druk op A om ermee te herstarten" },
        { "You are on the latest release", "Je hebt de nieuwste versie" },
        { "up to date", "up-to-date" },
        { "Looks at the releases on GitHub", "Kijkt naar de releases op GitHub" },
        { "If the puzzles show numbered squares, get the pictures here "
          "and restart",
            "Als de puzzels genummerde vakjes tonen, haal hier de "
            "afbeeldingen en herstart" },
        { "failed", "mislukt" },
        { "Somebody", "Iemand" },
        { "keep everything", "alles houden" },
        { "switch tab", "tab wisselen" },

        // ------------------------------------------------- the puzzle pictures
        { "Forest in the Rain", "Bos in de regen" },
        { "Mountain in the Fog", "Berg in de mist" },
        { "Mystical Swamp", "Mystiek moeras" },
        { "Old Farm", "Oude boerderij" },
        { "Castle Blue", "Blauw kasteel" },
        { "Beach at Dusk", "Strand in de schemering" },

        // --------------------------------------------------- the card themes
        { "Amber lantern", "Amberen lantaarn" },
        { "Dusk market", "Schemermarkt" },
        { "Tidepool", "Getijdenpoel" },
        { "Paper lantern", "Papieren lantaarn" },
        { "Rose market", "Rozenmarkt" },
        { "Night express", "Nachtexpres" },

        // ----------------------------------------------- the pass you start with
        { "Traveller", "Reiziger" },
        { "Just passing through.", "Ik ben maar op doorreis." },

        // ------------------------------------------- what the plaza is saying
        { "Looking around...", "Rondkijken..." },
        { "Publishing your pass...", "Jouw kaart publiceren..." },
        { "Blocking a console...", "Een console blokkeren..." },
        { "Unblocking a console...", "Een console vrijgeven..." },
        { "Clearing the block list...", "Blokkeerlijst wissen..." },
        { "Asking the server to forget us...", "De server vragen ons te vergeten..." },
        { "Daily crossing limit reached. Back tomorrow.",
            "Daglimiet aan ontmoetingen bereikt. Morgen weer." },
        { "Networking is unavailable.", "Het netwerk is niet beschikbaar." },
        { "No internet connection.", "Geen internetverbinding." },

        // ------------------------------------------- when an update goes wrong
        { "This console would not start the update worker.",
            "Deze console kon de update-taak niet starten." },
        { "The release list could not be read.",
            "De releaselijst kon niet worden gelezen." },
        { "The release list carried no version.",
            "De releaselijst bevatte geen versie." },
        { "The download did not finish: %s", "De download is niet voltooid: %s" },
        { "The downloaded archive held no nx-plaza build.",
            "Het gedownloade archief bevatte geen nx-plaza-build." },
        { "The downloaded file is not a valid nx-plaza build.",
            "Het gedownloade bestand is geen geldige nx-plaza-build." },
        { "This build does not know its own path, so it cannot replace itself.",
            "Deze versie kent zijn eigen pad niet en kan zich niet vervangen." },
        { "The current version could not be backed up.",
            "De huidige versie kon niet worden geback-upt." },
        { "The update could not be written over the current one - %s",
            "De update kon niet over de huidige worden geschreven - %s" },
        { "The installed update did not verify, so it was rolled back.",
            "De geïnstalleerde update kon niet worden gecontroleerd en is "
            "teruggedraaid." },
        { "That release publishes no puzzle art.",
            "Die release publiceert geen puzzelafbeeldingen." },
        { "That release's archive holds no puzzle art.",
            "Het archief van die release bevat geen puzzelafbeeldingen." },
        { "The puzzle art that arrived was not readable.",
            "De aangekomen puzzelafbeeldingen waren onleesbaar." },
        { "The folder for the puzzle art could not be made.",
            "De map voor de puzzelafbeeldingen kon niet worden gemaakt." },
        { "The puzzle art could not be written - %s",
            "De puzzelafbeeldingen konden niet worden geschreven - %s" },

        // ------------------------------------------ the settings sections
        //
        // The eight names down the left of the screen, and the pills on the
        // rows that offer a choice.
        { "Privacy", "Privacy" },
        { "Exchange", "Uitwisseling" },
        { "Appearance", "Weergave" },
        { "Languages", "Talen" },
        { "This console", "Deze console" },
        { "Data", "Gegevens" },
        { "About", "Over" },
        { "Off", "Uit" },
        { "District", "Wijk" },
        { "City", "Stad" },
        { "Same network", "Zelfde netwerk" },
        { "Anywhere", "Overal" },
        { "Light", "Licht" },
        { "Dark", "Donker" },

        // -------------------------------------- when the SD card says no
        { "Could not make the export folder on the SD card.",
            "De exportmap kon niet op de SD-kaart worden gemaakt." },
        { "Could not write to the SD card.",
            "Er kon niet naar de SD-kaart worden geschreven." },
        { "That file could not be read.", "Dat bestand kon niet worden gelezen." },
        { "That is not a face this app saved.",
            "Dat is geen gezicht dat deze app opsloeg." },
        { "That face was saved by a different version of the app.",
            "Dat gezicht is opgeslagen door een andere versie van de app." },
        { "Could not delete that file from the SD card.",
            "Dat bestand kon niet van de SD-kaart worden verwijderd." },
        { "could not make the backup folder", "de back-upmap kon niet worden gemaakt" },
        { "could not copy %s", "%s kon niet worden gekopieerd" },
        { "there was nothing to back up", "er was niets om te back-uppen" },

        // ------------------------------------------------- the same in French
        //
        // Listed on purpose rather than left out, so the scanner can tell a
        // word that needs no translation from one nobody has looked at yet.
        // tr() drops these rows: falling back to the English is the same
        // answer, and cheaper.
        { "Plaza", "Plaza" },
        { "Collection", "Collectie" },
        { "collection", "collectie" },
        { "Puzzles", "Puzzels" },
        { "puzzles", "puzzels" },
        { "plaza dash", "plaza dash" },
        { "sections", "secties" },
        { "m", "m" },
        { "-", "-" },
        { "%d", "%d" },
        { "Notifications", "Meldingen" },
        { "Console", "Console" },
        { "nx-plaza ", "nx-plaza " },
        { "(none)", "(geen)" },
        { "NX Plaza - Online StreetPass | ", "NX Plaza - Online StreetPass | " },
        { "https://github.com/Insektaure/NX-Plaza",
            "https://github.com/Insektaure/NX-Plaza" },
    };

} // namespace

Catalog dutchCatalog()
{
    return Catalog { kEntries, sizeof(kEntries) / sizeof(kEntries[0]) };
}

} // namespace nxp
