#include "core/i18n.h"

// Italian.
//
// Generated by tools/gen_lang_tables.py from tools/lang_data.py, in the shape
// of lang_fr.cpp - same sections, same order - so any two languages can be
// read side by side. Edit the table, not this file.
//
// Left column: the English exactly as it is written in the code, which is the
// key. Reword a line in a scene and the row here stops matching in silence,
// which is what `tools/i18n_scan.py --lang it` is for. A string this
// language has not been given yet is simply absent, and comes out in English.

namespace nxp {
namespace {

    const Translation kEntries[] = {
        // ------------------------------------------------------------- tabs
        { "Nearby", "Nei paraggi" },
        { "The Square", "La piazza" },
        { "Games", "Giochi" },
        { "The shop", "Il negozio" },
        { "Trophies", "Trofei" },
        { "Your pass", "La tua carta" },
        { "Settings", "Impostazioni" },

        // ------------------------------------------------- the hint strip
        { "again", "ancora" },
        { "back", "indietro" },
        { "block", "blocca" },
        { "cancel", "annulla" },
        { "change", "cambia" },
        { "choose", "scegli" },
        { "close", "chiudi" },
        { "done", "fatto" },
        { "fill the screen", "schermo intero" },
        { "give up", "arrenditi" },
        { "jump - hold to go higher", "salta - tieni premuto per saltare più in alto" },
        { "jump ten", "dieci avanti" },
        { "left and right to change", "sinistra e destra per cambiare" },
        { "look now", "cerca ora" },
        { "mark read", "segna letto" },
        { "next pass", "carta successiva" },
        { "open", "apri" },
        { "open section", "apri sezione" },
        { "play", "gioca" },
        { "roll", "lancia" },
        { "roll again", "rilancia" },
        { "run", "corri" },
        { "run again", "corri ancora" },
        { "save / load", "salva / carica" },
        { "save face", "salva volto" },
        { "shuffle", "casuale" },
        { "shuffle face", "volto casuale" },
        { "spin", "gira" },
        { "start", "inizia" },

        // --------------------------------------------------------- buttons
        { "Make my pass", "Crea la mia carta" },
        { "Not now", "Non ora" },
        { "Run", "Corri" },
        { "Run again", "Corri ancora" },
        { "Start stacking", "Inizia a impilare" },
        { "Stack again", "Impila ancora" },

        // ------------------------------------------- eyebrows and captions
        { "games", "giochi" },
        { "trophies", "trofei" },
        { "the shop", "il negozio" },
        { "the square", "la piazza" },
        { "the mii race", "la corsa dei Mii" },
        { "the mii tower", "la torre di Mii" },
        { "the dice duel", "il duello di dadi" },
        { "what it pays", "quanto paga" },
        { "your prediction", "il tuo pronostico" },
        { "your pairing code", "il tuo codice di abbinamento" },
        { "people met", "persone incontrate" },
        { "times your pass was sent", "volte che la tua carta è stata inviata" },
        { "floors", "piani" },
        { "best %u %s", "record %u %s" },

        // ------------------------------------------------------ the games
        { "Something to do", "Qualcosa da fare" },
        { "Played with the faces and names in your collection, so the "
          "more people you have crossed, the more there is here.",
            "Si gioca con i volti e i nomi della tua collezione: più "
            "gente hai incrociato, più c'è da fare qui." },

        { "The Mii race", "La corsa dei Mii" },
        { "Three of the people you have crossed, against your own Mii, "
          "and nobody is faster than anybody.\nWatch for nothing, bet a "
          "coin for three back, or call first and second for eleven.",
            "Tre delle persone che hai incrociato, contro il tuo Mii, e "
            "nessuno è più veloce di nessuno.\nGuarda gratis, punta una "
            "moneta per tre indietro, o pronostica 1° e 2° per undici." },

        { "The dice duel", "Il duello di dadi" },
        { "One roll each against somebody you have crossed, and the "
          "highest takes it.\nRoll for nothing, or bet two coins for "
          "three back - and a draw hands your two back.",
            "Un lancio per ciascuno contro qualcuno che hai incrociato, e "
            "vince il più alto.\nLancia gratis, o punta due monete per "
            "tre indietro - un pari ti restituisce le tue due." },

        { "The lantern wheel", "La ruota delle lanterne" },
        { "Twelve lanterns and a needle, and two of them are a puzzle "
          "piece.\nWatch it for nothing, or ten coins a spin - every "
          "lantern pays something, and one in six is a piece.",
            "Dodici lanterne e un ago, e due di esse sono un pezzo di "
            "puzzle.\nGuarda gratis, o dieci monete per giro - ogni "
            "lanterna paga qualcosa, e una su sei è un pezzo." },

        { "The bandit", "Il bandito" },
        { "Three reels, and two machines: three symbols that pay small "
          "and often, or five that pay rarely and big.\nA coin a spin, "
          "or spin for nothing - two bells hand the coin back, and the "
          "board on the wall lists every line it pays.",
            "Tre rulli e due macchine: tre simboli che pagano poco e "
            "spesso, o cinque che pagano raramente e molto.\nUna moneta "
            "per giro, o gratis - due campane restituiscono la moneta, e "
            "il tabellone al muro elenca ogni combinazione." },

        { "The Mii tower", "La torre di Mii" },
        { "Stack the people you have crossed, one drop at a time.\nMiss "
          "the shoulders below and they fall; drift too far from the "
          "base and the lot goes over.",
            "Impila le persone che hai incrociato, una per "
            "volta.\nSbaglia le spalle sotto e cadono; allontanati troppo "
            "dalla base e crolla tutto." },

        { "Plaza dash", "Plaza Dash" },
        { "Your own Mii running through the plaza, jumping what the "
          "market leaves in the way.\nIt gets quicker. Nothing staked, "
          "nothing won - only how far you got.",
            "Il tuo Mii corre per il plaza saltando ciò che il mercato "
            "lascia in mezzo.\nAccelera. Nulla puntato, nulla vinto - "
            "solo quanto lontano sei arrivato." },

        // ------------------------------------------------ settings: sections
        { "%s never sends your name or an exact position. You choose "
          "how much of a pass leaves the console.",
            "%s non invia mai il tuo nome né una posizione esatta. Decidi "
            "tu quanto di una carta lascia la console." },
        { "How passes find their way to you.", "Come le carte arrivano fino a te." },
        { "Nothing interrupts a game. The plaza waits.",
            "Niente interrompe una partita. Il plaza aspetta." },
        { "The app opens in daylight. Dark is for a dim room, or match "
          "whatever the console is set to.",
            "L'app si apre in chiaro. Scuro è per una stanza in penombra, "
            "oppure segui la console." },
        { "The app is written in English and says what it has been "
          "taught to say in anything else. Whatever a language is "
          "missing stays in English.",
            "L'app è scritta in inglese e nelle altre lingue dice ciò che "
            "le è stato insegnato. Ciò che manca a una lingua resta in "
            "inglese." },
        { "Where your passes go, and how another console recognises this one.",
            "Dove vanno le tue carte, e come un'altra console riconosce questa." },
        { "Everything the app keeps lives on the SD card, and all of it can go.",
            "Tutto ciò che l'app conserva è sulla scheda SD, e tutto può andarsene." },
        { "What this build of %s is, who made it, and where it came from.",
            "Cos'è questa versione di %s, chi l'ha fatta e da dove viene." },

        // ---------------------------------------------------- settings: rows
        { "English - what the app is written in",
            "Inglese - la lingua in cui è scritta l'app" },
        { "Share where we crossed", "Condividi dove ci siamo incrociati" },
        { "District only - never a street or a venue you did not name",
            "Solo il quartiere - mai una via o un luogo che non hai indicato" },
        { "District label", "Nome del quartiere" },
        { "e.g. Namba Station", "ad es. Namba Station" },
        { "City label", "Nome della città" },
        { "used when sharing is set to City",
            "usato quando la condivisione è su Città" },
        { "Show what I am playing", "Mostra cosa sto giocando" },
        { "The title, your hours in it, and how many games you have. "
          "Hidden titles stay hidden, always",
            "Il gioco, le tue ore su di esso e quanti giochi hai. I "
            "giochi nascosti restano nascosti, sempre" },
        { "Exchange passes automatically", "Scambia le carte automaticamente" },
        { "Trades happen while the app is open",
            "Gli scambi avvengono mentre l'app è aperta" },
        { "How far a crossing reaches", "Portata di un incrocio" },
        { "Same network is the closest thing to walking past someone",
            "La stessa rete è la cosa più simile a incrociarsi per strada" },
        { "Crossings per day", "Incroci al giorno" },
        { "Tell me when passes arrive", "Avvisami quando arrivano carte" },
        { "A card in the corner, never an interruption",
            "Una carta nell'angolo, mai un'interruzione" },
        { "Theme", "Tema" },
        { "Hold the scenery still", "Tieni fermo lo sfondo" },
        { "On, for anybody the Plaza Dash minigame makes queasy: the "
          "background stops moving and only what you have to dodge "
          "does. Turn it off for the full parallax",
            "Attivo, per chi ha la nausea col minigioco Plaza Dash: lo "
            "sfondo si ferma e si muove solo ciò da evitare. Disattivalo "
            "per la parallasse completa" },
        { "Plaza server", "Server del plaza" },
        { "Wi-Fi match token", "Token Wi-Fi" },
        { "Check in now", "Connettiti ora" },
        { "Blocked consoles", "Console bloccate" },
        { "Clear the whole list", "Svuota tutta la lista" },
        { "unblock", "sblocca" },
        { "none", "nessuno" },
        { "Write a log file", "Scrivi un file di log" },
        { "Copy everything to a backup folder",
            "Copia tutto in una cartella di backup" },
        { "Your identity, your pass and your collection, into backup/ "
          "on this card",
            "La tua identità, la tua carta e la tua collezione, in "
            "backup/ su questa scheda" },
        { "Download puzzle art", "Scarica le immagini dei puzzle" },
        { "Delete every pass you have collected", "Elimina tutte le carte raccolte" },
        { "This cannot be undone", "Non si può annullare" },
        { "Start over as someone new", "Ricomincia come qualcun altro" },
        { "New id, new pass; everything you handed out goes unlinkable",
            "Nuovo id, nuova carta; tutto ciò che hai distribuito diventa "
            "non collegabile" },
        { "Check for updates", "Cerca aggiornamenti" },
        { "Check on every launch", "Controlla a ogni avvio" },
        { "One request when the app opens; it never installs on its own",
            "Una richiesta all'avvio; non installa mai da sé" },
        { "Developed by Insektaure", "Sviluppato da Insektaure" },
        { "Find us on GitHub !", "Trovaci su GitHub !" },
        { "This console's id", "Id di questa console" },
        { "Glyphs drawn so far", "Glifi disegnati finora" },
        { "how much of the glyph atlas is in use",
            "quanta parte dell'atlante dei glifi è in uso" },
        { "the atlas is full - some text will be missing",
            "l'atlante è pieno - parte del testo mancherà" },

        // -------------------------------------------------- settings: toasts
        { "Not connected to the plaza", "Non connesso al plaza" },
        { "This one needs the server. The dot by the tabs turns green "
          "when it can be reached.",
            "Questo richiede il server. Il punto accanto alle schede "
            "diventa verde quando è raggiungibile." },
        { "Busy with another download", "C'è un altro download in corso" },
        { "Wait for the update in About to finish, then try again.",
            "Attendi la fine dell'aggiornamento in Informazioni, poi riprova." },
        { "Downloading puzzle art", "Scarico le immagini" },
        { "This row shows how it is going.", "Questa riga mostra come procede." },
        { "Could not back up", "Backup non riuscito" },
        { "Backed up to %s", "Salvato in %s" },
        { "It is on the same card. Copy the backup folder to a computer "
          "to be safe from losing the card itself.",
            "È sulla stessa scheda. Copia la cartella di backup su un "
            "computer per non dipendere dalla scheda." },
        { "Checking in", "Connessione in corso" },
        { "Unblocked %s", "%s sbloccato" },
        { "They can cross you again, unless they blocked you as well.",
            "Possono incrociarti di nuovo, a meno che non abbiano bloccato anche te." },

        // ---------------------------------------------------- the Mii race
        { "Four runners, one line", "Quattro corridori, una linea" },
        { "Nobody is faster than anybody. Nothing you do changes that.",
            "Nessuno è più veloce di nessuno. Nulla di ciò che fai lo cambia." },
        { "Race for free", "Gareggia gratis" },
        { "Bet 1 coin - your Mii to win", "Punta 1 moneta - il tuo Mii vince" },
        { "Predict 1st and 2nd", "Pronostica 1° e 2°" },
        { "Just to watch.", "Solo per guardare." },
        { "%u back if it comes in.", "%u indietro se va in porto." },
        { "For free, or bet 1 coin for %u back.",
            "Gratis, o punta 1 moneta per %u indietro." },
        { "Nothing to bet with.", "Non hai nulla da puntare." },
        { "Nothing to bet", "Nulla da puntare" },
        { "Ten coins arrive on each new day you open the app.",
            "Arrivano dieci monete ogni nuovo giorno in cui apri l'app." },
        { "Who comes first?", "Chi arriva primo?" },
        { "And who comes second?", "E chi arriva secondo?" },
        { "That is your call", "Questo è il tuo pronostico" },
        { "First and second, in order. Eleven for a coin if you call "
          "it, or watch for nothing.",
            "Primo e secondo, nell'ordine. Undici per una moneta se "
            "indovini, o guarda gratis." },
        { "%s to win. Now who is behind them?", "%s vince. E chi arriva dietro?" },
        { "%s first, %s second.", "%s primo, %s secondo." },
        { "race", "gareggia" },
        { "Go", "Via" },
        { "You are in front", "Sei in testa" },
        { "%s is in front", "%s è in testa" },
        { "predict again", "ripronostica" },
        { "race again", "gareggia ancora" },
        { "Called it", "L'hai indovinato" },
        { "You won", "Hai vinto" },
        { "%s won", "%s ha vinto" },
        { "Nobody", "Nessuno" },
        { "You said %s then %s - they came %s and %s.",
            "Avevi detto %s poi %s - sono arrivati %s e %s." },
        { "The bet paid %u - %u coins to spend.",
            "La puntata paga %u - %u monete da spendere." },
        { "The bet cost you a coin. %u left.",
            "La puntata ti è costata una moneta. Ne restano %u." },
        { "Nothing bet, but right is right.",
            "Nulla puntato, ma indovinato è indovinato." },
        { "Nothing bet, nothing lost.", "Nulla puntato, nulla perso." },
        { "Predict again", "Ripronostica" },
        { "Race again", "Gareggia ancora" },
        { "Bet %u coin - %u back", "Punta %u moneta - %u indietro" },
        { "1st", "1°" },
        { "2nd", "2°" },
        { "3rd", "3°" },
        { "4th", "4°" },

        // ---------------------------------------------------- the dice duel
        { "One roll each", "Un lancio per ciascuno" },
        { "Highest roll takes it. A draw hands your %u back.",
            "Vince il lancio più alto. Un pari ti restituisce le tue %u." },
        { "Roll for free", "Lancia gratis" },
        { "%u coins to play", "%u monete per giocare" },
        { "Ten arrive on each new day you open the app.",
            "Ne arrivano dieci ogni nuovo giorno in cui apri l'app." },
        { "%d all - nobody takes it", "%d pari - nessuno vince" },
        { "%d beats %d", "%d batte %d" },
        { "%d loses to %d", "%d perde contro %d" },
        { "Your %u came back. %u to spend.",
            "Le tue %u sono tornate. %u da spendere." },
        { "The bet cost you %u. %u left.",
            "La puntata ti è costata %u. Ne restano %u." },
        { "Nothing bet, and nothing decided.", "Nulla puntato, e nulla deciso." },
        { "Nothing bet, but a win is a win.",
            "Nulla puntato, ma una vittoria è una vittoria." },
        { "%u in a row", "%u di fila" },
        { "Roll again", "Rilancia" },
        { "Bet %u coins - %u back", "Punta %u monete - %u indietro" },

        // ------------------------------------------------- the lantern wheel
        { "%u coins for a spin", "%u monete per un giro" },
        { "Watch it for nothing, or put %u coins on it. Every lantern "
          "pays something and %d of the %d are a puzzle piece. You have "
          "%u.",
            "Guarda gratis, o punta %u monete. Ogni lanterna paga "
            "qualcosa e %d su %d sono un pezzo di puzzle. Ne hai %u." },
        { "Spin for nothing", "Gira gratis" },
        { "A piece of %s", "Un pezzo di %s" },
        { "The piece lantern", "La lanterna del pezzo" },
        { "The %u lantern", "La lanterna da %u" },
        { "Piece %d, and the panel will say the wheel brought it. %u "
          "coins left.",
            "Pezzo %d, e il pannello dirà che l'ha portato la ruota. "
            "Restano %u monete." },
        { "%u coins to spend. A spin costs %u.",
            "%u monete da spendere. Un giro costa %u." },
        { "Nothing was on it - that one only pays when you have staked.",
            "Non c'era nulla in gioco - quella paga solo se hai puntato." },
        { "Nothing staked, so nothing won. It would have paid %u.",
            "Nulla puntato, quindi nulla vinto. Avrebbe pagato %u." },
        { "Spin again", "Gira ancora" },
        { "Bet %u coins", "Punta %u monete" },

        // ---------------------------------------------------- the bandit
        { "A coin a spin", "Una moneta per giro" },
        { "A coin a spin, and %u to spend. X changes machines.",
            "Una moneta per giro, e %u da spendere. X cambia macchina." },
        { "THREE SYMBOLS", "TRE SIMBOLI" },
        { "FIVE SYMBOLS", "CINQUE SIMBOLI" },
        { "three symbols", "tre simboli" },
        { "five symbols", "cinque simboli" },
        { "Spin for free", "Gira gratis" },
        { "Bet %u coin", "Punta %u moneta" },
        { "Two sevens", "Due sette" },
        { "Two bells", "Due campane" },
        { "Two the same", "Due uguali" },
        { "Any two the same", "Due uguali qualsiasi" },
        { "Nothing", "Niente" },
        { "Three %s", "Tre %s" },
        { "suns", "soli" },
        { "moons", "lune" },
        { "bells", "campane" },
        { "sevens", "sette" },
        { "bars", "barre" },
        { "a line about every 3 spins", "una combinazione ogni 3 giri circa" },
        { "a line about every 4 spins", "una combinazione ogni 4 giri circa" },
        { "%u back, and %u to spend.", "%u indietro, e %u da spendere." },
        { "That coin is gone. %u left.", "Quella moneta è andata. Ne restano %u." },
        { "Nothing staked, so nothing won - it would have paid %u.",
            "Nulla puntato, quindi nulla vinto - avrebbe pagato %u." },
        { "Nothing staked, and nothing to stake it on.",
            "Nulla puntato, e nulla da puntare." },

        // ---------------------------------------------------- the Mii tower
        { "Stack them up", "Impilali" },
        { "A drops whoever is swinging. Miss the shoulders below and "
          "they fall; drift too far from the base and the lot goes "
          "over.",
            "A lascia cadere chi sta oscillando. Sbaglia le spalle sotto "
            "e cade; allontanati troppo dalla base e crolla tutto." },
        { "drop", "lascia" },
        { "lean", "inclinazione" },
        { "%d floors", "%d piani" },
        { "best %u floors", "record %u piani" },
        { "floors, best %u", "piani, record %u" },
        { "%s had nothing to stand on.", "%s non aveva nulla sotto i piedi." },
        { "It went over with %s on top.", "È crollata con %s in cima." },

        // ---------------------------------------------------- plaza dash
        { "Jump the market", "Salta il mercato" },
        { "A to jump, and hold it to jump higher. It gets quicker until "
          "you hit something.",
            "A per saltare, tienilo premuto per saltare più in alto. "
            "Accelera finché non sbatti contro qualcosa." },
        { "%u m", "%u m" },
        { "best %u m", "record %u m" },
        { "Best is %u m.", "Il record è %u m." },
        { "A new best.", "Nuovo record." },
        { "a new best", "nuovo record" },

        // ------------------------------------------- shared by the games
        { "You", "Tu" },
        { "A stranger", "Uno sconosciuto" },

        // ---------------------------------------------------- the trophies
        { "show %s", "mostra %s" },
        { "earned only", "solo ottenuti" },
        { "still to earn", "ancora da ottenere" },
        { "all of them", "tutti" },
        { "bronze", "bronzo" },
        { "silver", "argento" },
        { "gold", "oro" },
        { "platinum", "platino" },
        { "%d of %zu", "%d di %zu" },
        { "earned", "ottenuto" },
        { "earned %s", "ottenuto %s" },
        { "Nothing earned yet. Go and meet somebody.",
            "Ancora nulla di ottenuto. Va' a incontrare qualcuno." },
        { "Everything here is earned.", "Qui è tutto ottenuto." },
        { "A %s trophy.", "Un trofeo %s." },
        { "%d trophies earned", "%d trofei ottenuti" },
        { "Your record is in the trophies tab.",
            "Il tuo record è nella scheda dei trofei." },

        { "Somebody's out there", "C'è qualcuno là fuori" },
        { "Cross one other console.", "Incrocia un'altra console." },
        { "Properly introduced", "Presentazioni fatte" },
        { "Give your pass a name, a greeting and something to carry.",
            "Dai alla tua carta un nome, un saluto e qualcosa da portare." },
        { "Fully laden", "Carico a pieno" },
        { "Carry four things on your pass at once.",
            "Porta quattro cose insieme sulla tua carta." },
        { "A corner of something", "Un angolo di qualcosa" },
        { "Take your first puzzle piece off a crossing.",
            "Prendi il tuo primo pezzo di puzzle da un incrocio." },
        { "Worth keeping", "Vale la pena tenerla" },
        { "Star a card.", "Metti una carta tra i preferiti." },
        { "Ten faces", "Dieci volti" },
        { "Cross ten different consoles.", "Incrocia dieci console diverse." },
        { "A week of it", "Una settimana" },
        { "Open the app on seven different days.",
            "Apri l'app in sette giorni diversi." },
        { "Two down", "Due fatti" },
        { "Finish two puzzles.", "Completa due puzzle." },
        { "First purchase", "Primo acquisto" },
        { "Buy something in the shop.", "Compra qualcosa nel negozio." },
        { "Beginner's luck", "Fortuna del principiante" },
        { "Win a bet in the games tab.",
            "Vinci una scommessa nella scheda dei giochi." },
        { "First blood", "Primo sangue" },
        { "Win a duel at the dice.", "Vinci un duello di dadi." },
        { "Six all", "Sei pari" },
        { "Roll a six against a six.", "Fai un sei contro un sei." },
        { "Lined up", "Allineati" },
        { "Line up three of a kind at the bandit.",
            "Allinea tre simboli uguali al bandito." },
        { "The wheel's own", "Dono della ruota" },
        { "Win a puzzle piece on the lantern wheel.",
            "Vinci un pezzo di puzzle alla ruota delle lanterne." },
        { "Ten storeys", "Dieci piani" },
        { "Stack ten floors in the Mii tower.",
            "Impila dieci piani nella torre di Mii." },
        { "Dead centre", "In pieno centro" },
        { "Land a floor within six pixels of the one below.",
            "Posa un piano entro sei pixel da quello sotto." },
        { "Off the mark", "Partito" },
        { "Run a hundred metres in the plaza dash.",
            "Corri cento metri in Plaza Dash." },
        { "Your own face", "Il tuo volto" },
        { "Make a face of your own in the Mii maker.",
            "Crea un volto tutto tuo nell'editor di Mii." },
        { "Redecorated", "Ridecorata" },
        { "Give your card a look of your own.",
            "Dai alla tua carta un aspetto tutto tuo." },
        { "Out in the world", "In giro per il mondo" },
        { "Have your pass reach somebody.", "Fai arrivare la tua carta a qualcuno." },
        { "Matching outfits", "Vestiti uguali" },
        { "Cross somebody whose card wears the same look as yours.",
            "Incrocia qualcuno la cui carta ha lo stesso aspetto della tua." },
        { "Same taste", "Stessi gusti" },
        { "Cross somebody carrying something you carry too.",
            "Incrocia qualcuno che porta qualcosa che porti anche tu." },
        { "The strong silent type", "Il tipo silenzioso" },
        { "Cross a pass with nothing written on it.",
            "Incrocia una carta senza nulla scritto." },
        { "A busy afternoon", "Un pomeriggio intenso" },
        { "Cross ten consoles in one day.", "Incrocia dieci console in un giorno." },
        { "Fifty faces", "Cinquanta volti" },
        { "Cross fifty different consoles.", "Incrocia cinquanta console diverse." },
        { "A hundred faces", "Cento volti" },
        { "Cross a hundred different consoles.", "Incrocia cento console diverse." },
        { "A hundred hellos", "Cento saluti" },
        { "Cross people a hundred times, the same ones included.",
            "Incrocia gente cento volte, ripetizioni comprese." },
        { "A regular", "Un habitué" },
        { "Cross the same console ten times.",
            "Incrocia la stessa console dieci volte." },
        { "Around town", "In giro per il quartiere" },
        { "Cross people in five different places.",
            "Incrocia gente in cinque luoghi diversi." },
        { "Ten places", "Dieci luoghi" },
        { "Cross people in ten different places.",
            "Incrocia gente in dieci luoghi diversi." },
        { "The late train", "L'ultimo treno" },
        { "Cross somebody between midnight and four.",
            "Incrocia qualcuno tra mezzanotte e le quattro." },
        { "Every day of the week", "Ogni giorno della settimana" },
        { "Cross somebody on each of the seven weekdays.",
            "Incrocia qualcuno in ognuno dei sette giorni." },
        { "A fortnight", "Due settimane" },
        { "Open the app on fourteen different days.",
            "Apri l'app in quattordici giorni diversi." },
        { "An old friend", "Una vecchia conoscenza" },
        { "Keep a card for six months.", "Conserva una carta per sei mesi." },
        { "A picture at last", "Un'immagine, finalmente" },
        { "Finish a puzzle.", "Completa un puzzle." },
        { "Halfway through", "A metà strada" },
        { "Hold half of every piece there is.",
            "Possiedi la metà di tutti i pezzi esistenti." },
        { "A picture by committee", "Un'immagine a più mani" },
        { "Take pieces from ten different people.",
            "Prendi pezzi da dieci persone diverse." },
        { "A shortlist", "Una selezione" },
        { "Star twenty-five cards.", "Metti venticinque carte tra i preferiti." },
        { "Nothing left unread", "Nulla non letto" },
        { "Open every card you hold, with fifty of them.",
            "Apri tutte le carte che hai, con cinquanta di esse." },
        { "Reciprocated", "Ricambiato" },
        { "Send something back to twenty-five people.",
            "Ricambia qualcosa a venticinque persone." },
        { "Namesake", "Omonimo" },
        { "Cross somebody who chose the same name as you.",
            "Incrocia qualcuno che ha scelto il tuo stesso nome." },
        { "Somebody with a life", "Qualcuno con una vita" },
        { "Cross a pass carrying a thousand hours in one title.",
            "Incrocia una carta con mille ore su un solo gioco." },
        { "The shop's best customer", "Il miglior cliente del negozio" },
        { "Spend five hundred coins.", "Spendi cinquecento monete." },
        { "Saving up", "Salvadanaio" },
        { "Have five hundred coins at once.", "Possiedi cinquecento monete insieme." },
        { "On a run", "In serie" },
        { "Win five duels at the dice in a row.",
            "Vinci cinque duelli di dadi di fila." },
        { "A good day at the tables", "Una buona giornata ai tavoli" },
        { "Win fifty coins betting in the games tab.",
            "Vinci cinquanta monete scommettendo nella scheda dei giochi." },
        { "Sevens", "Tre sette" },
        { "Line up three sevens at the bandit.", "Allinea tre sette al bandito." },
        { "Twice lucky", "Fortunato due volte" },
        { "Win two puzzle pieces on the lantern wheel.",
            "Vinci due pezzi di puzzle alla ruota delle lanterne." },
        { "Twenty up", "Venti piani" },
        { "Stack twenty floors in the Mii tower.",
            "Impila venti piani nella torre di Mii." },
        { "Steady hands", "Mano ferma" },
        { "Land five floors in a row dead centre.",
            "Posa cinque piani di fila in pieno centro." },
        { "Talked it down", "Rimessa in piedi" },
        { "Lean a tower to the edge of going over, and bring it back.",
            "Inclina una torre sul punto di cadere e recuperala." },
        { "A good run", "Una bella corsa" },
        { "Run five hundred metres in the plaza dash.",
            "Corri cinquecento metri in Plaza Dash." },
        { "Five hundred faces", "Cinquecento volti" },
        { "Cross five hundred different consoles.",
            "Incrocia cinquecento console diverse." },
        { "A thousand faces", "Mille volti" },
        { "Cross a thousand different consoles.", "Incrocia mille console diverse." },
        { "A thousand hellos", "Mille saluti" },
        { "Cross people a thousand times, the same ones included.",
            "Incrocia gente mille volte, ripetizioni comprese." },
        { "Practically neighbours", "Praticamente vicini" },
        { "Cross the same console fifty times.",
            "Incrocia la stessa console cinquanta volte." },
        { "Far travelled", "Gran viaggiatore" },
        { "Cross people in twenty-five different places.",
            "Incrocia gente in venticinque luoghi diversi." },
        { "Fifty places", "Cinquanta luoghi" },
        { "Cross people in fifty different places.",
            "Incrocia gente in cinquanta luoghi diversi." },
        { "A month of it", "Un mese" },
        { "Open the app on thirty different days.",
            "Apri l'app in trenta giorni diversi." },
        { "A hundred days", "Cento giorni" },
        { "Open the app on a hundred different days.",
            "Apri l'app in cento giorni diversi." },
        { "A year of it", "Un anno" },
        { "Open the app on three hundred and sixty-five different days.",
            "Apri l'app in trecentosessantacinque giorni diversi." },
        { "Known you for a year", "Un anno di conoscenza" },
        { "Keep a card for a year.", "Conserva una carta per un anno." },
        { "Every picture", "Tutte le immagini" },
        { "Finish every puzzle.", "Completa tutti i puzzle." },
        { "By hand alone", "Senza comprare nulla" },
        { "Finish a puzzle without buying a single piece.",
            "Completa un puzzle senza comprare un solo pezzo." },
        { "The full set", "La collezione completa" },
        { "Line up three of a kind of every symbol the bandit has.",
            "Allinea tre uguali di ogni simbolo del bandito." },
        { "Five from the wheel", "Cinque dalla ruota" },
        { "Win five puzzle pieces on the lantern wheel.",
            "Vinci cinque pezzi di puzzle alla ruota delle lanterne." },
        { "Thirty storeys", "Trenta piani" },
        { "Stack thirty floors in the Mii tower.",
            "Impila trenta piani nella torre di Mii." },
        { "A kilometre of plaza", "Un chilometro di plaza" },
        { "Run a thousand metres in the plaza dash.",
            "Corri mille metri in Plaza Dash." },
        { "Seven in a row", "Sette di fila" },
        { "Win seven duels at the dice in a row.",
            "Vinci sette duelli di dadi di fila." },
        { "The bookmaker's problem", "L'incubo del bookmaker" },
        { "Win two hundred coins betting in the games tab.",
            "Vinci duecento monete scommettendo nella scheda dei giochi." },
        { "Fifty contributors", "Cinquanta contributori" },
        { "Take pieces from fifty different people.",
            "Prendi pezzi da cinquanta persone diverse." },
        { "The whole plaza", "Tutto il plaza" },
        { "Earn everything else.", "Ottieni tutto il resto." },

        // ------------------------------------------- settings, the rest of it
        { "following the console, currently %s", "segue la console, ora %s" },
        { "light", "chiaro" },
        { "dark", "scuro" },
        { "light by default", "chiaro per impostazione" },
        { "http://host:port of your own server", "http://host:porta del tuo server" },
        { "where this build trades passes", "dove questa versione scambia le carte" },
        { "no Wi-Fi name to match on - wired, or not connected",
            "nessun nome Wi-Fi da confrontare - via cavo o non connesso" },
        { "consoles on \"%s\" share this", "le console su \"%s\" condividono questo" },
        { "Nobody is blocked here. A asks the plaza to drop any it "
          "still has",
            "Qui non c'è nessuno bloccato. A chiede al plaza di lasciare "
            "quelli che tiene" },
        { "Nobody is blocked here. Needs the plaza, and this console is "
          "offline",
            "Qui non c'è nessuno bloccato. Serve il plaza, e questa "
            "console è offline" },
        { " - blocked %s", " - bloccato %s" },
        { ". A lets them cross you again",
            ". A permette loro di incrociarti di nuovo" },
        { ". Offline - unblocking needs the plaza",
            ". Offline - sbloccare richiede il plaza" },
        { "Clears all %zu at once, on this console and on the plaza",
            "Sblocca tutte e %zu in una volta, su questa console e sul plaza" },
        { "Offline - clearing the list needs the plaza, or the two "
          "would disagree",
            "Offline - svuotare la lista richiede il plaza, o i due non "
            "concorderebbero" },
        { "Off. Turn it on before reporting a problem, then off again",
            "Disattivato. Attivalo prima di segnalare un problema, poi rispegnilo" },
        { "plaza.log, beside your pass on the SD card - it names this "
          "console and the server",
            "plaza.log, accanto alla tua carta sulla scheda SD - contiene "
            "questa console e il server" },

        // -------------------------------------- the rest of the hint strip
        //
        // The verbs, from screens whose own words are still English: the strip
        // along the bottom is chrome, like the tabs, and reads as one thing
        // wherever you are rather than changing language with the screen.
        { "buy", "compra" },
        { "star", "preferito" },
        { "unstar", "togli preferito" },
        { "delete", "elimina" },
        { "save", "salva" },
        { "load this face", "carica questo volto" },
        { "look at it", "guardala" },
        { "look at them", "guardali" },
        { "carry it", "portalo" },
        { "put it back", "rimettilo" },
        { "trade back", "ricambia" },
        { "toggle", "cambia" },
        { "block - offline", "blocca - offline" },
        { "make my pass", "crea la mia carta" },
        { "not now", "non ora" },
        { "your details", "i tuoi dati" },
        { "your mii", "il tuo Mii" },

        // ------------------------------------------------------ how long ago
        //
        // The one place a French sentence will not take the English shape:
        // "3 days ago" puts the number in the middle, "il y a 3 jours" puts it
        // at the end, which is why relativeTime() hands the whole line to
        // format() rather than gluing a number to a word.
        { "unknown", "sconosciuto" },
        { "just now", "proprio ora" },
        { "%llum ago", "%llu min fa" },
        { "%lluh ago", "%llu h fa" },
        { "Yesterday", "Ieri" },
        { "%d days ago", "%d giorni fa" },
        { "%d %s", "%d %s" },
        { "Jan", "gen" },
        { "Feb", "feb" },
        { "Mar", "mar" },
        { "Apr", "apr" },
        { "May", "mag" },
        { "Jun", "giu" },
        { "Jul", "lug" },
        { "Aug", "ago" },
        { "Sep", "set" },
        { "Oct", "ott" },
        { "Nov", "nov" },
        { "Dec", "dic" },
        { "Sun", "dom" },
        { "Mon", "lun" },
        { "Tue", "mar" },
        { "Wed", "mer" },
        { "Thu", "gio" },
        { "Fri", "ven" },
        { "Sat", "sab" },

        // ------------------------------------------------------- the plaza
        { "the plaza - today", "il plaza - oggi" },
        { "Nobody has crossed you yet", "Nessuno ti ha ancora incrociato" },
        { "1 person crossed your path", "1 persona ti ha incrociato" },
        { "%u people crossed your path", "%u persone ti hanno incrociato" },
        { "1 pass waiting for you", "1 carta ti attende" },
        { "%u passes waiting for you", "%u carte ti attendono" },
        { "Nothing new today", "Niente di nuovo oggi" },
        { "Take the console outside, or join a busier network. Passes "
          "arrive on their own.",
            "Porta la console fuori, o entra in una rete più frequentata. "
            "Le carte arrivano da sole." },
        { "Somewhere out there.", "Da qualche parte là fuori." },
        { ", ", ", " },
        { ", and ", " e " },
        { "Unopened passes", "Carte non aperte" },
        { "nothing yet", "ancora nulla" },
        { "all caught up", "tutto letto" },
        { "%u waiting", "%u in attesa" },
        { " - oldest %s", " - la più vecchia %s" },
        { " - %u crossings, %u place", " - %u incroci, %u luogo" },
        { " - %u crossings, %u places", " - %u incroci, %u luoghi" },
        { "new", "nuovo" },
        { "hidden title", "gioco nascosto" },
        { "%s - %s", "%s - %s" },
        { "%d more", "%d in più" },
        { "The plaza is empty", "Il plaza è vuoto" },
        { "Your console trades a pass with anyone whose Switch is on "
          "the same network, or nearby on the internet. Leave it "
          "running and come back.",
            "La tua console scambia una carta con chiunque abbia la "
            "Switch sulla stessa rete, o vicino su internet. Lasciala "
            "accesa e torna dopo." },
        { "Looking for passes", "Cerco carte" },
        { "Asking the plaza who else has been around.",
            "Chiedo al plaza chi altro è passato." },

        // ------------------------------------------------------ the collection
        { "Starred %s", "%s tra i preferiti" },
        { "Unstarred %s", "%s rimosso dai preferiti" },
        { "Kept when the collection fills up.",
            "Resta quando la collezione si riempie." },
        { "No longer kept when the collection fills up.",
            "Non resta più quando la collezione si riempie." },
        { "%u %s met", "%u %s incontrate" },
        { "person", "persona" },
        { "people", "persone" },
        { "%s - %u crossings in total", "%s - %u incroci in totale" },
        { "by name", "per nome" },
        { "starred first", "preferiti prima" },
        { "most recent first", "più recenti prima" },
        { "sort by name", "ordina per nome" },
        { "sort by starred", "ordina per preferiti" },
        { "sort by recent", "ordina per data" },
        { "Nothing collected yet. The first pass you receive lands here "
          "and stays.",
            "Ancora nulla di raccolto. La prima carta che ricevi finisce "
            "qui e resta." },
        { "met %u times", "incontrato %u volte" },

        // ------------------------------------------------------- the Square
        { "Everyone you cross paths with turns up here.",
            "Tutti quelli che incroci compaiono qui." },
        { "A few of the people you have met, milling about.",
            "Alcune delle persone che hai incontrato, in giro." },

        // --------------------------------------------------------- nearby
        { "live - scanning", "in diretta - ricerca" },
        { "live - trading", "in diretta - scambio" },
        { "offline", "offline" },
        { "cannot reach the plaza", "plaza non raggiungibile" },
        { "1 console awake near you", "1 console attiva nei paraggi" },
        { "%d consoles awake near you", "%d console attive nei paraggi" },
        { "Passes exchange on their own. You do not have to sit here.",
            "Le carte si scambiano da sole. Non devi restare qui." },
        { "Nobody else has checked in here yet. Leave the app open; the "
          "plaza fills faster if you do.",
            "Qui non si è ancora registrato nessun altro. Lascia l'app "
            "aperta; il plaza si riempie più in fretta." },
        { "waiting", "in attesa" },
        { "exchanging...", "scambio..." },
        { "passed", "incrociato" },
        { "out of range", "fuori portata" },
        { "same network", "stessa rete" },
        { "nearby network", "rete vicina" },
        { "somewhere else", "altrove" },
        { "Up to %d per day while the app is open",
            "Fino a %d al giorno mentre l'app è aperta" },
        { " - matching on \"%s\"", " - confronto su \"%s\"" },
        { " - on \"%s\", no name to match",
            " - su \"%s\", nessun nome da confrontare" },

        // ----------------------------------------------------- a peer nearby
        { "awake near you", "attiva nei paraggi" },
        { "Someone", "Qualcuno" },
        { "How close", "Distanza" },
        { "Playing", "Sta giocando" },
        { "Right now", "In questo momento" },
        { "Trading passes", "Scambio di carte" },
        { "You have already crossed", "Vi siete già incrociati" },
        { "Drifted out of range", "Uscito dalla portata" },
        { "Waiting for the next round", "In attesa del prossimo giro" },
        { "Passes trade on their own with everyone in range. There is "
          "nothing to press here, and nothing to wait for.",
            "Le carte si scambiano da sole con tutti a portata. Qui non "
            "c'è nulla da premere né da attendere." },

        // -------------------------------------------------------- the puzzles
        { "Nothing to collect yet", "Ancora nulla da collezionare" },
        { "Every puzzle is finished", "Tutti i puzzle sono completati" },
        { "%d of %zu finished", "%d di %zu completati" },
        { "Every console you cross brings one piece. Pick which puzzle they go into.",
            "Ogni console che incroci porta un pezzo. Scegli in quale puzzle vanno." },
        { "filling", "in corso" },
        { "finished", "completato" },
        { "%d of %u pieces", "%d di %u pezzi" },
        { "already finished", "già completato" },
        { "already filling", "già in corso" },
        { "fill this one next", "riempi questo dopo" },
        { "%s is finished", "%s è completato" },
        { "Pieces go into the first puzzle that is not.",
            "I pezzi vanno nel primo che non lo è." },
        { "Already filling %s", "%s è già in corso" },
        { "Every crossing brings a piece of this one.",
            "Ogni incrocio porta un pezzo di questo." },
        { "Filling %s", "%s in corso" },
        { "Crossings go into this one until you pick another.",
            "Gli incroci vanno in questo finché non ne scegli un altro." },
        { "One person brought this", "Una sola persona ha portato questo" },
        { "%d people brought this", "%d persone hanno portato questo" },
        { " - finished %s", " - completato %s" },
        { "Piece %d", "Pezzo %d" },
        { "Brought by", "Portato da" },
        { "Not found yet", "Non ancora trovato" },
        { "someone", "qualcuno" },
        { "Cross someone while this puzzle is the one being filled.",
            "Incrocia qualcuno mentre questo puzzle è quello in corso." },
        { "Collected before the app started keeping track.",
            "Raccolto prima che l'app tenesse traccia." },

        // ---------------------------------------------------------- the shop
        { "%u earned - %u spent", "%u guadagnate - %u spese" },
        { "A piece you do not have yet of %s - the puzzle your "
          "crossings are filling, %d of %u so far. Twice the price, "
          "because you get to say which picture it goes into.",
            "Un pezzo di %s che non hai ancora - il puzzle che i tuoi "
            "incroci stanno riempiendo, %d su %u finora. Prezzo doppio, "
            "perché scegli tu l'immagine." },
        { "%s is finished. Choose another to fill on the puzzles "
          "screen, or take your chances with any puzzle.",
            "%s è completato. Scegline un altro da riempire nella "
            "schermata dei puzzle, o tenta la sorte con uno qualsiasi." },
        { "A piece of any puzzle", "Un pezzo di un puzzle qualsiasi" },
        { "Half the price, and you do not choose: one piece drawn from "
          "every unfinished puzzle at once - %d still to find across %d "
          "of them.",
            "Metà prezzo, e non scegli: un pezzo estratto da tutti i "
            "puzzle incompleti insieme - ne mancano %d su %d di essi." },
        { "Every puzzle is finished. There is nothing left to sell you.",
            "Tutti i puzzle sono completati. Non c'è più nulla da venderti." },
        { "Nothing on the shelf yet.", "Ancora nulla sugli scaffali." },
        { "%u more coins needed. Ten arrive on every new day you open "
          "the app.",
            "Mancano %u monete. Ne arrivano dieci ogni nuovo giorno in "
            "cui apri l'app." },
        { "sold out", "esaurito" },
        { "%u coins short", "Mancano %u monete" },
        { "Nothing to sell there", "Nulla da vendere là" },
        { "There are no pieces left to find there.",
            "Là non ci sono più pezzi da trovare." },
        { "Piece %d of %s", "Pezzo %d di %s" },
        { "%u coins left.", "Restano %u monete." },
        { "Buy %s for %u coins?", "Comprare %s per %u monete?" },
        { "%s That leaves you %u.", "%s Te ne resteranno %u." },
        { "One you do not hold yet, into the puzzle you are filling.",
            "Uno che non hai ancora, nel puzzle che stai riempiendo." },
        { "Drawn from every unfinished puzzle at once, so it may not be "
          "the one you are filling.",
            "Estratto da tutti i puzzle incompleti insieme, quindi "
            "potrebbe non essere quello in corso." },
        { "Buy it", "Compra" },

        // -------------------------------------------------------- your pass
        { "your pass", "la tua carta" },
        { "This is what they see", "Questo è ciò che vedono" },
        { "%s theme", "tema %s" },
        { "(no greeting yet)", "(ancora nessun saluto)" },
        { "Name", "Nome" },
        { "not set yet", "non impostato" },
        { "Greeting", "Saluto" },
        { "%zu of 60 characters", "%zu di 60 caratteri" },
        { "Card theme", "Tema della carta" },
        { "%s - 6 unlocked", "%s - 6 sbloccati" },
        { "What you carry", "Cosa porti" },
        { "Title on your pass", "Gioco sulla tua carta" },
        { "hidden by privacy settings", "nascosto dalle impostazioni sulla privacy" },
        { "reading the play history...", "lettura della cronologia di gioco..." },
        { "nothing played on this console yet",
            "ancora nulla giocato su questa console" },
        { "hidden", "nascosto" },
        { "%s - %uh", "%s - %u h" },
        { "edit", "modifica" },
        { "edit your mii", "modifica il Mii" },
        { "next theme", "tema successivo" },
        { "next title", "gioco successivo" },
        { "The name on your pass", "Il nome sulla tua carta" },
        { "Up to 60 characters", "Fino a 60 caratteri" },
        { "Your pass never carries your account name, your friend code, "
          "or a precise position - only what you typed and, if you "
          "allow it, the place you named.",
            "La tua carta non porta mai il nome del tuo account, il "
            "codice amico o una posizione precisa - solo ciò che hai "
            "scritto e, se lo permetti, il luogo che hai indicato." },

        // ------------------------------------------------------ what you carry
        { "on your pass", "sulla tua carta" },
        { "%zu of %d", "%zu di %d" },
        { "Four is the limit", "Quattro è il massimo" },
        { "Put something back before picking this up.",
            "Rimetti qualcosa prima di prendere questo." },

        // -------------------------------------------------------- a crossing
        { "crossed paths - %s", "vi siete incrociati - %s" },
        { "playing %s", "sta giocando a %s" },
        { "somewhere on the network", "da qualche parte in rete" },
        { "carrying", "porta" },
        { "time crossed", "volta incrociato" },
        { "times crossed", "volte incrociato" },
        { "game installed", "gioco installato" },
        { "games installed", "giochi installati" },
        { "hours played", "ore giocate" },
        { "in %s", "in %s" },
        { "Already traded back", "Già ricambiato" },
        { "Trade something back", "Ricambia qualcosa" },
        { "Take it, send something back", "Prendilo e ricambia" },
        { "Star this card", "Metti questa carta tra i preferiti" },
        { "Unstar this card", "Togli dai preferiti" },
        { "Sent something back to %s", "Qualcosa ricambiato a %s" },
        { "It travels with your pass the next time you cross.",
            "Viaggerà con la tua carta al prossimo incrocio." },
        { "Blocking has to reach the server, or they would keep "
          "receiving your pass. Try again when the dot by the tabs is "
          "green.",
            "Il blocco deve raggiungere il server, altrimenti "
            "continuerebbero a ricevere la tua carta. Riprova quando il "
            "punto accanto alle schede è verde." },
        { "Block %s?", "Bloccare %s?" },
        { "Their pass is deleted and this console can never cross you "
          "again. They are not told.",
            "La loro carta viene eliminata e quella console non potrà più "
            "incrociarti. Non vengono avvisati." },
        { "Block and forget", "Blocca e dimentica" },

        // ------------------------------------------------------- your Mii
        { "your face", "il tuo volto" },
        { "Make your Mii", "Crea il tuo Mii" },
        { "how others see you", "come ti vedono gli altri" },
        { "yes", "sì" },
        { "no", "no" },
        { "%d of %d", "%d di %d" },
        { "Face shape", "Forma del viso" },
        { "Skin tone", "Tono della pelle" },
        { "Hair", "Capelli" },
        { "Hair colour", "Colore dei capelli" },
        { "Hair flipped", "Capelli specchiati" },
        { "Eyes", "Occhi" },
        { "Eye colour", "Colore degli occhi" },
        { "Eyebrows", "Sopracciglia" },
        { "Eyebrow colour", "Colore delle sopracciglia" },
        { "Nose", "Naso" },
        { "Mouth", "Bocca" },
        { "Lip colour", "Colore delle labbra" },
        { "Glasses", "Occhiali" },
        { "Glasses colour", "Colore degli occhiali" },
        { "Moustache", "Baffi" },
        { "Beard", "Barba" },
        { "Facial hair colour", "Colore della barba" },
        { "Wrinkles", "Rughe" },
        { "Makeup", "Trucco" },
        { "Mole", "Neo" },
        { "Headwear", "Cappello" },
        { "Build", "Corporatura" },
        { "Height", "Altezza" },
        { "Favourite colour", "Colore preferito" },
        { "Eye spacing", "Distanza degli occhi" },
        { "Eye height", "Altezza degli occhi" },
        { "Eye width", "Larghezza degli occhi" },
        { "Eye height scale", "Allungamento degli occhi" },
        { "Eye tilt", "Inclinazione degli occhi" },
        { "Eyebrow spacing", "Distanza delle sopracciglia" },
        { "Eyebrow height", "Altezza delle sopracciglia" },
        { "Eyebrow width", "Larghezza delle sopracciglia" },
        { "Eyebrow thickness", "Spessore delle sopracciglia" },
        { "Eyebrow tilt", "Inclinazione delle sopracciglia" },
        { "Nose height", "Altezza del naso" },
        { "Nose size", "Dimensione del naso" },
        { "Mouth height", "Altezza della bocca" },
        { "Mouth width", "Larghezza della bocca" },
        { "Mouth thickness", "Spessore della bocca" },
        { "Moustache height", "Altezza dei baffi" },
        { "Moustache size", "Dimensione dei baffi" },
        { "Beard height", "Altezza della barba" },
        { "Beard size", "Dimensione della barba" },
        { "Glasses height", "Altezza degli occhiali" },
        { "Glasses size", "Dimensione degli occhiali" },
        { "Mole across", "Neo in orizzontale" },
        { "Mole down", "Neo in verticale" },
        { "Mole size", "Dimensione del neo" },

        // -------------------------------------------------- faces on the card
        { "faces on the sd card", "volti sulla scheda sd" },
        { "Save and load", "Salva e carica" },
        { "Save this face...", "Salva questo volto..." },
        { "Name this face", "Dai un nome a questo volto" },
        { "Needs a name", "Serve un nome" },
        { "That name has nothing in it a file can be called.",
            "In quel nome non c'è nulla con cui chiamare un file." },
        { "Saved", "Salvato" },
        { "%s is in the export folder.", "%s è nella cartella di esportazione." },
        { "Not saved", "Non salvato" },
        { "Replace %s?", "Sostituire %s?" },
        { "There is already a face saved under that name. Replacing it "
          "cannot be undone.",
            "C'è già un volto salvato con quel nome. Sostituirlo non si "
            "può annullare." },
        { "Replace", "Sostituisci" },
        { "Delete %s?", "Eliminare %s?" },
        { "It is removed from the SD card for good. Anyone you sent it "
          "to still has their copy.",
            "Viene rimosso dalla scheda SD per sempre. Chi l'ha ricevuto "
            "conserva la sua copia." },
        { "Delete", "Elimina" },
        { "Deleted", "Eliminato" },
        { "%s is gone from the export folder.",
            "%s è scomparso dalla cartella di esportazione." },
        { "Not deleted", "Non eliminato" },
        { "Cannot load that one", "Non si può caricare quello" },
        { "Not a face this version can read",
            "Non è un volto che questa versione sappia leggere" },
        { "Nothing saved yet. Faces you save show up here, and so does "
          "anything you drop into the folder yourself.",
            "Ancora nulla salvato. I volti che salvi compaiono qui, come "
            "tutto ciò che metti tu nella cartella." },

        // --------------------------------------------------------- first run
        { "Leave it open.", "Lasciala aperta." },
        { "While this is open, your console swaps a small pass with the "
          "others that are open too - a face, a greeting, whatever you "
          "chose to carry. Who you meet is whoever is awake within the "
          "reach you set.",
            "Mentre questo è aperto, la tua console scambia una piccola "
            "carta con le altre aperte - un volto, un saluto, ciò che hai "
            "scelto di portare. Incroci chi è attivo entro la portata che "
            "imposti." },
        { "Make your pass - a face, a greeting, one thing to trade",
            "Crea la tua carta - un volto, un saluto, una cosa da scambiare" },
        { "Leave it open; it checks in on its own",
            "Lasciala aperta; si connette da sola" },
        { "Open the plaza and see who you crossed",
            "Apri il plaza e guarda chi hai incrociato" },
        { "A greeting, up to 60 characters", "Un saluto, fino a 60 caratteri" },
        { "pair this console", "abbina questa console" },
        { "A picture of this console's id. It lives on the SD card, is "
          "tied to nothing about the hardware, and you can throw it "
          "away.",
            "Un'immagine dell'id di questa console. Vive sulla scheda SD, "
            "non è legata a nulla dell'hardware e puoi buttarla." },

        // ------------------------------------------- updates, and the app itself
        { "Version %s is out", "La versione %s è uscita" },
        { "Settings -> About -> Check for updates to install it.",
            "Impostazioni -> Informazioni -> Cerca aggiornamenti per installarla." },
        { "Puzzle art downloaded", "Immagini scaricate" },
        { "Restart the app to see the pictures.",
            "Riavvia l'app per vedere le immagini." },
        { "Update installed", "Aggiornamento installato" },
        { "Restart from Settings -> \"About\" to run version %s.",
            "Riavvia da Impostazioni -> \"Informazioni\" per usare la versione %s." },
        { "Up to date", "Aggiornato" },
        { "%s is the latest release.", "%s è l'ultima versione." },
        { "Could not download puzzle art", "Impossibile scaricare le immagini" },
        { "Could not check for updates", "Impossibile cercare aggiornamenti" },
        { "Install version %s?", "Installare la versione %s?" },
        { "The new version is downloaded, checked, and only then "
          "written over this one. The copy you are running now is kept "
          "until the new one has been verified.",
            "La nuova versione viene scaricata, verificata e solo dopo "
            "scritta sopra questa. La copia in esecuzione resta finché la "
            "nuova non è verificata." },
        { "Install", "Installa" },
        { "Restart into version %s?", "Riavviare con la versione %s?" },
        { "The app closes and opens again on the new version. Your "
          "passes and your collection are untouched.",
            "L'app si chiude e si riapre sulla nuova versione. Le tue "
            "carte e la tua collezione restano intatte." },
        { "Restart", "Riavvia" },
        { "%s passed you", "%s ti ha incrociato" },
        { "%s and %zu others passed you", "%s e altri %zu ti hanno incrociato" },
        { "%zu new passes", "%zu nuove carte" },
        { "a piece of %s", "un pezzo di %s" },
        { "%d pieces of %s", "%d pezzi di %s" },
        { "one of them is carrying %s", "uno di loro porta %s" },
        { "Open the plaza to see who.", "Apri il plaza per vedere chi." },
        { "Keep everything", "Tieni tutto" },

        // ------------------------------------------- settings, the dialogs
        { "Where are you? A district, a station, a shop",
            "Dove sei? Un quartiere, una stazione, un negozio" },
        { "Which city", "Quale città" },
        { "Plaza server address", "Indirizzo del server del plaza" },
        { "Clear any block the plaza still has?",
            "Cancellare i blocchi che il plaza ha ancora?" },
        { "Clear all %zu?", "Sbloccare tutte e %zu?" },
        { "This console has none listed, but the plaza keeps its own "
          "copy and a restored backup can leave the two disagreeing. "
          "Nothing happens if it has none either.",
            "Questa console non ne elenca nessuna, ma il plaza tiene la "
            "propria copia e un backup ripristinato può farli discordare. "
            "Se non ne ha nemmeno lui, non accade nulla." },
        { "Every console you have blocked can cross you again, except "
          "any that blocked you as well. Their old passes are not "
          "coming back; only the block is lifted.",
            "Ogni console che hai bloccato potrà incrociarti di nuovo, "
            "tranne quelle che hanno bloccato anche te. Le loro vecchie "
            "carte non tornano; si toglie solo il blocco." },
        { "Clear them", "Sbloccali" },
        { "Block list cleared", "Lista dei blocchi svuotata" },
        { "This console has none left, and the plaza has been asked to "
          "drop the blocks it was holding for you.",
            "Questa console non ne ha più, e al plaza è stato chiesto di "
            "lasciare i blocchi che teneva per te." },
        { "Delete every pass?", "Eliminare tutte le carte?" },
        { "Every pass you have collected is removed from this console. "
          "Your own pass and your identity stay.",
            "Ogni carta che hai raccolto viene rimossa da questa console. "
            "La tua carta e la tua identità restano." },
        { "Delete them all", "Elimina tutte" },
        { "Collection cleared", "Collezione svuotata" },
        { "The plaza is empty again.", "Il plaza è di nuovo vuoto." },
        { "Start over as someone new?", "Ricominciare come qualcun altro?" },
        { "This console gets a brand new id. Passes you already handed "
          "out can no longer be linked to you, and your collection is "
          "deleted.",
            "Questa console riceve un id nuovo. Le carte già distribuite "
            "non potranno più essere collegate a te, e la tua collezione "
            "viene eliminata." },
        { "Start over", "Ricomincia" },
        { "You are someone new", "Sei qualcun altro" },
        { "Your code is now %s", "Il tuo codice ora è %s" },

        // ------------------------------------------- what the plaza is doing
        //
        // These come off the sync and update threads, and are read back on
        // screen in Settings and in Nearby. Whole sentences are translated;
        // the protocol diagnostics they sometimes carry - an HTTP status, a
        // libnx result code - stay as they are, because they exist to be
        // pasted into a bug report.
        { "Trading passes...", "Scambio delle carte..." },
        { "Connected over LAN: matching by network area only.",
            "Connesso via LAN: confronto solo per area di rete." },
        { "Nobody else is awake here yet.", "Qui non c'è ancora nessun altro attivo." },
        { "No plaza server set yet. Settings > Plaza server.",
            "Nessun server del plaza impostato. Impostazioni > Server del plaza." },
        { "Server sent something that was not JSON",
            "Il server ha inviato qualcosa che non era JSON" },
        { "Server said %ld on %s", "Il server ha risposto %ld su %s" },
        { "Server said %ld on hello", "Il server ha risposto %ld su hello" },
        { "Checking for updates", "Ricerca aggiornamenti" },
        { "Downloading", "Download in corso" },
        { "Unpacking", "Estrazione" },
        { "Installing", "Installazione" },
        { "nx-plaza %s is the latest version.", "nx-plaza %s è l'ultima versione." },
        { "Release %s has no .nro to install.",
            "La versione %s non ha alcun .nro da installare." },
        { "Version %s is available.", "La versione %s è disponibile." },
        { "The download is version %s, not %s.",
            "Il download è la versione %s, non la %s." },
        { "Version %s is installed. Restart to run it.",
            "La versione %s è installata. Riavvia per usarla." },
        { "%d puzzle pictures downloaded. Restart to see them.",
            "%d immagini dei puzzle scaricate. Riavvia per vederle." },

        // ------------------------------------------- the last of the settings
        { "Asking GitHub for the latest release", "Chiedo a GitHub l'ultima versione" },
        { "Press A to download and install it",
            "Premi A per scaricarla e installarla" },
        { "Press A to restart into it", "Premi A per riavviare con essa" },
        { "You are on the latest release", "Hai l'ultima versione" },
        { "up to date", "aggiornato" },
        { "Looks at the releases on GitHub", "Controlla le versioni su GitHub" },
        { "If the puzzles show numbered squares, get the pictures here "
          "and restart",
            "Se i puzzle mostrano caselle numerate, scarica qui le "
            "immagini e riavvia" },
        { "failed", "non riuscito" },
        { "Somebody", "Qualcuno" },
        { "keep everything", "tieni tutto" },
        { "switch tab", "cambia scheda" },

        // ------------------------------------------------- the puzzle pictures
        { "Forest in the Rain", "Bosco nella pioggia" },
        { "Mountain in the Fog", "Montagna nella nebbia" },
        { "Mystical Swamp", "Palude mistica" },
        { "Old Farm", "Vecchia fattoria" },
        { "Castle Blue", "Castello blu" },
        { "Beach at Dusk", "Spiaggia al crepuscolo" },

        // --------------------------------------------------- the card themes
        { "Amber lantern", "Lanterna d'ambra" },
        { "Dusk market", "Mercato al crepuscolo" },
        { "Tidepool", "Pozza di marea" },
        { "Paper lantern", "Lanterna di carta" },
        { "Rose market", "Mercato rosa" },
        { "Night express", "Espresso notturno" },

        // ----------------------------------------------- the pass you start with
        { "Traveller", "Viaggiatore" },
        { "Just passing through.", "Sono solo di passaggio." },

        // ------------------------------------------- what the plaza is saying
        { "Looking around...", "Sto guardando in giro..." },
        { "Publishing your pass...", "Pubblicazione della tua carta..." },
        { "Blocking a console...", "Blocco di una console..." },
        { "Unblocking a console...", "Sblocco di una console..." },
        { "Clearing the block list...", "Svuotamento della lista dei blocchi..." },
        { "Asking the server to forget us...",
            "Chiediamo al server di dimenticarci..." },
        { "Daily crossing limit reached. Back tomorrow.",
            "Limite di incroci del giorno raggiunto. A domani." },
        { "Networking is unavailable.", "La rete non è disponibile." },
        { "No internet connection.", "Nessuna connessione a internet." },

        // ------------------------------------------- when an update goes wrong
        { "This console would not start the update worker.",
            "Questa console non ha avviato il processo di aggiornamento." },
        { "The release list could not be read.",
            "Non è stato possibile leggere l'elenco delle versioni." },
        { "The release list carried no version.",
            "L'elenco delle versioni non conteneva alcuna versione." },
        { "The download did not finish: %s", "Il download non è terminato: %s" },
        { "The downloaded archive held no nx-plaza build.",
            "L'archivio scaricato non conteneva alcuna versione di nx-plaza." },
        { "The downloaded file is not a valid nx-plaza build.",
            "Il file scaricato non è una versione valida di nx-plaza." },
        { "This build does not know its own path, so it cannot replace "
          "itself.",
            "Questa versione non conosce il proprio percorso, quindi non "
            "può sostituirsi." },
        { "The current version could not be backed up.",
            "Non è stato possibile salvare la versione attuale." },
        { "The update could not be written over the current one - %s",
            "Non è stato possibile scrivere l'aggiornamento sopra l'attuale - %s" },
        { "The installed update did not verify, so it was rolled back.",
            "L'aggiornamento installato non ha superato la verifica ed è "
            "stato annullato." },
        { "That release publishes no puzzle art.",
            "Quella versione non pubblica immagini dei puzzle." },
        { "That release's archive holds no puzzle art.",
            "L'archivio di quella versione non contiene immagini dei puzzle." },
        { "The puzzle art that arrived was not readable.",
            "Le immagini arrivate non erano leggibili." },
        { "The folder for the puzzle art could not be made.",
            "Non è stato possibile creare la cartella per le immagini." },
        { "The puzzle art could not be written - %s",
            "Non è stato possibile scrivere le immagini - %s" },

        // ------------------------------------------ the settings sections
        //
        // The eight names down the left of the screen, and the pills on the
        // rows that offer a choice.
        { "Privacy", "Privacy" },
        { "Exchange", "Scambio" },
        { "Appearance", "Aspetto" },
        { "Languages", "Lingue" },
        { "This console", "Questa console" },
        { "Data", "Dati" },
        { "About", "Informazioni" },
        { "Off", "No" },
        { "District", "Quartiere" },
        { "City", "Città" },
        { "Same network", "Stessa rete" },
        { "Anywhere", "Ovunque" },
        { "Light", "Chiaro" },
        { "Dark", "Scuro" },

        // -------------------------------------- when the SD card says no
        { "Could not make the export folder on the SD card.",
            "Non è stato possibile creare la cartella di esportazione "
            "sulla scheda SD." },
        { "Could not write to the SD card.",
            "Non è stato possibile scrivere sulla scheda SD." },
        { "That file could not be read.", "Non è stato possibile leggere quel file." },
        { "That is not a face this app saved.",
            "Non è un volto salvato da questa app." },
        { "That face was saved by a different version of the app.",
            "Quel volto è stato salvato da un'altra versione dell'app." },
        { "Could not delete that file from the SD card.",
            "Non è stato possibile eliminare quel file dalla scheda SD." },
        { "could not make the backup folder",
            "non è stato possibile creare la cartella di backup" },
        { "could not copy %s", "non è stato possibile copiare %s" },
        { "there was nothing to back up", "non c'era nulla da salvare" },

        // ------------------------------------------------- the same in French
        //
        // Listed on purpose rather than left out, so the scanner can tell a
        // word that needs no translation from one nobody has looked at yet.
        // tr() drops these rows: falling back to the English is the same
        // answer, and cheaper.
        { "Plaza", "Plaza" },
        { "Collection", "Collezione" },
        { "collection", "collezione" },
        { "Puzzles", "Puzzle" },
        { "puzzles", "puzzle" },
        { "plaza dash", "plaza dash" },
        { "sections", "sezioni" },
        { "m", "m" },
        { "-", "-" },
        { "%d", "%d" },
        { "%zu, %.0f%%", "%zu, %.0f%%" },
        { "Notifications", "Notifiche" },
        { "Console", "Console" },
        { "nx-plaza ", "nx-plaza " },
        { "(none)", "(nessuno)" },
        { "NX Plaza - Online StreetPass | ", "NX Plaza - Online StreetPass | " },
        { "https://github.com/Insektaure/NX-Plaza",
            "https://github.com/Insektaure/NX-Plaza" },
    };

} // namespace

Catalog italianCatalog()
{
    return Catalog { kEntries, sizeof(kEntries) / sizeof(kEntries[0]) };
}

} // namespace nxp
