#---------------------------------------------------------------------------------
# nx-plaza / Crossings -- Nintendo Switch homebrew
#
# Build requirements (devkitPro pacman):
#   dkp-pacman -S switch-dev deko3d switch-curl switch-freetype switch-jansson switch-mbedtls
#
# Targets:
#   make            release build (nx-plaza.nro)
#   make DEBUG=1    debug build (links -ldeko3dd, deko3d validation layer)
#   make clean
#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro")
endif

TOPDIR ?= $(CURDIR)
include $(DEVKITPRO)/libnx/switch_rules

#---------------------------------------------------------------------------------
TARGET      :=  nx-plaza
BUILD       :=  build
# devkitPro's rules flatten these by basename and find them through VPATH, so
# two .cpp files with the same name in different directories collide into one
# object and one of them is silently dropped. Keep basenames unique across the
# whole tree (this is why the Mii drawing code is mii_render.cpp, not mii.cpp).
SOURCES     :=  source source/core source/gfx source/net source/platform source/scenes source/ui
DATA        :=  data
INCLUDES    :=  source
ROMFS       :=  romfs

# GLSL lives outside SOURCES so it does not get picked up as compilable code
SHADER_DIR  :=  shaders
# Output folder for autogenerated files inside romfs
OUT_SHADERS :=  shaders

APP_TITLE   :=  NX Plaza - Online StreetPass
APP_AUTHOR  :=  Insektaure
APP_VERSION :=  0.1.1

# The plaza this build talks to.
#
# Compiled in rather than typed by the user: a released build has one plaza and
# the address is not a setting. A DEBUG=1 build makes it editable again in
# Settings, which is how you point a console at a plaza on your own machine.
PLAZA_SERVER := https://api.nxplaza.net

# Where the updater looks for releases.
PLAZA_REPO := Insektaure/NX-Plaza

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------
ARCH    :=  -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE

PKGCONF :=  $(DEVKITPRO)/portlibs/switch/bin/aarch64-none-elf-pkg-config
# minizip for the updater, which has to open a release published as a zip;
# zlib comes with it, and the play-history NACP inflate uses that too.
PORT_CFLAGS :=  $(shell $(PKGCONF) freetype2 jansson libcurl minizip zlib --cflags)
PORT_LIBS   :=  $(shell $(PKGCONF) freetype2 jansson libcurl minizip zlib --libs)

# Single-quoted around the double quotes, so a value containing a space stays
# one argument. Written as \"...\" it does not: APP_TITLE of "NX Plaza" reached
# the compiler as two arguments and failed with "missing terminating character".
DEFINES :=  -DAPP_VERSION='"$(APP_VERSION)"' \
            -DAPP_TITLE='"$(APP_TITLE)"' \
            -DPLAZA_SERVER='"$(PLAZA_SERVER)"' \
            -DPLAZA_REPO='"$(PLAZA_REPO)"'

CFLAGS  :=  -g -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -O2 -ffunction-sections \
            $(ARCH) $(DEFINES)

CFLAGS  +=  $(INCLUDE) $(PORT_CFLAGS) -D__SWITCH__

CXXFLAGS    := $(CFLAGS) -std=gnu++17 -fno-exceptions -fno-rtti

ASFLAGS :=  -g $(ARCH)
LDFLAGS =   -specs=$(DEVKITPRO)/libnx/switch.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)

ifeq ($(DEBUG),1)
    DEKO3D_LIB := -ldeko3dd
    CFLAGS     += -DNXP_DEBUG
else
    DEKO3D_LIB := -ldeko3d
endif

# curl on devkitPro is built against mbedtls; the .pc file does not advertise it
LIBS    :=  $(DEKO3D_LIB) $(PORT_LIBS) -lmbedtls -lmbedx509 -lmbedcrypto -lnx

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS :=  $(PORTLIBS) $(LIBNX)

#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT   :=  $(CURDIR)/$(TARGET)
export TOPDIR   :=  $(CURDIR)

export VPATH    :=  $(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
            $(foreach dir,$(DATA),$(CURDIR)/$(dir)) \
            $(CURDIR)/$(SHADER_DIR)

export DEPSDIR  :=  $(CURDIR)/$(BUILD)

CFILES      :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES    :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
SFILES      :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
GLSLFILES   :=  $(notdir $(wildcard $(SHADER_DIR)/*.glsl))
BINFILES    :=  $(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
    export LD   :=  $(CC)
else
    export LD   :=  $(CXX)
endif
#---------------------------------------------------------------------------------

export OFILES_BIN   :=  $(addsuffix .o,$(BINFILES))
export OFILES_SRC   :=  $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
export OFILES       :=  $(OFILES_BIN) $(OFILES_SRC)
export HFILES_BIN   :=  $(addsuffix .h,$(subst .,_,$(BINFILES)))

ifneq ($(strip $(ROMFS)),)
    ROMFS_TARGETS :=
    ROMFS_FOLDERS :=
    ifneq ($(strip $(OUT_SHADERS)),)
        ROMFS_SHADERS := $(ROMFS)/$(OUT_SHADERS)
        ROMFS_TARGETS += $(patsubst %.glsl, $(ROMFS_SHADERS)/%.dksh, $(GLSLFILES))
        ROMFS_FOLDERS += $(ROMFS_SHADERS)
    endif

    export ROMFS_DEPS := $(foreach file,$(ROMFS_TARGETS),$(CURDIR)/$(file))
endif

export INCLUDE  :=  $(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
            $(foreach dir,$(LIBDIRS),-I$(dir)/include) \
            -I$(CURDIR)/$(BUILD)

export LIBPATHS :=  $(foreach dir,$(LIBDIRS),-L$(dir)/lib)

ifeq ($(strip $(ICON)),)
    icons := $(wildcard *.jpg)
    ifneq (,$(findstring $(TARGET).jpg,$(icons)))
        export APP_ICON := $(TOPDIR)/$(TARGET).jpg
    else
        ifneq (,$(findstring icon.jpg,$(icons)))
            export APP_ICON := $(TOPDIR)/icon.jpg
        endif
    endif
else
    export APP_ICON := $(TOPDIR)/$(ICON)
endif

ifeq ($(strip $(NO_ICON)),)
    export NROFLAGS += --icon=$(APP_ICON)
endif

ifeq ($(strip $(NO_NACP)),)
    export NROFLAGS += --nacp=$(CURDIR)/$(TARGET).nacp
endif

ifneq ($(APP_TITLEID),)
    export NACPFLAGS += --titleid=$(APP_TITLEID)
endif

ifneq ($(ROMFS),)
    export NROFLAGS += --romfsdir=$(CURDIR)/$(ROMFS)
endif

.PHONY: all clean

#---------------------------------------------------------------------------------
all: $(ROMFS_TARGETS) | $(BUILD)
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile

$(BUILD):
	@mkdir -p $@

ifneq ($(strip $(ROMFS_TARGETS)),)

$(ROMFS_TARGETS): | $(ROMFS_FOLDERS)

$(ROMFS_FOLDERS):
	@mkdir -p $@

$(ROMFS_SHADERS)/%_vsh.dksh: %_vsh.glsl
	@echo {vert} $(notdir $<)
	@uam -s vert -o $@ $<

$(ROMFS_SHADERS)/%_fsh.dksh: %_fsh.glsl
	@echo {frag} $(notdir $<)
	@uam -s frag -o $@ $<

$(ROMFS_SHADERS)/%.dksh: %.glsl
	@echo {comp} $(notdir $<)
	@uam -s comp -o $@ $<

endif

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(ROMFS_FOLDERS) $(TARGET).nro $(TARGET).nacp $(TARGET).elf

#---------------------------------------------------------------------------------
else
.PHONY:	all

DEPENDS	:=	$(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
all	:	$(OUTPUT).nro

ifeq ($(strip $(NO_NACP)),)
$(OUTPUT).nro	:	$(OUTPUT).elf $(OUTPUT).nacp $(ROMFS_DEPS)
else
$(OUTPUT).nro	:	$(OUTPUT).elf $(ROMFS_DEPS)
endif

$(OUTPUT).elf	:	$(OFILES)

$(OFILES_SRC)	: $(HFILES_BIN)

-include $(DEPENDS)

#---------------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------------
