#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write source/core/lang_<code>.cpp for every language after French.

The French file is the template. This reads it for the shape - its section
comments, its order, the blank lines between its groups - and writes each of
the other seven in exactly that shape, with the translations from
tools/lang_data.py. Two languages can then be read side by side, and a string
sits in the same place in all eight files.

    tools/gen_lang_tables.py

French itself is hand-written: it carries its own notes about the choices it
makes (le plaza against la place, carte for a pass, pièce de puzzle never
shortened), and it is the source of the layout everything else follows.

A key with no translation yet is left out of that language's file, where tr()
falls back to the English. `tools/i18n_scan.py --all` says how far each
language has got.
"""

import io
import os
import re
import signal
import sys

# Piping into head should end quietly rather than in a traceback - and, worse,
# rather than stopping halfway through the seven files.
try:
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
except (AttributeError, ValueError):
    pass

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lang_data import ORDER, ROWS  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "source", "core")
TEMPLATE = os.path.join(SOURCE, "lang_fr.cpp")

NAMES = {
    "de": ("German", "germanCatalog"),
    "es": ("Spanish", "spanishCatalog"),
    "it": ("Italian", "italianCatalog"),
    "nl": ("Dutch", "dutchCatalog"),
    "pt": ("Portuguese", "portugueseCatalog"),
    "ru": ("Russian", "russianCatalog"),
    "ja": ("Japanese", "japaneseCatalog"),
}

LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')
ROW_START = re.compile(r"^\s*\{\s*\"")
SECTION = re.compile(r"^\s*// -{2,}")

HEADER = '''#include "core/i18n.h"

// %(name)s.
//
// Generated by tools/gen_lang_tables.py from tools/lang_data.py, in the shape
// of lang_fr.cpp - same sections, same order - so any two languages can be
// read side by side. Edit the table, not this file.
//
// Left column: the English exactly as it is written in the code, which is the
// key. Reword a line in a scene and the row here stops matching in silence,
// which is what `tools/i18n_scan.py --lang %(code)s` is for. A string this
// language has not been given yet is simply absent, and comes out in English.

namespace nxp {
namespace {

    const Translation kEntries[] = {'''

FOOTER = '''    };

} // namespace

Catalog %(fn)s()
{
    return Catalog { kEntries, sizeof(kEntries) / sizeof(kEntries[0]) };
}

} // namespace nxp
'''


def unescape(text):
    return (text.replace("\\n", "\n").replace('\\"', '"')
                .replace("\\t", "\t").replace("\\\\", "\\"))


def escape(text):
    return (text.replace("\\", "\\\\").replace('"', '\\"')
                .replace("\n", "\\n").replace("\t", "\\t"))


def read_template():
    """The French file as a list of ('comment', text) and ('row', key)."""
    shape = []
    lines = io.open(TEMPLATE, encoding="utf-8").read().split("\n")
    inside = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if not inside:
            if "const Translation kEntries[]" in line:
                inside = True
            i += 1
            continue
        if line.strip() == "};":
            break
        if SECTION.match(line):
            block = [line]
            # A section heading can carry a note under it; keep the whole run.
            while i + 1 < len(lines) and lines[i + 1].strip().startswith("//"):
                i += 1
                block.append(lines[i])
            shape.append(("comment", "\n".join(block)))
        elif not line.strip():
            shape.append(("blank", ""))
        elif ROW_START.match(line):
            # A row can run over several lines; the key is its first literals,
            # up to the comma that ends the first argument.
            row = line
            while row.count('"') % 2 or not row.rstrip().endswith("},"):
                i += 1
                row += "\n" + lines[i]
            first = row[row.index("{") + 1:]
            depth = 0
            key_src = ""
            for ch_index, ch in enumerate(first):
                if ch == '"':
                    depth += 1
                if ch == "," and depth % 2 == 0:
                    key_src = first[:ch_index]
                    break
            shape.append(("row", unescape("".join(LITERAL.findall(key_src)))))
        i += 1
    return shape


def emit_row(source, target, width=88):
    src, dst = escape(source), escape(target)
    one = '        { "%s", "%s" },' % (src, dst)
    if len(one) <= width:
        return one
    two = '        { "%s",\n            "%s" },' % (src, dst)
    if max(len(part) for part in two.split("\n")) <= width:
        return two

    def wrap(text, room, indent):
        parts, line = [], ""
        for word in text.split(" "):
            piece = (line + " " + word) if line else word
            if len(piece) > room and line:
                parts.append(line + " ")
                line = word
            else:
                line = piece
        if line:
            parts.append(line)
        return ("\n" + indent).join('"%s"' % part for part in parts)

    return "        { %s,\n            %s }," % (
        wrap(src, 60, " " * 10), wrap(dst, 60, " " * 12))


def main():
    shape = read_template()
    keys = [key for kind, key in shape if kind == "row"]
    unknown = [key for key in ROWS if key not in keys]
    if unknown:
        print("lang_data.py has %d rows the French file does not:" % len(unknown),
              file=sys.stderr)
        for key in sorted(unknown)[:10]:
            print("  %s" % escape(key), file=sys.stderr)

    for index, code in enumerate(ORDER):
        name, fn = NAMES[code]
        out = [HEADER % {"name": name, "code": code}]
        pending_comment = None
        pending_blank = False
        wrote_since_comment = 0
        wrote_any = False
        for kind, value in shape:
            if kind == "comment":
                pending_comment = value
                wrote_since_comment = 0
                continue
            if kind == "blank":
                pending_blank = True
                continue
            target = ROWS.get(value, ("",) * len(ORDER))[index]
            if not target:
                continue
            if pending_comment is not None:
                # A blank line before a section, but not one at the very top:
                # the header already ends in one.
                if out[-1].strip() and wrote_any:
                    out.append("")
                out.append(pending_comment)
                pending_comment = None
            elif pending_blank and wrote_since_comment:
                out.append("")
            pending_blank = False
            out.append(emit_row(value, target))
            wrote_since_comment += 1
            wrote_any = True
        out.append(FOOTER % {"fn": fn})
        path = os.path.join(SOURCE, "lang_%s.cpp" % code)
        io.open(path, "w", encoding="utf-8").write("\n".join(out))
        done = sum(1 for key in keys if ROWS.get(key, ("",) * 7)[index])
        print("lang_%s.cpp: %d of %d" % (code, done, len(keys)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
