#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes SHADOWS.md: the name of every shadow in the tower.

A port of shadowName() in source/core/quest_rules.cpp, kept literal so the two
can be compared line by line. The point of having it outside the app is that
999 invented words want reading by a person before anybody meets one: a
syllable table is a small machine for accidentally spelling something.

    tools/shadow_names.py            rewrite SHADOWS.md
    tools/shadow_names.py --check    fail if it is out of date
    tools/shadow_names.py --screen   just the check for real words

If the numbers here and the numbers in quest_rules.cpp ever disagree,
quest_rules.cpp is the one that is right.
"""

import argparse
import io
import os
import sys

HEAD = ["Var", "Mor", "Kel", "Thas", "Ru", "Sel", "Bran", "Oth",
        "Ny", "Dre", "Iss", "Gorm", "Ael", "Vex", "Tor", "Umb"]
MID = ["", "a", "en", "i", "ul", "or", "esh", "ya",
       "o", "ae", "is", "ur", "aer", "av", "yn", "ou"]
TAIL = ["ka", "dros", "eth", "un", "mir", "sha", "ax", "il",
        "rok", "ven", "tha", "os", "zar", "neth", "gorn", "ric"]

FLOORS = 999
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "SHADOWS.md")

# Not a moral position, just a net: a syllable machine will eventually spell
# something, and it is cheaper to know which floor it is than to be told.
BAD = ["ass", "arse", "cul", "con", "sex", "tit", "cock", "dick", "piss",
       "shit", "merde", "fuck", "fick", "puta", "cazzo", "kurwa", "nazi",
       "hitler", "isis", "rape", "kill", "hure", "bite", "pute", "negro",
       "nigg", "jew", "gay", "homo", "anal", "porn", "chier", "salop",
       "encul", "vagin", "penis", "sperm", "caca", "pipi", "pedo", "dumm",
       "idiot", "crap", "damn", "satan"]


def name_for(floor):
    """The same four-round Feistel the app uses. Every round is invertible, so
    this is a permutation and no two floors ever share a name."""
    x = min(4095, max(1, floor))
    left, right = (x >> 6) & 63, x & 63
    for key in (0x2D, 0x17, 0x3B, 0x09):
        left, right = right, left ^ (((right * 29 + key) ^ (right >> 2)) & 63)
    i = ((left << 6) | right) & 4095
    return HEAD[i & 15] + MID[(i >> 4) & 15] + TAIL[(i >> 8) & 15]


def screen(names):
    """Anything that reads as a real word, in any of the obvious ways."""
    flagged = [(f, n) for f, n in names.items()
               if any(b in n.lower() for b in BAD)]
    try:
        with open("/usr/share/dict/words") as f:
            words = set(w.strip().lower() for w in f)
        flagged += [(f, n) for f, n in names.items() if n.lower() in words]
    except OSError:
        pass
    return sorted(set(flagged))


def render(names):
    rows = 250
    out = [
        "# The shadows",
        "",
        "Every floor of the quest has the same shadow on every console, with the",
        "same face and the same name: both are worked out from the floor number",
        "alone. This is the whole list, so it can be read before anybody meets one.",
        "",
        "The name is three syllables from three tables of sixteen, picked by a",
        "four-round Feistel permutation of the floor - which is why no two floors",
        "share a name. They are invented proper nouns, so they are the same in all",
        "twelve languages.",
        "",
        "Generated by `tools/shadow_names.py`, which is the same arithmetic as",
        "`shadowName()` in `source/core/quest_rules.cpp`.",
        "",
        "| floor | name | floor | name | floor | name | floor | name |",
        "| ---: | --- | ---: | --- | ---: | --- | ---: | --- |",
    ]
    for r in range(rows):
        cells = []
        for c in range(4):
            f = r + 1 + c * rows
            cells.append("%d | %s" % (f, names[f]) if f <= FLOORS else " | ")
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if out of date")
    ap.add_argument("--screen", action="store_true", help="only screen the names")
    args = ap.parse_args()

    names = {f: name_for(f) for f in range(1, FLOORS + 1)}
    if len(set(names.values())) != FLOORS:
        print("the permutation repeated itself, which it cannot do")
        return 2

    flagged = screen(names)
    for floor, name in flagged:
        print("floor %d: %s" % (floor, name))
    if args.screen:
        print("%d flagged of %d" % (len(flagged), FLOORS))
        return 1 if flagged else 0

    body = render(names)
    if args.check:
        current = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != body:
            print("SHADOWS.md is out of date; run tools/shadow_names.py")
            return 1
        print("SHADOWS.md is up to date (%d names, %d flagged)"
              % (FLOORS, len(flagged)))
        return 0

    io.open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s: %d names, %d flagged" % (OUT, FLOORS, len(flagged)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
